;;; -*- Gerbil -*-
(import :std/test
        :extensions/facade
        :parser/facade)
(export parser-test)

(def (find-call-with-argument calls argument)
  (find (lambda (call)
          (equal? (call-fact-arguments call) [argument]))
        calls))

(def parser-test
  (test-suite "gerbil scheme harness parser"
    (test-case "native reader captures package and definitions"
      (let* ((root (path-normalize "."))
             (file (parse-source-file root "test/fixtures/sample.ss")))
        (check (source-file-package file) => "sample/sample")
        (check (map definition-name (source-file-definitions file))
               => ["answer" "make-answer"])
        (check (map definition-formals (source-file-definitions file))
               => ['() '()])
        (check (map definition-arity (source-file-definitions file))
               => [0 0])
        (check (map top-form-head (source-file-forms file))
               => ["import" "export" "def" "def"])
        (check (map top-form-kind (source-file-forms file))
               => ["import" "export" "definition" "definition"])
        (check (top-form-selector (car (source-file-forms file)))
               => "test/fixtures/sample.ss:5-5")
        (check (source-file-line-count file) => 12)))
    (test-case "native reader captures definition formals"
      (let* ((root (path-normalize "."))
             (file (parse-source-file root "test/fixtures/formals.ss")))
        (check (map definition-name (source-file-definitions file))
               => ["sum-two" "collect"])
        (check (map definition-formals (source-file-definitions file))
               => [["x" "y"] ["xs"]])
        (check (map definition-arity (source-file-definitions file))
               => [2 1])))
    (test-case "native reader captures call facts"
      (let* ((root (path-normalize "."))
             (file (parse-source-file root "test/fixtures/formals.ss"))
             (calls (source-file-calls file)))
        (check (map call-fact-callee calls) => ["+"])
        (check (map call-fact-arity calls) => [2])
        (check (map call-fact-arguments calls) => [["x" "y"]])
        (check (map call-fact-argument-types calls) => [[#f #f]])
        (check (map call-fact-caller calls) => ["sum-two"])
        (check (map call-fact-selector calls)
               => ["test/fixtures/formals.ss:4-5"])))
    (test-case "native reader captures local literal binding argument types"
      (let* ((root (path-normalize ".run/parser-local-literal-binding"))
             (source-dir (string-append root "/src"))
             (source-path (string-append source-dir "/main.ss")))
        (ensure-dir ".run")
        (ensure-dir root)
        (ensure-dir source-dir)
        (write-text source-path
                    "(package: sample/local-literal)\n(def (use-let)\n  (let ((value \"ok\") (bad 10))\n    (needs-string value)\n    (needs-string bad)))\n")
        (let* ((file (parse-source-file root "src/main.ss"))
               (calls (filter (lambda (call)
                                 (equal? (call-fact-callee call) "needs-string"))
                               (source-file-calls file)))
               (value-call (find-call-with-argument calls "value"))
               (bad-call (find-call-with-argument calls "bad")))
          (check (length calls) => 2)
          (check (call-fact-argument-types value-call) => ["string"])
          (check (call-fact-argument-types bad-call) => ["number"])
          (check (map call-fact-caller calls) => ["use-let" "use-let"]))))
    (test-case "native reader propagates sequential local alias argument types"
      (let* ((root (path-normalize ".run/parser-local-alias-binding"))
             (source-dir (string-append root "/src"))
             (source-path (string-append source-dir "/main.ss")))
        (ensure-dir ".run")
        (ensure-dir root)
        (ensure-dir source-dir)
        (write-text source-path
                    "(package: sample/local-alias)\n(def (use-let-star)\n  (let* ((star-value \"ok\")\n         (star-alias star-value)\n         (bad 10)\n         (bad-alias bad))\n    (needs-string star-alias)\n    (needs-string bad-alias)))\n(def (use-let)\n  (let ((plain-value \"ok\")\n        (plain-alias plain-value))\n    (needs-string plain-alias)))\n")
        (let* ((file (parse-source-file root "src/main.ss"))
               (calls (filter (lambda (call)
                                 (equal? (call-fact-callee call) "needs-string"))
                               (source-file-calls file)))
               (star-alias-call (find-call-with-argument calls "star-alias"))
               (bad-alias-call (find-call-with-argument calls "bad-alias"))
               (plain-alias-call (find-call-with-argument calls "plain-alias")))
          (check (length calls) => 3)
          (check (call-fact-argument-types star-alias-call) => ["string"])
          (check (call-fact-argument-types bad-alias-call) => ["number"])
          (check (call-fact-argument-types plain-alias-call) => [#f]))))
    (test-case "native reader tolerates malformed let forms"
      (let* ((root (path-normalize ".run/parser-malformed-let"))
             (source-dir (string-append root "/src"))
             (source-path (string-append source-dir "/main.ss")))
        (ensure-dir ".run")
        (ensure-dir root)
        (ensure-dir source-dir)
        (write-text source-path "(package: sample/main)\n(def answer (let))\n(define)\n")
        (let (file (parse-source-file root "src/main.ss"))
          (check (source-file-parse-error file) => #f)
          (check (map definition-name (source-file-definitions file))
                 => ["answer"])
          (check (source-file-calls file) => '()))))
    (test-case "project collection ignores tree-sitter query files"
      (let* ((root (path-normalize ".run/parser-tree-sitter-ignore"))
             (source-dir (string-append root "/src"))
             (query-dir (string-append root "/tree-sitter/tree-sitter-scheme/queries"))
             (source-path (string-append source-dir "/main.ss"))
             (query-path (string-append query-dir "/locals.scm")))
        (ensure-dir ".run")
        (ensure-dir root)
        (ensure-dir source-dir)
        (ensure-dir (string-append root "/tree-sitter"))
        (ensure-dir (string-append root "/tree-sitter/tree-sitter-scheme"))
        (ensure-dir query-dir)
        (write-text source-path "(package: sample/main)\n(def answer 42)\n")
        (write-text query-path "((identifier) @local.definition)\n")
        (check (map source-file-path (project-index-files (collect-project root)))
               => ["src/main.ss"])))
    (test-case "project collection captures gerbil package dependencies"
      (let* ((root (path-normalize ".run/parser-package"))
             (source-dir (string-append root "/src"))
             (package-path (string-append root "/gerbil.pkg"))
             (source-path (string-append source-dir "/main.ss")))
        (ensure-dir ".run")
        (ensure-dir root)
        (ensure-dir source-dir)
        (write-text package-path
                    "(package: clan/poo\n depend: (\"git.cons.io/mighty-gerbils/gerbil-utils\"))\n")
        (write-text source-path "(package: clan/poo/main)\n(def answer 42)\n")
        (let (package (project-index-package (collect-project root)))
          (check (project-package-path package) => "gerbil.pkg")
          (check (project-package-name package) => "clan/poo")
          (check (project-package-manager package) => "gxpkg")
          (check (project-package-dependencies package)
                 => ["git.cons.io/mighty-gerbils/gerbil-utils"]))))
    (test-case "project package dependency activates poo extension"
      (let* ((root (path-normalize ".run/parser-poo-dependency"))
             (source-dir (string-append root "/src"))
             (package-path (string-append root "/gerbil.pkg"))
             (source-path (string-append source-dir "/main.ss")))
        (ensure-dir ".run")
        (ensure-dir root)
        (ensure-dir source-dir)
        (write-text package-path
                    "(package: sample/app\n depend: (\"git.cons.io/mighty-gerbils/gerbil-poo\"))\n")
        (write-text source-path "(package: sample/app/main)\n(def answer 42)\n")
        (let* ((index (collect-project root))
               (extensions (project-extension-json index))
               (extension (car extensions)))
          (check (project-package-name (project-index-package index)) => "sample/app")
          (check (hash-get extension 'name) => "poo")
          (check (hash-get extension 'activation) => "gerbil.pkg")
          (check (hash-get extension 'packageManager) => "gxpkg")
          (check (hash-get extension 'package) => "sample/app"))))))

(def (ensure-dir path)
  (with-catch
   (lambda (_) #f)
   (lambda () (create-directory path))))

(def (write-text path text)
  (with-catch
   (lambda (_) #f)
   (lambda () (delete-file path)))
  (call-with-output-file path
    (lambda (port) (display text port))))
