#!/usr/bin/env gxi
;; -*- Gerbil -*-
(import :std/make
        :std/misc/process)

(def (build-prefix)
  (getenv "GERBIL_BUILD_PREFIX" (path-expand ".build/gerbil" (current-directory))))

(def (gerbil-bin name)
  (let ((usr-local-bin (string-append "/usr/local/bin/" name))
        (homebrew-bin (string-append "/opt/homebrew/bin/" name))
        (default-bin (path-expand (string-append "bin/" name) (gerbil-home)))
        (sibling-bin (path-expand (string-append "../bin/" name) (gerbil-home))))
    (cond
     ((file-exists? default-bin) default-bin)
     ((file-exists? sibling-bin) sibling-bin)
     ((file-exists? usr-local-bin) usr-local-bin)
     ((file-exists? homebrew-bin) homebrew-bin)
     (else name))))

(def (write-gsc-wrapper real-gsc gambit-root)
  (let ((wrapper (path-expand "bin/gsc-gerbil-build" (build-prefix))))
    (create-directory* (path-directory wrapper))
    (call-with-output-file wrapper
      (lambda (out)
        (display "#!/bin/sh\nexec " out)
        (write real-gsc out)
        (display " " out)
        (write (string-append "-:~~=" gambit-root) out)
        (display " \"$@\"\n" out)))
    (invoke "chmod" ["+x" wrapper])
    wrapper))

(def (write-native-link-wrapper)
  (let ((wrapper (path-expand "bin/gerbil-native-link" (build-prefix))))
    (create-directory* (path-directory wrapper))
    (call-with-output-file wrapper
      (lambda (out)
        (display "#!/bin/sh\n" out)
        (display "set -eu\n\n" out)
        (display "tmp=$1\n" out)
        (display "final=$2\n" out)
        (display "timeout=${ASP_NATIVE_TIMEOUT_SECONDS:-120}\n" out)
        (display "log=${tmp}.log\n\n" out)
        (display "cleanup_artifacts() {\n" out)
        (display "  rm -f \"$tmp\" \"${tmp}__exe.scm\" \"${tmp}__exe.c\" \"${tmp}__exe_.c\" \"${tmp}__exe.o\" \"${tmp}__exe_.o\" \"${tmp}__exe__.c\" \"${tmp}__exe__.o\"\n" out)
        (display "}\n\n" out)
        (display "cleanup_success() {\n" out)
        (display "  cleanup_artifacts\n" out)
        (display "  rm -f \"$log\"\n" out)
        (display "}\n\n" out)
        (display "cleanup_failure() {\n" out)
        (display "  if [ \"${ASP_NATIVE_KEEP_ARTIFACTS:-}\" ]; then\n" out)
        (display "    echo \"native compile artifacts prefix: $tmp\" >&2\n" out)
        (display "  else\n" out)
        (display "    cleanup_artifacts\n" out)
        (display "  fi\n" out)
        (display "  if [ -s \"$log\" ]; then\n" out)
        (display "    echo \"native compile log: $log\" >&2\n" out)
        (display "  else\n" out)
        (display "    rm -f \"$log\"\n" out)
        (display "  fi\n" out)
        (display "}\n\n" out)
        (display "debug_tail() {\n" out)
        (display "  if [ \"${ASP_NATIVE_DEBUG:-}\" ]; then\n" out)
        (display "    tail -12 \"$log\" 2>/dev/null | cut -c 1-180 >&2 || true\n" out)
        (display "  fi\n" out)
        (display "}\n\n" out)
        (display "if [ \"${ASP_NATIVE_DEBUG:-}\" ]; then\n" out)
        (display "  gxc -V -exe -o \"$tmp\" src/cli.ss >\"$log\" 2>&1 &\n" out)
        (display "else\n" out)
        (display "  gxc -exe -o \"$tmp\" src/cli.ss >\"$log\" 2>&1 &\n" out)
        (display "fi\n" out)
        (display "pid=$!\n" out)
        (display "elapsed=0\n" out)
        (display "while kill -0 \"$pid\" 2>/dev/null; do\n" out)
        (display "  if [ \"$elapsed\" -ge \"$timeout\" ]; then\n" out)
        (display "    kill \"$pid\" 2>/dev/null || true\n" out)
        (display "    sleep 1\n" out)
        (display "    kill -9 \"$pid\" 2>/dev/null || true\n" out)
        (display "    wait \"$pid\" 2>/dev/null || true\n" out)
        (display "    echo \"native compile timed out after ${timeout}s; leaving existing provider executable untouched\" >&2\n" out)
        (display "    debug_tail\n" out)
        (display "    cleanup_failure\n" out)
        (display "    exit 124\n" out)
        (display "  fi\n" out)
        (display "  sleep 1\n" out)
        (display "  elapsed=$((elapsed + 1))\n" out)
        (display "done\n\n" out)
        (display "set +e\n" out)
        (display "wait \"$pid\"\n" out)
        (display "status=$?\n" out)
        (display "set -e\n" out)
        (display "if [ \"$status\" -ne 0 ]; then\n" out)
        (display "  debug_tail\n" out)
        (display "  cleanup_failure\n" out)
        (display "  exit \"$status\"\n" out)
        (display "fi\n" out)
        (display "if [ ! -x \"$tmp\" ]; then\n" out)
        (display "  echo \"native compile did not produce executable: $tmp\" >&2\n" out)
        (display "  debug_tail\n" out)
        (display "  cleanup_failure\n" out)
        (display "  exit 1\n" out)
        (display "fi\n" out)
        (display "mv \"$tmp\" \"$final\"\n" out)
        (display "cleanup_success\n" out)))
    (invoke "chmod" ["+x" wrapper])
    wrapper))

(def (write-native-diagnose-wrapper)
  (let ((wrapper (path-expand "bin/gerbil-native-diagnose" (build-prefix))))
    (create-directory* (path-directory wrapper))
    (call-with-output-file wrapper
      (lambda (out)
        (display "#!/bin/sh\n" out)
        (display "set -eu\n\n" out)
        (display "tmp=$1\n" out)
        (display "timeout=${ASP_NATIVE_TIMEOUT_SECONDS:-120}\n" out)
        (display "log=${tmp}.log\n\n" out)
        (display "cleanup_previous() {\n" out)
        (display "  rm -f \"$tmp\" \"$log\" \"${tmp}__exe.scm\" \"${tmp}__exe.c\" \"${tmp}__exe_.c\" \"${tmp}__exe.o\" \"${tmp}__exe_.o\" \"${tmp}__exe__.c\" \"${tmp}__exe__.o\"\n" out)
        (display "}\n\n" out)
        (display "debug_tail() {\n" out)
        (display "  if [ \"${ASP_NATIVE_DEBUG:-}\" ]; then\n" out)
        (display "    tail -12 \"$log\" 2>/dev/null | cut -c 1-180 >&2 || true\n" out)
        (display "  fi\n" out)
        (display "}\n\n" out)
        (display "cleanup_previous\n" out)
        (display "echo \"native diagnose mode=gerbil-front-end command='gxc -S -V -exe'\" >&2\n" out)
        (display "gxc -S -V -exe -o \"$tmp\" src/cli.ss >\"$log\" 2>&1 &\n" out)
        (display "pid=$!\n" out)
        (display "elapsed=0\n" out)
        (display "while kill -0 \"$pid\" 2>/dev/null; do\n" out)
        (display "  if [ \"$elapsed\" -ge \"$timeout\" ]; then\n" out)
        (display "    kill \"$pid\" 2>/dev/null || true\n" out)
        (display "    sleep 1\n" out)
        (display "    kill -9 \"$pid\" 2>/dev/null || true\n" out)
        (display "    wait \"$pid\" 2>/dev/null || true\n" out)
        (display "    echo \"native diagnose timed out after ${timeout}s before Gambit link\" >&2\n" out)
        (display "    debug_tail\n" out)
        (display "    echo \"native diagnose log: $log\" >&2\n" out)
        (display "    echo \"native diagnose artifacts prefix: $tmp\" >&2\n" out)
        (display "    exit 124\n" out)
        (display "  fi\n" out)
        (display "  sleep 1\n" out)
        (display "  elapsed=$((elapsed + 1))\n" out)
        (display "done\n\n" out)
        (display "set +e\n" out)
        (display "wait \"$pid\"\n" out)
        (display "status=$?\n" out)
        (display "set -e\n" out)
        (display "debug_tail\n" out)
        (display "echo \"native diagnose log: $log\" >&2\n" out)
        (display "echo \"native diagnose artifacts prefix: $tmp\" >&2\n" out)
        (display "if [ \"$status\" -ne 0 ]; then\n" out)
        (display "  exit \"$status\"\n" out)
        (display "fi\n" out)
        (display "echo \"native diagnose gerbil-front-end=ok gambit-link=skipped\" >&2\n" out)))
    (invoke "chmod" ["+x" wrapper])
    wrapper))

(def (ensure-gerbil-gsc!)
  (let (gsc (gerbil-bin "gsc"))
    (when (file-exists? gsc)
      (setenv "GERBIL_GSC"
              (write-gsc-wrapper gsc
                                 (path-normalize (gerbil-home)))))))

(def (ensure-source-load-path!)
  (add-load-path! (path-expand "src" (current-directory))))

(def (compile-command? args)
  (or (member "compile" args)
      (member "full" args)
      (member "native" args)
      (member "native-link" args)
      (member "native-diagnose" args)))

(def (native-command? args)
  (or (member "native" args)
      (member "native-link" args)))

(def (full-command? args)
  (or (member "full" args)
      (member "native" args)))

(def (gerbil-poo-installed-at? root)
  (and root
       (file-exists?
        (path-expand "lib/clan/poo/object.ssi" root))))

(def (home-gerbil-root)
  (let (home (getenv "HOME" #f))
    (and home (path-expand ".gerbil" home))))

(def (local-gerbil-poo-installed?)
  (gerbil-poo-installed-at?
   (path-expand ".gerbil" (current-directory))))

(def (home-gerbil-poo-installed?)
  (gerbil-poo-installed-at? (home-gerbil-root)))

(def (ensure-package-dependencies!)
  (unless (local-gerbil-poo-installed?)
    (if (home-gerbil-poo-installed?)
      (display "... install package dependencies into provider .gerbil (global gerbil-poo detected)\n")
      (display "... install package dependencies into provider .gerbil\n"))
    (invoke "gxpkg" ["deps" "-i"])))

(def (clean-compiled-provider-artifacts!)
  (let* ((lib-root (path-expand ".gerbil/lib" (current-directory)))
         (static-root (path-expand "static" lib-root))
         (package-root
          (path-expand "gerbil-scheme-language-project-harness" lib-root)))
    (display "... clean stale compiled provider artifacts\n")
    (invoke "rm" ["-rf" package-root])
    (when (file-exists? static-root)
      (invoke "find"
              [static-root
               "-name"
               "gerbil-scheme-language-project-harness__*.scm"
               "-delete"]))))

(def (static-provider-artifacts-present?)
  (file-exists?
   (path-expand
    ".gerbil/lib/static/gerbil-scheme-language-project-harness__src__cli.scm"
    (current-directory))))

(def (provider-bin-dir)
  (let ((override (getenv "ASP_PROVIDER_BIN_DIR" #f))
        (monorepo-root (path-expand "../.." (current-directory))))
    (cond
     ((and override (not (equal? override "")))
      (path-expand override (current-directory)))
     ((file-exists? (path-expand "asp.toml" monorepo-root))
      (path-expand ".bin" monorepo-root))
     (else (path-expand ".bin" (current-directory))))))

(def (write-native-cli!)
  (let* ((binary (path-expand "gerbil-scheme-harness"
                              (provider-bin-dir)))
         (tmp-binary (string-append binary ".native-tmp"))
         (exe-stub (string-append tmp-binary "__exe.scm")))
    (display "... compile native ")
    (display binary)
    (newline)
    (create-directory* (path-directory binary))
    (set-provider-compile-env!)
    (invoke "rm" ["-f" tmp-binary exe-stub])
    (invoke (write-native-link-wrapper)
            [tmp-binary binary])
    (when (file-exists? exe-stub)
      (invoke "rm" ["-f" exe-stub]))
    (invoke "chmod" ["+x" binary])
    binary))

(def (run-native-diagnose!)
  (let* ((diagnose-dir (path-expand "native-diagnose" (build-prefix)))
         (tmp-binary (path-expand "gerbil-scheme-harness.native-diagnose"
                                  diagnose-dir)))
    (display "... diagnose native ")
    (display tmp-binary)
    (newline)
    (create-directory* diagnose-dir)
    (set-provider-compile-env!)
    (unless (static-provider-artifacts-present?)
      (error "native diagnose requires static provider artifacts; run `gxi build.ss full` or `gxi build.ss native` first"))
    (invoke (write-native-diagnose-wrapper)
            [tmp-binary])
    tmp-binary))

(def (write-provider-cli!)
  (let* ((binary (path-expand "gerbil-scheme-harness"
                              (provider-bin-dir)))
         (harness-root (path-normalize (current-directory))))
    (display "... write provider executable ")
    (display binary)
    (newline)
    (create-directory* (path-directory binary))
    (call-with-output-file binary
      (lambda (out)
        (display "#!/usr/bin/env sh\n" out)
        (display "set -eu\n\n" out)
        (display "HARNESS=" out)
        (write harness-root out)
        (display "\n\n" out)
        (display "if [ \"${GERBIL:-}\" ]; then\n" out)
        (display "  GERBIL_BIN=\"$GERBIL\"\n" out)
        (display "elif command -v gxi >/dev/null 2>&1; then\n" out)
        (display "  GERBIL_BIN=\"$(command -v gxi)\"\n" out)
        (display "elif [ -x /usr/local/bin/gxi ]; then\n" out)
        (display "  GERBIL_BIN=/usr/local/bin/gxi\n" out)
        (display "elif [ -x /opt/homebrew/bin/gxi ]; then\n" out)
        (display "  GERBIL_BIN=/opt/homebrew/bin/gxi\n" out)
        (display "else\n" out)
        (display "  GERBIL_BIN=gxi\n" out)
        (display "fi\n\n" out)
        (display "GERBIL_PATH=\"${GERBIL_PATH:-$HARNESS/.gerbil}\"\n" out)
        (display "GERBIL_LOADPATH=\"${GERBIL_LOADPATH:-$HARNESS/src}\"\n" out)
        (display "export GERBIL_PATH GERBIL_LOADPATH\n\n" out)
        (display "json=0\n" out)
        (display "for arg in \"$@\"; do\n" out)
        (display "  if [ \"$arg\" = --json ]; then json=1; fi\n" out)
        (display "done\n\n" out)
        (display "if [ \"$json\" = 0 ] && [ \"${1:-}\" = search ] && [ \"${2:-}\" = extension ] && { [ \"${3:-}\" = poo ] || [ \"${3:-}\" = gerbil-poo ]; }; then\n" out)
        (display "  shift 2\n" out)
        (display "  exec \"$GERBIL_BIN\" \"$HARNESS/bin/gerbil-scheme-search-extension.ss\" \"$@\"\n" out)
        (display "fi\n\n" out)
        (display "if [ \"$json\" = 0 ] && [ \"${1:-}\" = search ] && [ \"${2:-}\" = pattern ] && [ \"${3:-}\" = gerbil-poo ]; then\n" out)
        (display "  shift 2\n" out)
        (display "  exec \"$GERBIL_BIN\" \"$HARNESS/bin/gerbil-scheme-search-pattern.ss\" \"$@\"\n" out)
        (display "fi\n\n" out)
        (display "if [ \"${1:-}\" = search ]; then\n" out)
        (display "  shift\n" out)
        (display "  exec \"$GERBIL_BIN\" \"$HARNESS/bin/gerbil-scheme-search.ss\" \"$@\"\n" out)
        (display "fi\n\n" out)
        (display "exec \"$GERBIL_BIN\" \"$HARNESS/bin/gerbil-scheme-harness.ss\" \"$@\"\n" out)))
    (invoke "chmod" ["+x" binary])
    binary))

(def +build-spec+ '("src/cli"))

(def (build-keys)
  [libdir: (path-expand "lib" (build-prefix))
   bindir: (path-expand "bin" (build-prefix))
   debug: #f])

(def (parse-build-options args)
  (let lp ((rest args)
           (options '()))
    (cond
     ((null? rest) options)
     ((equal? (car rest) "--release")
      (lp (cdr rest) (cons 'build-release: (cons #t options))))
     ((equal? (car rest) "--optimized")
      (lp (cdr rest) (cons 'build-optimized: (cons #t options))))
     ((equal? (car rest) "--debug")
      (lp (cdr rest) (cons 'debug: (cons #t options))))
     (else (error "Unexpected " rest)))))

(def (make-provider! options)
  (apply make
         +build-spec+
         srcdir: (current-directory)
         (append options (build-keys))))

(def (clean-provider!)
  (apply make-clean
         +build-spec+
         srcdir: (current-directory)
         (build-keys)))

(def (set-provider-compile-env!)
  (setenv "GERBIL_PATH" (path-expand ".gerbil" (current-directory)))
  (setenv "GERBIL_LOADPATH" (path-expand "src" (current-directory))))

(def (refresh-static-provider-artifacts!)
  (display "... refresh static provider artifacts\n")
  (set-provider-compile-env!)
  (invoke "sh"
          ["-c"
           "find src -name '*.ss' -print | sort | xargs -P 8 -n 1 gxc -static -d .gerbil/lib"]))

(def (run-build! args)
  (cond
   ((null? args) (make-provider! '()))
   ((equal? (car args) "meta")
    (write ["spec" "compile" "full" "native" "native-link" "native-diagnose" "clean"])
    (newline))
   ((equal? (car args) "spec")
    (pretty-print +build-spec+))
   ((equal? (car args) "clean")
    (clean-provider!))
   ((equal? (car args) "compile")
    (write-provider-cli!))
   ((equal? (car args) "full")
    (make-provider! (parse-build-options (cdr args)))
    (refresh-static-provider-artifacts!)
    (write-provider-cli!))
   ((equal? (car args) "native")
    (make-provider! (parse-build-options (cdr args)))
    (refresh-static-provider-artifacts!)
    (write-native-cli!))
   ((equal? (car args) "native-link")
    (write-native-cli!))
   ((equal? (car args) "native-diagnose")
    (run-native-diagnose!))
   (else (error "Unexpected " args))))

(def (main . args)
  (ensure-gerbil-gsc!)
  (ensure-source-load-path!)
  (when (compile-command? args)
    (ensure-package-dependencies!)
    (when (full-command? args)
      (clean-compiled-provider-artifacts!)))
  (run-build! args))
