;;; -*- Gerbil -*-
;;; Reusable downstream POO policy scenario fixtures.

(import :gerbil/gambit)

(export write-poo-direct-writeenv-project
        write-poo-io-override-project
        write-downstream-poo-agent-project
        write-poo-method-shape-project
        write-downstream-poo-agent-positive-project
        write-poo-prototype-fixed-point-drift-project
        write-poo-prototype-fixed-point-positive-project
        write-poo-prototype-boundary-read-project)
;; : (-> String Unit )
(def (write-poo-direct-writeenv-project root)
  (let* ((src (string-append root "/src"))
         (owner (string-append src "/orders")))
    (ensure-dir ".run")
    (ensure-dir root)
    (ensure-dir src)
    (ensure-dir owner)
    (write-text (string-append owner "/io.ss")
                ";;; -*- Gerbil -*-\n(import :clan/poo/io)\n(def (render order) (writeenv order))\n")))
;; : (-> String String )
(def (write-poo-io-override-project root)
  (let* ((src (string-append root "/src"))
         (owner (string-append src "/orders")))
    (ensure-dir ".run")
    (ensure-dir root)
    (ensure-dir src)
    (ensure-dir owner)
    (write-text (string-append owner "/io.ss")
                ";;; -*- Gerbil -*-\n(import :clan/poo/io)\n(defmethod (@method :wr object) (lambda (self writeenv) self))\n")))
;; : (-> String Unit )
(def (write-downstream-poo-agent-project root)
  (let* ((src (string-append root "/src"))
         (owner (string-append src "/orders")))
    (ensure-dir ".run")
    (ensure-dir root)
    (ensure-dir src)
    (ensure-dir owner)
    (write-text (string-append owner "/core.ss")
                ";;; -*- Gerbil -*-\n(package: sample/orders)\n(def (process order) order)\n(def (make-order id total) (hash (id id) (total total)))\n(def (order-total order) order)\n")
    (write-text (string-append owner "/io.ss")
                ";;; -*- Gerbil -*-\n(import :clan/poo/io)\n(defmethod (@method :wr object) (lambda (self writeenv) (writeenv self)))\n")))
;; : (-> String Unit )
(def (write-poo-method-shape-project root)
  (let* ((src (string-append root "/src"))
         (owner (string-append src "/orders")))
    (ensure-dir ".run")
    (ensure-dir root)
    (ensure-dir src)
    (ensure-dir owner)
    (write-text (string-append owner "/methods.ss")
                ";;; -*- Gerbil -*-\n(package: sample/orders)\n(import :clan/poo/mop)\n(defmethod (@method order-discount Order) (lambda (self amount) amount))\n")))
;; : (-> String Unit )
(def (write-poo-prototype-fixed-point-drift-project root)
  (let* ((src (string-append root "/src"))
         (owner (string-append src "/orders")))
    (ensure-dir ".run")
    (ensure-dir root)
    (ensure-dir src)
    (ensure-dir owner)
    (write-text (string-append owner "/core.ss")
                ";;; -*- Gerbil -*-\n(package: sample/orders)\n(import :clan/poo/brace)\n(def (make-order source)\n  (let ((id (.ref source 'id))\n        (total (.ref source 'total)))\n    (hash (id id) (total total))))\n")))
;; : (-> String Unit )
(def (write-poo-prototype-fixed-point-positive-project root)
  (let* ((src (string-append root "/src"))
         (owner (string-append src "/orders")))
    (ensure-dir ".run")
    (ensure-dir root)
    (ensure-dir src)
    (ensure-dir owner)
    (write-text (string-append owner "/core.ss")
                ";;; -*- Gerbil -*-\n;;; Fixture keeps POO fixed-point behavior inside one prototype.\n(package: sample/orders)\n(import :clan/poo/brace)\n(def base {id: 1 total: 2 meta: {currency: 'USD}})\n(def order {(:: @ base)\n            total: => 1+\n            meta: =>.+ {source: 'agent}\n            status: ? 'draft})\n(def order-view (.mix order))\n"))
    )
;; : (-> String Unit )
(def (write-poo-prototype-boundary-read-project root)
  (let* ((src (string-append root "/src"))
         (owner (string-append src "/orders")))
    (ensure-dir ".run")
    (ensure-dir root)
    (ensure-dir src)
    (ensure-dir owner)
    (write-text (string-append owner "/core.ss")
                ";;; -*- Gerbil -*-\n(package: sample/orders)\n(import :clan/poo/brace)\n(def (order-id source)\n  (.ref source 'id))\n")))
;; : (-> String Unit )
(def (write-downstream-poo-agent-positive-project root)
  (let* ((src (string-append root "/src"))
         (owner (string-append src "/orders")))
    (ensure-dir ".run")
    (ensure-dir root)
    (ensure-dir src)
    (ensure-dir owner)
    (write-text (string-append owner "/core.ss")
                ";;; -*- Gerbil -*-\n;;; Fixture preserves parser-visible POO and combinator evidence for agent repair tests.\n(package: sample/orders)\n(import (only-in :clan/poo/object defclass object))\n;;; POO invariant: keep Order as a class so method policy has runtime model evidence.\n;; Order <- Id Total\n(defclass (Order object) (id total) transparent: #t)\n;; Total <- Order\n(def (order-total order) order)\n;;; Composition boundary: summary stays parser-visible as map evidence for R013.\n;; Summary <- Order\n(def (order-summary order) (car (map order-total [order])))\n")
    (write-text (string-append owner "/methods.ss")
                ";;; -*- Gerbil -*-\n;;; Fixture keeps generic and method evidence split for downstream POO repairs.\n(package: sample/orders)\n(import (only-in :clan/poo/mop .defgeneric defmethod @method))\n;;; Generic boundary: declare the method shape before adding specializers.\n;; Amount <- Order Amount\n(.defgeneric (order-discount Order amount))\n;;; Method boundary: keep the override parser-visible without runtime IO mutation.\n;; Amount <- Order Amount\n(defmethod (@method order-discount Order) (lambda (self amount) (car (map (lambda (value) value) [amount]))))\n")))
;; : (-> String EnsureDir )
(def (ensure-dir path)
  (with-catch
   (lambda (_) #f)
   (lambda () (create-directory path))))
;; : (-> String SourceLine Unit )
(def (write-text path text)
  (delete-file-if-exists path)
  (call-with-output-file path
    (lambda (port) (display text port))))
;; : (-> String DeleteFileIfExists )
(def (delete-file-if-exists path)
  (with-catch
   (lambda (_) #f)
   (lambda () (delete-file path))))
