;;; -*- Gerbil -*-
;;; Agent-facing typed-combinator quality facet steering.

(export typed-combinator-style-quality-facet-steering)

;;; Native facet steering turns parser-owned Gerbil quality facts into bounded repair moves.
;;; This keeps agent freedom in naming while constraining the rewrite strategy to witnessed syntax.
;; : (-> (List QualityFacet) (List RepairMove) )
(def (typed-combinator-style-quality-facet-steering quality-facets)
  (filter identity
          [(and (member "expression-level-composition" quality-facets)
                "prefer map/filter/filter-map/fold pipelines; extract predicate, mapper, or reducer helpers before rewriting loops")
           (and (member "manual-loop-drift" quality-facets)
                "replace manual loops with map/filter/filter-map/fold pipelines when parser facts show no IO/state/generator witness")
           (and (member "over-abstracted-contract-risk" quality-facets)
                "replace abstract grouped contracts with concrete domain/result names or add parser-owned callsite evidence")
           (and (member "scheme-native-typed-block-migration" quality-facets)
                "migrate legacy ;; Output <- Input contract comments to adjacent Scheme-native ;; : (-> Input Output) blocks; add ;; | type aliases for enum/refinement names")
           (and (member "combinator-composition" quality-facets)
                "prefer cut/curry/rcurry/compose helper composition when arity evidence already matches")
           (and (member "lambda-local-abstraction" quality-facets)
                "prefer small local lambda/function-factory helpers when the behavior is a reusable transform")
           (and (member "lambda-match-rewrite-opportunity" quality-facets)
                "replace unary lambdas whose whole body matches the same argument with gerbil-utils/base.ss lambda-match or lambda-ematch")
           (and (member "lambda-match-destructuring" quality-facets)
                "keep pattern destructuring at the function boundary instead of hiding it behind anonymous wrapper lambdas")
           (and (member "named-lambda-helper" quality-facets)
                "use gerbil-utils/base.ss style fun helpers when a local named lambda makes the transform reusable without recursive self-reference")
           (and (member "parameterized-transform" quality-facets)
                "keep lambda/lambda-match parameters meaningful and push repeated destructuring into named helpers")
           (and (member "case-lambda-optimization-boundary" quality-facets)
                "preserve case-lambda or common-case specialization and document the optimization boundary")
           (and (member "multi-arity-abstraction" quality-facets)
                "use case-lambda when a helper has real arity variants instead of branching on raw argument lists")
           (and (member "function-specialization-abstraction" quality-facets)
                "use cut/curry/rcurry for first-class specialization instead of repeated wrapper lambdas")
           (and (member "eta-wrapper-drift" quality-facets)
                "replace eta-wrapper lambdas with the direct function, cut, curry/rcurry, or compose/rcompose according to argument shape")
           (and (member "function-pipeline-abstraction" quality-facets)
                "use compose/rcompose/!>/!!> when the data flow is a reusable function pipeline")
           (and (member "base-style-combinator-composition" quality-facets)
                "model reusable data flow after gerbil-utils/base.ss combinators: λ/lambda-match for local destructuring, fun for named lambdas, and compose/!>/curry/rcurry for first-class flow")
           (and (member "higher-order-constructor-abstraction" quality-facets)
                "preserve function-constructor boundaries that combine case-lambda with returned procedures")
           (and (member "arity-specialized-function-factory" quality-facets)
                "use nested case-lambda only for real arity specialization and keep the optimization boundary explicit")
           (and (member "wrapper-lambda-drift" quality-facets)
                "extract repeated wrapper lambdas into a named factory, case-lambda function factory, curry/rcurry specializer, or compose/rcompose pipeline")
           (and (member "function-specialization-opportunity" quality-facets)
                "repair anonymous specialization by introducing one first-class helper boundary before changing call sites")
           (and (member "boolean-normalization-drift" quality-facets)
                "replace double-negation scaffolding with the underlying boolean expression, or name the predicate boundary when truthiness normalization is intentional")
           (and (member "generated-scaffold-shape" quality-facets)
                "treat obvious generated scaffolding as a repair trigger: remove redundant wrappers before adding new abstraction")
           (and (member "anti-ai-scaffold-boundary" quality-facets)
                "replace generated-looking protocol scaffolding with local adapter boundaries; use compose or define-type methods.* shape when representation steps are already proven")
           (and (member "list-combinator-boundary" quality-facets)
                "replace hand-written list recursion scaffolding with small mapper, selector, reducer, filter-map, fold, or builder boundaries when parser facts prove pure traversal")
           (and (member "destructuring-combinator-boundary" quality-facets)
                "replace repeated car/cdr/assq temporary-binding scaffolding with match/lambda-match, named selector helpers, or local slot/lens boundaries")
           (and (member "result-index-scaffold" quality-facets)
                "replace anonymous vector-ref result/index protocols with values binding, named records, or a small domain object boundary")
           (and (member "builder-or-fold-combinator" quality-facets)
                "prefer for/fold or with-list-builder only when parser facts show a real accumulator or builder boundary")
           (and (member "generator-combinator-boundary" quality-facets)
                "when contracts mention Generating, prefer a named generator protocol boundary such as map, fold, partition, or merge style before hand-written producer loops; do not require a downstream gerbil-utils dependency")
           (and (member "protocol-serialization-boundary" quality-facets)
                "when one owner mixes JSON/string/bytes/marshal representation layers, split local protocol adapters so marshal boundaries are self-delimited, raw bytes adapters stay representation-only, and reader/writer symmetry is explicit; do not require gerbil-poo or gerbil-utils dependencies")
           (and (member "slot-lens-boundary" quality-facets)
                "when one owner mixes slot/get/set/modify/validation responsibilities, introduce local lens or slot descriptor helpers and keep validation at the update boundary; do not require gerbil-poo or gerbil-utils dependencies")
           (and (member "concurrency-control-boundary" quality-facets)
                "when one owner mixes spawn/join/mutex/race/thread-parameter responsibilities, split local concurrency helpers, name sequentialization and join boundaries, and preserve parameter propagation without requiring gerbil-utils dependencies")
           (and (member "exception-continuation-boundary" quality-facets)
                "when one owner mixes exception, continuation, handler, context, and raise responsibilities, split a local exception boundary that preserves handler restoration, contextual logging, and re-raise behavior; do not require gerbil-utils dependencies")
           (and (member "controlled-macro-syntax-boundary" quality-facets)
                "when parser facts show macro owners, use upstream Gerbil macro-library idioms; keep syntax wrappers thin and hygienic, and push reusable runtime behavior into ordinary helpers")
           (and (member "poo-typeclass-algebra-boundary" quality-facets)
                "when POO facts expose typeclass/functor/wrapper options, model the implementation after gerbil-poo/fun.ss algebra instead of raw object adapters or ad hoc tables")
           (and (member "method-table-combinator-body" quality-facets)
                "preserve method-table slots that already use cut/curry/compose/pipeline or selector-shaped bodies")
           (and (member "method-table-lambda-drift" quality-facets)
                "repair method-table lambdas by extracting slot-shaped helpers or using cut/curry/compose while preserving the receiver/protocol boundary")
           (and (member "method-table-low-level-body" quality-facets)
                "move low-level method-table calls or compounds behind named helpers before widening the adapter")]))
