;;; -*- Gerbil -*-
;;; Agent-facing typed-combinator quality facet steering.

(export typed-combinator-style-quality-facet-steering)

;;; Native facet steering turns parser-owned Gerbil quality facts into bounded repair moves.
;;; This keeps agent freedom in naming while constraining the rewrite strategy to witnessed syntax.
;; : (-> (List QualityFacet) (List RepairMove) )
(def (typed-combinator-style-quality-facet-steering quality-facets)
  (filter identity
          [(and (member "expression-level-composition" quality-facets)
                "prefer map/filter/filter-map/fold pipelines; extract predicate, mapper, or reducer helpers before rewriting loops")
           (and (member "manual-loop-drift" quality-facets)
                "replace manual loops with map/filter/filter-map/fold pipelines when parser facts show no IO/state/generator witness")
           (and (member "reader-collection-boundary" quality-facets)
                "when a reader loop also does selection or projection, split a source/form reader helper and compose the public function with filter-map/map/fold")
           (and (member "inline-file-reader-boundary" quality-facets)
                "when a file helper opens a port and owns the EOF loop inline, extract a port reader helper and pass it directly to call-with-input-file")
           (and (member "over-abstracted-contract-risk" quality-facets)
                "replace abstract grouped contracts with concrete domain/result names or add parser-owned callsite evidence")
           (and (member "scheme-native-typed-block-migration" quality-facets)
                "use adjacent Scheme-native ;; : (-> Input Output) blocks; add ;; | type aliases for enum/refinement names")
           (and (member "combinator-composition" quality-facets)
                "prefer cut/curry/rcurry/compose helper composition when arity evidence already matches")
           (and (member "lambda-local-abstraction" quality-facets)
                "prefer small local lambda/function-factory helpers when the behavior is a reusable transform")
           (and (member "lambda-match-rewrite-opportunity" quality-facets)
                "replace unary lambdas whose whole body matches the same argument with gerbil-utils/base.ss lambda-match or lambda-ematch")
           (and (member "lambda-match-destructuring" quality-facets)
                "keep pattern destructuring at the function boundary instead of hiding it behind anonymous wrapper lambdas")
           (and (member "named-lambda-helper" quality-facets)
                "use gerbil-utils/base.ss style fun helpers when a local named lambda makes the transform reusable without recursive self-reference")
           (and (member "parameterized-transform" quality-facets)
                "keep lambda/lambda-match parameters meaningful and push repeated destructuring into named helpers")
           (and (member "case-lambda-optimization-boundary" quality-facets)
                "preserve case-lambda or common-case specialization and document the optimization boundary")
           (and (member "multi-arity-abstraction" quality-facets)
                "use case-lambda when a helper has real arity variants instead of branching on raw argument lists")
           (and (member "function-specialization-abstraction" quality-facets)
                "use cut/curry/rcurry for first-class specialization instead of repeated wrapper lambdas")
           (and (member "eta-wrapper-drift" quality-facets)
                "replace eta-wrapper lambdas with the direct function, cut, curry/rcurry, or compose/rcompose according to argument shape")
           (and (member "function-pipeline-abstraction" quality-facets)
                "use compose/rcompose/!>/!!> when the data flow is a reusable function pipeline")
           (and (member "base-style-combinator-composition" quality-facets)
                "model reusable data flow after gerbil-utils/base.ss combinators: λ/lambda-match for local destructuring, fun for named lambdas, and compose/!>/curry/rcurry for first-class flow")
           (and (member "higher-order-constructor-abstraction" quality-facets)
                "preserve function-constructor boundaries that combine case-lambda with returned procedures")
           (and (member "arity-specialized-function-factory" quality-facets)
                "use nested case-lambda only for real arity specialization and keep the optimization boundary explicit")
           (and (member "wrapper-lambda-drift" quality-facets)
                "extract repeated wrapper lambdas into a named factory, case-lambda function factory, curry/rcurry specializer, or compose/rcompose pipeline")
           (and (member "function-specialization-opportunity" quality-facets)
                "repair anonymous specialization by introducing one first-class helper boundary before changing call sites")
           (and (member "boolean-normalization-drift" quality-facets)
                "replace double-negation scaffolding with the underlying boolean expression, or name the predicate boundary when truthiness normalization is intentional")
           (and (member "generated-scaffold-shape" quality-facets)
                "treat obvious generated scaffolding as a repair trigger: remove redundant wrappers before adding new abstraction")
           (and (member "anti-ai-scaffold-boundary" quality-facets)
                "replace generated-looking protocol scaffolding with local adapter boundaries; use compose or define-type methods.* shape when representation steps are already proven")
           (and (member "list-combinator-boundary" quality-facets)
                "replace hand-written list recursion scaffolding with small mapper, selector, reducer, filter-map, fold, or builder boundaries when parser facts prove pure traversal")
           (and (member "std-sugar-flow-boundary" quality-facets)
                "replace nested let/if flow scaffolding with std/sugar chain or if-let/when-let when parser facts show a local expression-flow boundary")
           (and (member "parser-combinator-boundary" quality-facets)
                "replace hand-written string cursor parser state machines with std/parser defparser grammar boundaries, using parser-fail/parser-rewind and raise-parse-error for source-aware failures")
           (and (member "destructuring-combinator-boundary" quality-facets)
                "replace repeated car/cdr/assq temporary-binding scaffolding with match/lambda-match, named selector helpers, or local slot/lens boundaries")
           (and (member "pair-tuple-projection-boundary" quality-facets)
                "replace cons-built Pair tuple results with values/call-with-values unless pair/list protocol behavior is the public contract")
           (and (member "result-index-scaffold" quality-facets)
                "replace anonymous vector-ref result/index protocols with values binding, named records, or a small domain object boundary")
           (and (member "builder-or-fold-combinator" quality-facets)
                "prefer for/fold or with-list-builder only when parser facts show a real accumulator or builder boundary")
           (and (member "generator-combinator-boundary" quality-facets)
                "when contracts mention Generating, prefer a named generator protocol boundary such as map, fold, partition, or merge style before hand-written producer loops; do not require a downstream gerbil-utils dependency")
           (and (member "protocol-serialization-boundary" quality-facets)
                "when one owner mixes JSON/string/bytes/marshal representation layers, split local protocol adapters so marshal boundaries are self-delimited, raw bytes adapters stay representation-only, and reader/writer symmetry is explicit; do not require gerbil-poo or gerbil-utils dependencies")
           (and (member "slot-lens-boundary" quality-facets)
                "when one owner mixes slot/get/set/modify/validation responsibilities, introduce local lens or slot descriptor helpers; use Gerbil `using (value :- Type)` for known class/interface descriptors and keep validation at the update boundary without requiring gerbil-poo or gerbil-utils dependencies")
           (and (member "concurrency-control-boundary" quality-facets)
                "when one owner mixes spawn/join/mutex/race/thread-parameter responsibilities, split local concurrency helpers, name sequentialization and join boundaries, and preserve parameter propagation without requiring gerbil-utils dependencies")
           (and (member "dynamic-scope-cleanup-boundary" quality-facets)
                "wrap manual current-directory/current-port save and restore in dynamic-wind, with-unwind-protect, or parameterize so cleanup runs across exceptions and continuations")
           (and (member "ssxi-optimizer-metadata-boundary" quality-facets)
                "when one owner mixes SSXI metadata, inline rules, optimizer assumptions, primitive calls, and dynamic apply, keep metadata adjacent to the direct primitive boundary so unchecked-call and inline-rule visibility stays compiler-owned")
           (and (member "expander-root-boundary" quality-facets)
                "when one owner mixes module import, expander context, phase/phi state, syntax artifacts, and delayed eval/runtime helpers, split the staged expander root into module-context, transformer, and ordinary runtime boundaries")
           (and (member "actor-runtime-boundary" quality-facets)
                "when one owner mixes actor spawn, mailbox send/receive, shutdown, supervision, and parameters, split the actor runtime protocol into explicit mailbox, lifecycle, and parameter-propagation helpers")
           (and (member "mop-c3-linearization-boundary" quality-facets)
                "when one owner mixes MOP descriptors, class/superclass shape, C3 precedence, tail merging, and compatibility checks, split descriptor construction from linearization merge helpers")
           (and (member "exception-continuation-boundary" quality-facets)
                "when one owner mixes exception, continuation, handler, context, and raise responsibilities, split a local exception boundary that preserves handler restoration, contextual logging, and re-raise behavior; do not require gerbil-utils dependencies")
           (and (member "macro-metaprogramming-decision-boundary" quality-facets)
                "use declarative defrules/syntax-rules for fixed macro families; upgrade to procedural syntax-case/with-syntax only for syntax-object validation, identifier reconstruction, or source-aware errors")
           (and (member "syntax-parameterized-context-boundary" quality-facets)
                "replace mutable compile-time globals with defsyntax-parameter* plus syntax-parameterize so macro-local context is scoped, source-aware, and phase-safe")
           (and (member "syntax-local-registry-boundary" quality-facets)
                "replace syntax->datum keyed macro registry tables with defsyntax metadata objects and syntax-local-value lookup so identifier metadata stays hygienic and phase-owned")
           (and (member "macro-family-boundary" quality-facets)
                "collapse repeated same-prefix thin macros into one hygienic macro family helper or table; split shared parse/validate logic from syntax generation, then keep runtime behavior in ordinary functions")
           (and (member "phase-aware-macro-boundary" quality-facets)
                "when one owner mixes meta-syntactic tower, phase/context state, transformer parsing, expansion, and runtime helpers, split phase-aware macro parsing from ordinary runtime helpers and document the expansion contract")
           (and (member "controlled-macro-syntax-boundary" quality-facets)
                "when parser facts show macro owners, use upstream Gerbil macro-library idioms; parse complex syntax into a small local IR, keep syntax wrappers thin and hygienic, parameterize phase/context state instead of mutating global macro state, and push reusable runtime behavior into ordinary helpers")
           (and (member "match-extension-boundary" quality-facets)
                "when one macro owner mixes match pattern parsing, syntax-local match macro lookup, applicative destructuring, struct/class accessors, and source-aware parse errors, use defsyntax-for-match or applicative match helpers instead of a hand-rolled dispatcher")
           (and (member "mop-class-macro-boundary" quality-facets)
                "when one macro owner mixes class descriptors, slot layout, mixin accessors, mutators, constructor/predicate metadata, and method binding, replace table-shaped class generation with defclass-style descriptor helpers and narrow defmethod/runtime binding boundaries")
           (and (member "macro-phase-optimizer-visible-fast-path" quality-facets)
                "when a macro DSL generates runtime hot paths, keep the macro surface thin but generate lexical direct helpers so SSXI metadata and known-call optimization can still see the call boundary")
           (and (member "gambit-numeric-primitive-boundary" quality-facets)
                "when parser facts show a numeric hot loop with generic arithmetic, state the fixnum/flonum domain at the boundary, keep overflow/type behavior tested, and use Gambit fx/fl primitive families only inside that proven lane")
           (and (member "gerbil-inline-rule-call-shape" quality-facets)
                "when parser facts show repeated dynamic apply in a hot loop, keep primitive targets lexical and direct so Gerbil builtin inline rules and unchecked call optimization can see the call shape")
           (and (member "poo-typeclass-algebra-boundary" quality-facets)
                "when POO facts expose typeclass/functor/wrapper options, model the implementation after gerbil-poo/fun.ss algebra instead of raw object adapters or ad hoc tables")
           (and (member "method-table-combinator-body" quality-facets)
                "preserve method-table slots that already use cut/curry/compose/pipeline, selector-shaped bodies, or Gerbil compiler-style pass handlers with ast-case shape dispatch")
           (and (member "method-table-lambda-drift" quality-facets)
                "repair method-table lambdas by extracting slot-shaped helpers, compiler-style AST pass handlers, or cut/curry/compose adapters while preserving the receiver/protocol boundary")
           (and (member "method-table-low-level-body" quality-facets)
                "move low-level method-table calls or compounds behind named helpers or table-driven pass methods before widening the adapter")]))
