;;; -*- Gerbil -*-
;;; Stable policy facade for Gerbil project rules.

(import :policy/agent
        :policy/agent-poo
        :policy/agent-build
        :policy/core
        :policy/model
        :policy/modularity
        :policy/repair)

(export make-policy-rule
        policy-rule-id
        policy-rule-severity
        +modularity-facade-rule+
        +modularity-source-leaf-rule+
        +modularity-owner-collision-rule+
        +modularity-repeated-owner-entry-rule+
        +modularity-bin-entrypoint-rule+
        +modularity-test-directory-rule+
        +modularity-test-leaf-rule+
        +agent-intent-rule+
        +agent-generic-owner-rule+
        +agent-export-conflict-rule+
        +agent-vague-definition-rule+
        +agent-top-level-executable-rule+
        +agent-poo-direct-writeenv-rule+
        +agent-poo-io-runtime-witness-rule+
        +agent-poo-method-shape-rule+
        +agent-functional-idiom-advice-rule+
        +agent-poo-object-model-rule+
        +agent-macro-runtime-source-witness-rule+
        +agent-protocol-evidence-rule+
        +agent-typed-combinator-style-rule+
        +agent-controlled-branch-shape-rule+
        +agent-comment-quality-rule+
        +agent-predicate-family-combinator-rule+
        +agent-dependency-protocol-adapter-rule+
        +agent-explicit-precise-import-rule+
        +agent-package-build-responsibility-rule+
        +agent-build-runtime-quality-rule+
        +agent-policy-source-scope-rule+
        +agent-alist-access-rule+
        +agent-anonymous-pair-access-rule+
        +agent-package-build-canonical-shape-rule+
        +agent-poo-prototype-fixed-point-rule+
        +agent-poo-construction-performance-rule+
        +agent-poo-clone-override-loop-performance-rule+
        +agent-poo-materialization-loop-performance-rule+
        +agent-poo-composition-loop-performance-rule+
        +agent-poo-validation-loop-performance-rule+
        +agent-poo-lens-loop-performance-rule+
        +agent-poo-object-construction-loop-performance-rule+
        +agent-poo-type-construction-loop-performance-rule+
        +agent-poo-debug-instrumentation-loop-performance-rule+
        +agent-poo-slot-spec-mutation-loop-performance-rule+
        +agent-poo-slot-predicate-loop-performance-rule+
        repairable-finding?
        repairable-findings
        agent-repair-report-json
        agent-repair-summary-parts
        finding-agent-repair-json
        finding-agent-repair-parts
        finding-guide-detail-parts
        run-policy-checks
        run-modularity-policy
        +max-source-line-count+
        +max-test-line-count+
        +min-source-definition-count+
        +min-test-definition-count+
        facade-source-file?
        facade-implementation-finding
        sibling-file-dir-owner-collision-finding
        repeated-owner-entry-finding
        bin-entrypoint-implementation-finding
        source-leaf-bloat-finding
        test-leaf-bloat-finding
        run-agent-policy
        facade-intent-finding
        generic-owner-segment
        generic-owner-finding
        vague-definition-finding
        top-level-executable-finding
        functional-idiom-advice-finding
        poo-direct-writeenv-finding
        poo-io-runtime-witness-finding
        poo-object-model-finding
        poo-method-shape-finding
        poo-prototype-fixed-point-finding
        poo-construction-performance-finding
        poo-clone-override-loop-performance-finding
        poo-materialization-loop-performance-finding
        poo-composition-loop-performance-finding
        poo-validation-loop-performance-finding
        poo-lens-loop-performance-finding
        poo-object-construction-loop-performance-finding
        poo-type-construction-loop-performance-finding
        poo-debug-instrumentation-loop-performance-finding
        poo-slot-spec-mutation-loop-performance-finding
        poo-slot-predicate-loop-performance-finding
        macro-runtime-source-witness-finding
        protocol-evidence-finding
        typed-combinator-style-finding
        controlled-branch-shape-finding
        predicate-family-combinator-finding
        dependency-protocol-adapter-finding
        explicit-precise-import-finding
        package-build-responsibility-finding
        package-build-canonical-shape-finding
        build-runtime-quality-finding
        policy-source-scope-finding
        alist-access-finding
        anonymous-pair-access-finding
        facade-export-conflict-findings)
