;;; -*- Gerbil -*-
;;; Shell command and delegate process helpers for downstream testing builds.

(import :gerbil/gambit
        (only-in :std/misc/path path-directory)
        (only-in :std/misc/process run-process)
        (only-in :std/misc/string string-join)
        (only-in :std/sugar filter)
        :testing/model
        :testing/framework
        :testing/build-paths)

(export #t)

;; : (-> Char Boolean)
(def (testing-build-shell-quote-safe-char? char)
  (or (char-alphabetic? char)
      (char-numeric? char)
      (memq char '(#\/ #\. #\_ #\- #\= #\: #\+ #\,))))

;; : (-> String Boolean)
(def (testing-build-shell-token-plain? value)
  (and (string? value)
       (> (string-length value) 0)
       (testing-andmap testing-build-shell-quote-safe-char?
                       (string->list value))))

;; : (-> Port Char Unit)
(def (testing-build-display-shell-char port char)
  (if (char=? char #\')
    (display "'\\''" port)
    (display char port)))

;; : (-> String String)
(def (testing-build-shell-quote value)
  (if (testing-build-shell-token-plain? value)
    value
    (string-append
     "'"
     (call-with-output-string ""
       (lambda (port)
         (for-each
          (lambda (char)
            (testing-build-display-shell-char port char))
          (string->list value))))
     "'")))

;; : (-> [String] String)
(def (testing-build-shell-command command)
  (string-join (map testing-build-shell-quote command) " "))

;; : (-> Integer Integer)
(def (testing-build-exit-code status)
  (cond
   ((< status 0) 1)
   ((> status 255) (quotient status 256))
   (else status)))

;; : (-> [String] Integer)
(def (testing-build-run-process/status command)
  (let (status 0)
    (run-process command
                 stdin-redirection: #f
                 stdout-redirection: #f
                 stderr-redirection: #f
                 check-status:
                 (lambda (exit-status _settings)
                   (set! status exit-status)))
    (testing-build-exit-code status)))

;; : (-> TestingBuild MaybeString)
(def (testing-build-loadpath-env build)
  (let (loadpath (testing-object-ref build 'loadpath #f))
    (and loadpath
         (string-append "GERBIL_LOADPATH=" loadpath))))

;; : (-> TestingBuild [String])
(def (testing-build-process-env build)
  (filter values
          [(testing-build-loadpath-env build)]))

;; : (-> TestingBuild Boolean)
(def (testing-build-policy-enabled? build)
  (testing-object-ref build 'policy #f))

;; : (-> TestingBuild Path)
(def (testing-build-generated-policy-directory build)
  (testing-build-path
   build
   (path-expand "testing" (path-expand "gslph" ".gerbil"))))

;; : (-> TestingBuild Path)
(def (testing-build-generated-policy-file build)
  (path-expand
   (string-append (testing-object-ref build 'name "testing-build")
                  "-policy-test.ss")
   (testing-build-generated-policy-directory build)))

;; : (-> Port Datum Unit)
(def (testing-build-write-quoted port value)
  (display "'" port)
  (write value port))

;; : (-> TestingBuild [String] Path)
(def (testing-build-write-policy-delegate! build files)
  (let* ((directory (testing-build-generated-policy-directory build))
         (file (testing-build-generated-policy-file build))
         (root (testing-build-contract-root build)))
    (run-process ["mkdir" "-p" directory]
                 stdin-redirection: #f
                 stdout-redirection: #f
                 stderr-redirection: #f)
    (call-with-output-file file
      (lambda (port)
        (display ";;; -*- Gerbil -*-\n" port)
        (display ";;; Generated by asp gerbil-scheme testing-build; do not edit.\n\n" port)
        (display "(import (only-in :gslph/src/policy/gxtest make-policy-test))\n\n" port)
        (display "(export gslph-testing-policy-test)\n\n" port)
        (display "(def gslph-testing-policy-test\n  (make-policy-test " port)
        (write root port)
        (display " " port)
        (testing-build-write-quoted port files)
        (display "))\n" port)))
    file))

;; : (-> TestingBuild [String] Boolean MaybePath)
(def (testing-build-policy-delegate-file build files include-policy-file?)
  (and include-policy-file?
       (testing-build-policy-enabled? build)
       (testing-build-write-policy-delegate! build files)))

;; : (-> TestingBuild [String] Boolean [String])
(def (testing-build-gxtest-command build files (include-policy-file? #t))
  (let (policy-file (testing-build-policy-delegate-file
                     build
                     files
                     include-policy-file?))
    (append ["env"]
            (testing-build-process-env build)
            ["gxtest"]
            files
            (if policy-file
              [policy-file]
              []))))

;; : (-> TestingBuild Path)
(def (testing-build-gxtest-log-file build)
  (path-expand
   (string-append (testing-object-ref build 'name "testing-build")
                  "-gxtest.log")
   (testing-build-generated-policy-directory build)))

;; : (-> TestingBuild [String] String)
(def (testing-build-gxtest-shell build command)
  (let (log-file (testing-build-gxtest-log-file build))
    (run-process ["mkdir" "-p" (path-directory log-file)]
                 stdin-redirection: #f
                 stdout-redirection: #f
                 stderr-redirection: #f)
    (string-append
     "set -o pipefail; "
     (testing-build-shell-command command)
     " 2>&1 | tee "
     (testing-build-shell-quote log-file))))

;; : (-> String Boolean)
(def (testing-build-gxtest-failure-line? line)
  (and (string? line)
       (testing-string-prefix? "*** FAILED" line)))

;; : (-> Port Boolean)
(def (testing-build-gxtest-port-failed? port)
  (let loop ()
    (let (line (read-line port))
      (cond
       ((eof-object? line) #f)
       ((testing-build-gxtest-failure-line? line) #t)
       (else (loop))))))

;; : (-> Path Boolean)
(def (testing-build-gxtest-output-failed? log-file)
  (and (file-exists? log-file)
       (call-with-input-file log-file
         testing-build-gxtest-port-failed?)))

;; : (-> TestingBuild [String] Integer)
(def (testing-build-run-gxtest-command build command)
  (let ((status (testing-build-run-process/status
                 ["bash" "-c" (testing-build-gxtest-shell build command)]))
        (log-file (testing-build-gxtest-log-file build)))
    (if (and (= status 0)
             (testing-build-gxtest-output-failed? log-file))
      1
      status)))
