;;; -*- Gerbil -*-
;;; Boundary:
;;; - test owner records policy expectations.
;;; - Keep typed contracts and fixture intent explicit.
(import :std/test
        :commands/guide
        :commands/info
        :commands/search
        :support/args
        :std/misc/ports
        (only-in :std/text/json read-json)
        :unit/poo/runtime-witness
        :unit/search/structural-index)
(export search-test-part-12)
;; : (-> Table Key Json )
(def (json-get table key)
  (hash-get table key))
;; : (-> (List XX) SearchOutput )
(def (search-output args)
  (let* ((status #f)
         (output
          (call-with-output-string
            (lambda (out)
              (parameterize ((current-output-port out))
                (set! status (search-main args)))))))
    (check status => 0)
    output))
;; : (-> (List String) String )
(def (guide-output args)
  (let* ((status #f)
         (output
          (call-with-output-string
            (lambda (out)
              (parameterize ((current-output-port out))
                (set! status (guide-main args)))))))
    (check status => 0)
    output))
;; : (-> (List XX) InfoOutput )
(def (info-output args)
  (let* ((status #f)
         (output
          (call-with-output-string
            (lambda (out)
              (parameterize ((current-output-port out))
                (set! status (info-main args)))))))
    (check status => 0)
    output))
;; : (-> OutputPort Fragment Boolean )
(def (contains? output fragment)
  (and (string-contains output fragment) #t))
;; : (-> OutputPort Boolean )
(def (guide-code-render-metadata-free? output)
  (not (or (contains? output "[guide")
           (contains? output "|primaryExemplar")
           (contains? output "|exemplar")
           (contains? output "|code begin")
           (contains? output "selector=")
           (contains? output "nextCommand=")
           (contains? output "\n|"))))
;; : (-> OutputPort Fragments Boolean )
(def (check-output-contains output fragments)
  (for-each
   (lambda (fragment)
     (check (contains? output fragment) => #t))
   fragments))
;; SearchTest
;; TestSuite
(def search-test-part-12
  (test-suite "gerbil scheme harness search part 12"
    (test-case "runtime-source json uses schema-backed acquisition packet"
          (let* ((output (search-output ["runtime-source" "macro" "--json" "."]))
                 (packet (call-with-input-string output read-json))
                 (runtime (json-get packet "runtime"))
                 (source-ref (json-get packet "sourceRef"))
                 (acquisition (json-get packet "acquisition"))
                 (fact (car (json-get packet "facts")))
                 (details (json-get fact "details"))
                 (packet-resolver (json-get packet "selectorResolver"))
                 (packet-examples (json-get packet "sourceExamples"))
                 (packet-comments (json-get packet "sourceComments"))
                 (resolver (json-get details "selectorResolver"))
                 (examples (json-get details "sourceExamples"))
                 (comments (json-get details "sourceComments")))
            (check (json-get packet "schemaId")
                   => "agent.semantic-protocols.semantic-runtime-source-acquisition")
            (check (json-get packet "namespace") => "runtime-source")
            (check (json-get packet "authority") => "runtime-version-source")
            (check (json-get packet "quality") => "version-matched-source-plan")
            (check (json-get source-ref "kind") => "runtime-version-source")
            (check (json-get source-ref "repository")
                   => "https://git.cons.io/mighty-gerbils/gerbil")
            (check (json-get source-ref "checkoutPolicy")
                   => "exact-tag-from-active-runtime")
            (check (json-get source-ref "statePathPolicy")
                   => "asp-state-managed")
            (check (json-get acquisition "owner") => "asp")
            (check (json-get acquisition "operation")
                   => "clone-or-fetch-checkout-index")
            (check (json-get acquisition "stateNamespace")
                   => "runtime-source/gerbil-scheme")
            (check (json-get acquisition "indexOwner") => "asp-structural-index")
            (check (json-get packet-resolver "scheme") => "gerbil-runtime-source")
            (check (json-get (car packet-examples) "id") => "std-sugar-defrule")
            (check (json-get (car packet-comments) "fallback") => "comment-missing-is-signal")
            (check (json-get resolver "scheme") => "gerbil-runtime-source")
            (check (json-get resolver "output") => "code-with-comments")
            (check (json-get (car examples) "id") => "std-sugar-defrule")
            (check (json-get (car comments) "fallback") => "comment-missing-is-signal")
            (check (json-get packet "next")
                   => "search runtime-source macro sugar module-sugar")
            (check (string-prefix? "Gerbil v" (json-get runtime "systemVersion")) => #t)
            (check (not (contains? output ".data")) => #t)))
    (test-case "runtime-source json exposes writeenv printer hook selectors"
          (let* ((output (search-output ["runtime-source" "writeenv" "printer" "hook" "--json" "."]))
                 (packet (call-with-input-string output read-json))
                 (facts (json-get packet "facts"))
                 (fact (car facts))
                 (selectors (json-get fact "selectors"))
                 (writeenv-selector (car selectors))
                 (write-object-selector (list-ref selectors 2))
                 (failures (json-get packet "failureCases"))
                 (roundtrip-failure (list-ref failures 1)))
            (check (json-get packet "schemaId")
                   => "agent.semantic-protocols.semantic-runtime-source-acquisition")
            (check (json-get packet "namespace") => "runtime-source")
            (check (json-get packet "quality") => "version-matched-source-plan")
            (check (json-get packet "missing") => [])
            (check (json-get packet "witness")
                   => "active-runtime-version-to-writeenv-source-acquisition-plan")
            (check (json-get packet "next")
                   => "search runtime-source writeenv printer hook")
            (check (json-get fact "id") => "gerbil-runtime-writeenv-source")
            (check (json-get writeenv-selector "role") => "writeenv-builtin")
            (check (json-get writeenv-selector "selector")
                   => "gerbil-runtime-source://src/bootstrap/gerbil/builtin.ssxi.ss#writeenv")
            (check (json-get write-object-selector "role") => "runtime-write-object-owner")
            (check (json-get write-object-selector "selector")
                   => "gerbil-runtime-source://src/bootstrap/gerbil/core/runtime.ssi#write-object")
            (check (json-get roundtrip-failure "id")
                   => "poo-writeenv-roundtrip-assumption")
            (check (not (contains? output ".data")) => #t)))))
