;;; -*- Gerbil -*-
;;; Boundary:
;;; - test owner records policy expectations.
;;; - Keep typed contracts and fixture intent explicit.
(import :std/test
        :commands/guide
        :commands/info
        :commands/search
        :support/args
        :std/misc/ports
        (only-in :std/text/json read-json)
        :unit/poo/runtime-witness
        :unit/search/structural-index)
(export search-test-part-18)
;; : (-> Table Key Json )
(def (json-get table key)
  (hash-get table key))
;; : (-> (List XX) SearchOutput )
(def (search-output args)
  (let* ((status #f)
         (output
          (call-with-output-string
            (lambda (out)
              (parameterize ((current-output-port out))
                (set! status (search-main args)))))))
    (check status => 0)
    output))
;; : (-> (List String) String )
(def (guide-output args)
  (let* ((status #f)
         (output
          (call-with-output-string
            (lambda (out)
              (parameterize ((current-output-port out))
                (set! status (guide-main args)))))))
    (check status => 0)
    output))
;; : (-> (List XX) InfoOutput )
(def (info-output args)
  (let* ((status #f)
         (output
          (call-with-output-string
            (lambda (out)
              (parameterize ((current-output-port out))
                (set! status (info-main args)))))))
    (check status => 0)
    output))
;; : (-> OutputPort Fragment Boolean )
(def (contains? output fragment)
  (and (string-contains output fragment) #t))
;; : (-> OutputPort Boolean )
(def (guide-code-render-metadata-free? output)
  (not (or (contains? output "[guide")
           (contains? output "|primaryExemplar")
           (contains? output "|exemplar")
           (contains? output "|code begin")
           (contains? output "selector=")
           (contains? output "nextCommand=")
           (contains? output "\n|"))))
;; : (-> OutputPort Fragments Boolean )
(def (check-output-contains output fragments)
  (for-each
   (lambda (fragment)
     (check (contains? output fragment) => #t))
   fragments))
;; SearchTest
;; TestSuite
(def search-test-part-18
  (test-suite "gerbil scheme harness search part 18"
    (test-case "std json machine packet exposes minimal Gerbil import mapping"
          (let* ((output (search-output ["std" "json" "--json" "."]))
                 (packet (call-with-input-string output read-json))
                 (facts (json-get packet "facts"))
                 (fact (car facts))
                 (details (json-get fact "details")))
            (check (json-get packet "namespace") => "std")
            (check (json-get packet "evidenceGrade") => "fact")
            (check (json-get fact "id") => "std/text/json")
            (check (json-get details "module") => ":std/text/json")
            (check (json-get details "capabilities") => ["read-json"])
            (check (json-get details "minimalImport")
                   => "(import (only-in :std/text/json read-json))")))
    (test-case "pattern json uses schema-backed extension mapping packet"
          (let* ((output (search-output ["pattern" "poo" "class" "--json" "."]))
                 (packet (call-with-input-string output read-json))
                 (mapping (json-get packet "patternMapping"))
                 (source-ref (json-get mapping "sourceRef"))
                 (selector-resolver (json-get mapping "selectorResolver"))
                 (source-lookup (json-get mapping "sourceLookup"))
                 (agent-read-order (json-get mapping "agentReadOrder"))
                 (agent-action (json-get mapping "agentAction"))
                 (forms (json-get mapping "minimalForms"))
                 (first-form (car forms))
                 (template (json-get first-form "template"))
                 (selectors (json-get mapping "selectors"))
                 (mro-selector (list-ref selectors 5))
                 (mro-form (list-ref forms 4))
                 (failures (json-get mapping "failureCases"))
                 (first-failure (car failures))
                 (mro-failure (list-ref failures 3)))
            (check (json-get packet "schemaId")
                   => "agent.semantic-protocols.semantic-extension-pattern-mapping")
            (check (json-get packet "namespace") => "pattern")
            (check (json-get packet "quality") => "verified")
            (check (json-get mapping "id") => "poo-object-system")
            (check (json-get mapping "extension") => "poo")
            (check (json-get mapping "origin") => "direct")
            (check (hash-key? mapping "sourceWorkspace") => #f)
            (check (json-get source-ref "kind") => "package-manager-source")
            (check (json-get source-ref "manager") => "gxpkg")
            (check (json-get source-ref "dependency")
                   => "git.cons.io/mighty-gerbils/gerbil-poo")
            (check (json-get source-ref "pathPolicy") => "runtime-resolved")
            (check (json-get (json-get source-ref "localSource") "rootHint")
                   => "~/.gerbil")
            (check (json-get (json-get source-ref "localSource") "status")
                   => "probe-first")
            (check (json-get (json-get source-ref "localSource") "missingAction")
                   => "install-package-before-repository-fallback")
            (check (json-get (json-get source-ref "localSource") "installHint")
                   => "gxpkg install git.cons.io/mighty-gerbils/gerbil-poo")
            (check (json-get (json-get source-ref "repositorySource") "url")
                   => "https://git.cons.io/mighty-gerbils/gerbil-poo")
            (check (json-get (json-get source-ref "indexHint") "backend")
                   => "rust-sql")
            (check (json-get (json-get source-ref "indexHint") "missingLocalAction")
                   => "install-package-before-repository-fallback")
            (check (json-get (json-get source-ref "indexHint") "fallbackPolicy")
                   => "repository-source-after-install-check")
            (check (json-get selector-resolver "scheme")
                   => "gerbil-poo-logical-symbol")
            (check (json-get selector-resolver "querySelector") => "not-direct")
            (check (json-get source-lookup "order") => "local-source-before-git")
            (check (json-get source-lookup "missingLocalAction")
                   => "install-package-before-repository-fallback")
            (check (json-get source-lookup "fallbackPolicy")
                   => "repository-source-after-install-check")
            (check (json-get (json-get source-lookup "localSource") "rootHint")
                   => "~/.gerbil")
            (check (json-get (json-get source-lookup "localSource") "installHint")
                   => "gxpkg install git.cons.io/mighty-gerbils/gerbil-poo")
            (check (json-get (json-get source-lookup "repositorySource") "status")
                   => "fallback")
            (check (json-get agent-read-order "first") => "agentScenario")
            (check (json-get agent-read-order "third") => "selectorResolver")
            (check (json-get agent-action "action")
                   => "use-minimalForms-before-editing")
            (check (json-get agent-action "missingLocalAction")
                   => "install-package-before-repository-fallback")
            (check (json-get agent-action "fallback")
                   => "repository-source-after-install-check")
            (check (json-get agent-action "quality") => "verified")
            (check (json-get first-form "role") => "class-definition")
            (check (json-get first-form "selector")
                   => "gerbil-poo://object.ss#defclass")
            (check (json-get mro-selector "role") => "method-resolution-order")
            (check (json-get mro-selector "selector")
                   => "gerbil-runtime://c3.ss#class-precedence-list")
            (check (json-get mro-form "role") => "mro-regression-test")
            (check (json-get mro-form "selector")
                   => "gerbil-runtime-test://src/gerbil/test/c3-test.ss#class-inheritance")
            (check (json-get template "head") => "defclass")
            (check (json-get template "operands")
                   => ["(<Class> <Base>)" "(<slot> ...)"])
            (check (json-get template "keywords") => ["transparent: #t"])
            (check (json-get first-failure "riskKind") => "dialect-confusion")
            (check (json-get first-failure "badPattern")
                   => "racket-class-or-generic-scheme-object")
            (check (json-get first-failure "selectors")
                   => ["gerbil-poo://object.ss#defclass"
                       "gerbil-poo://mop.ss#.defgeneric"
                       "gerbil-poo://mop.ss#defmethod"])
            (check (json-get mro-failure "riskKind") => "semantic-regression-gap")
            (check (json-get mro-failure "correctiveAction")
                   => "add-c3-linearization-and-slot-vector-witnesses")))))
