;;; -*- Gerbil -*-
;;; Gerbil-poo package extension facts activated by declared gxpkg dependencies.

(import :extensions/model
        :package-manager/facade
        :parser/facade
        :std/sugar
        :support/list)

(export poo-extension-active?
        poo-extension-fact
        poo-extension-capability-names
        poo-extension-search-lines
        poo-extension-json
        poo-source-ref
        poo-pattern-evidence
        poo-pattern-query?
        poo-pattern-focus
        poo-pattern-kind
        poo-pattern-selectors
        poo-pattern-minimal-forms
        poo-pattern-failure-cases)
;; ConfigConstant
(def +poo-extension-name+ "poo")
;; ConfigConstant
(def +poo-extension-activation+ "gerbil.pkg")
;; Integer
(def +poo-dependency-mode+ "required")
;; ConfigConstant
(def +poo-package-tokens+
  '("poo" "clan/poo" "gerbil-poo" "git.cons.io/mighty-gerbils/gerbil-poo"))
;; Boolean <- ProjectIndex
(def (poo-extension-active? index)
  (project-package-depends-on? (project-index-package index)
                               poo-package-token?))
;; Boolean <- String
(def (poo-package-token? token)
  (and token
       (or (member token +poo-package-tokens+)
           (string-suffix? "/gerbil-poo" token))))
;; (List String)
(def (poo-extension-capability-names)
  '("object-system"
    "metaobject-protocol"
    "protocols"
    "policy-protocol"
    "macro-governance"
    "user-override-witness"))
;; Fact <- ProjectIndex
(def (poo-extension-fact index)
  (and (poo-extension-active? index)
       (let (package (project-index-package index))
         (make-extension-fact +poo-extension-name+
                              +poo-extension-activation+
                              +poo-dependency-mode+
                              (project-package-manager package)
                              (project-package-name package)
                              (project-package-dependencies package)
                              (poo-extension-capability-names)))))
;; (List String) <- ProjectIndex
(def (poo-extension-search-lines index)
  (let (fact (poo-extension-fact index))
    (if fact
      [(extension-fact-search-line fact)]
      '())))
;; Json <- ProjectIndex
(def (poo-extension-json index)
  (let (fact (poo-extension-fact index))
    (and fact (extension-fact-json fact))))
;; PooSourceRef <- ProjectIndex
(def (poo-source-ref index)
  (hash (kind "package-manager-download")
        (manager "gxpkg")
        (package +poo-extension-name+)
        (dependency (poo-extension-dependency index))
        (repository "git.cons.io/mighty-gerbils/gerbil-poo")
        (pathPolicy "runtime-resolved")
        (selectorScheme "gerbil-poo-logical-symbol")))
;;; Boundary:
;;; - poo-extension-dependency composes first-class procedures.
;;; - Keep data-flow evidence visible.
;; Integer <- ProjectIndex
(def (poo-extension-dependency index)
  (let* ((package (project-index-package index))
         (matches (if package
                    (filter poo-package-token?
                            (project-package-dependencies package))
                    '())))
    (if (pair? matches)
      (car matches)
      "git.cons.io/mighty-gerbils/gerbil-poo")))
;; String <- ProjectIndex (List PooFormFact)
(def (poo-pattern-evidence index terms)
  (and (poo-pattern-query? terms)
       (poo-extension-fact index)
       (let (kind (poo-pattern-kind terms))
         (hash (id (poo-pattern-id kind))
               (extension +poo-extension-name+)
               (focus (poo-pattern-focus kind terms))
               (sourceRef (poo-source-ref index))
               (sourceOwners (poo-pattern-source-owners kind))
               (selectors (poo-pattern-selectors kind))
               (agentScenario (poo-pattern-agent-scenario kind))
               (intent (poo-pattern-intent kind))
               (minimalForms (poo-pattern-minimal-forms kind))
               (failureCases (poo-pattern-failure-cases kind))
               (qualitySignals (poo-pattern-quality-signals kind))
               (witness (poo-pattern-witness kind))
               (missing (poo-pattern-missing kind))
               (next (poo-pattern-next kind))))))
;; Boolean <- (List PooFormFact)
(def (poo-pattern-query? terms)
  (and (pair? terms)
       (or (equal? (car terms) +poo-extension-name+)
           (member +poo-extension-name+ terms))))
;; String <- (List PooFormFact)
(def (poo-pattern-kind terms)
  (cond
   ((poo-pattern-term-any? terms ["trace" "debug" "trace-poo"
                                  "trace-inherited-slot" "traced-function"])
    'trace-debug)
   ((poo-pattern-term-any? terms ["json" "print" "sexp" "io" "write-json"
                                  "serialization" "fallback"])
    'io-json-fallback)
   ((poo-pattern-term-any? terms ["lens" "slot-lens"])
    'lens)
   ((poo-pattern-term-any? terms ["sealed" "validate" "validation"
                                  "element?" "type-validation"])
    'type-validation)
   ((poo-pattern-term-any? terms ["c3" "mro" "linearization"
                                  "precedence" "slot-order"])
    'c3-mro)
   ((poo-pattern-term-any? terms ["cache" "cached" ".ref" ".ref/cached"
                                  "computed" "apply-slot-spec" "superfun"])
    'slot-cache)
   ((poo-pattern-term-any? terms ["proto" "prototype" "compose-proto"
                                  "compose-proto*" "instantiate-proto"])
    'prototype-composition)
   (else 'object-system)))
;;; Boundary:
;;; - poo-pattern-term-any? composes first-class procedures.
;;; - Keep data-flow evidence visible.
;; Boolean <- (List PooFormFact) Needles
(def (poo-pattern-term-any? terms needles)
  (and (pair? terms)
       (ormap (lambda (needle) (member needle terms)) needles)))
;; PooPatternFocus <- String (List PooFormFact)
(def (poo-pattern-focus kind terms)
  (if (and (pair? terms) (pair? (cdr terms)))
    (join (cdr terms) " ")
    (poo-pattern-default-focus kind)))
;; String <- String
(def (poo-pattern-id kind)
  (case kind
    ((prototype-composition) "poo-prototype-composition")
    ((trace-debug) "poo-trace-debug")
    ((slot-cache) "poo-slot-cache-computed")
    ((io-json-fallback) "poo-io-json-fallback")
    ((lens) "poo-lens-slot")
    ((type-validation) "poo-type-validation-sealed")
    ((c3-mro) "poo-c3-mro-regression")
    (else "poo-object-system")))
;; PooPatternDefaultFocus <- String
(def (poo-pattern-default-focus kind)
  (case kind
    ((prototype-composition) "prototype composition")
    ((trace-debug) "trace debug computed slot")
    ((slot-cache) "slot cache computed slot")
    ((io-json-fallback) "io json print fallback")
    ((lens) "lens slot-lens")
    ((type-validation) "sealed type validation")
    ((c3-mro) "c3 mro slot order")
    (else "object-system")))
;; (List String) <- String
(def (poo-pattern-source-owners kind)
  (case kind
    ((prototype-composition) ["proto.ss"])
    ((trace-debug) ["debug.ss" "object.ss"])
    ((slot-cache) ["object.ss" "mop.ss"])
    ((io-json-fallback) ["io.ss" "mop.ss" "object.ss"])
    ((lens) ["mop.ss" "t/mop-test.ss"])
    ((type-validation) ["mop.ss" "t/mop-test.ss"])
    ((c3-mro) ["object.ss" ":gerbil/runtime/c3" "src/gerbil/test/c3-test.ss"])
    (else ["object.ss"
           "mop.ss"
           "proto.ss"
           ":gerbil/runtime/c3"
           "src/gerbil/test/c3-test.ss"])))
;; PooPatternAgentScenario <- String
(def (poo-pattern-agent-scenario kind)
  (case kind
    ((prototype-composition) "agent-composes-poo-prototypes-without-knowing-proto-order")
    ((trace-debug) "agent-traces-poo-methods-without-preserving-computed-slot-superfun")
    ((slot-cache) "agent-adds-computed-poo-slot-without-cache-or-superfun-semantics")
    ((io-json-fallback) "agent-customizes-poo-serialization-without-json-or-print-fallbacks")
    ((lens) "agent-updates-poo-slots-without-lens-composition-semantics")
    ((type-validation) "agent-defines-poo-class-without-sealed-type-validation")
    ((c3-mro) "agent-writes-poo-inheritance-without-knowing-c3-linearization")
    (else "agent-does-not-know-gerbil-poo-object-system")))
;; PooPatternIntent <- String
(def (poo-pattern-intent kind)
  (case kind
    ((prototype-composition) "query-proto-composition-source-before-composing-object-prototypes")
    ((trace-debug) "query-trace-poo-and-computed-slot-wrapper-before-adding-debug-tracing")
    ((slot-cache) "query-slot-cache-and-apply-slot-spec-before-adding-computed-slots")
    ((io-json-fallback) "query-poo-io-fallbacks-before-overriding-json-or-print-behavior")
    ((lens) "query-slot-lens-and-lens-compose-before-writing-functional-slot-updates")
    ((type-validation) "query-sealed-class-and-validate-witness-before-writing-type-checked-poo-classes")
    ((c3-mro) "force-agent-to-query-poo-and-runtime-c3-witnesses-before-editing-inheritance")
    (else "write-gerbil-poo-object-system-without-racket-or-generic-scheme-guessing")))
;;; Boundary:
;;; - poo-pattern-selectors coordinates multiple evidence fields.
;;; - Keep packet shape and invariants stable.
;; Selector
(def (poo-pattern-selectors (kind 'object-system))
  (case kind
    ((prototype-composition)
     [(hash (role "prototype-instantiation")
            (symbol "instantiate-proto")
            (selector "gerbil-poo://proto.ss#instantiate-proto"))
      (hash (role "prototype-composition")
            (symbol "compose-proto")
            (selector "gerbil-poo://proto.ss#compose-proto"))
      (hash (role "prototype-composition-list")
            (symbol "compose-proto*")
            (selector "gerbil-poo://proto.ss#compose-proto*"))])
    ((trace-debug)
     [(hash (role "trace-function-wrapper")
            (symbol "traced-function")
            (selector "gerbil-poo://debug.ss#traced-function"))
      (hash (role "trace-inherited-slot")
            (symbol "trace-inherited-slot")
            (selector "gerbil-poo://debug.ss#trace-inherited-slot"))
      (hash (role "trace-poo-wrapper")
            (symbol "trace-poo")
            (selector "gerbil-poo://debug.ss#trace-poo"))
      (hash (role "computed-slot-wrapper")
            (symbol "$computed-slot-spec")
            (selector "gerbil-poo://debug.ss#trace-inherited-slot"))])
    ((slot-cache)
     [(hash (role "slot-spec-application")
            (symbol "apply-slot-spec")
            (selector "gerbil-poo://object.ss#apply-slot-spec"))
      (hash (role "slot-cache-read")
            (symbol ".ref")
            (selector "gerbil-poo://object.ss#.ref"))
      (hash (role "slot-cache-read-existing")
            (symbol ".ref/cached")
            (selector "gerbil-poo://object.ss#.ref/cached"))
      (hash (role "slot-lens")
            (symbol "slot-lens")
            (selector "gerbil-poo://mop.ss#slot-lens"))
      (hash (role "real-project-slot-cache-test")
            (symbol "putslot-test")
            (selector "gerbil-poo-test://t/object-test.ss#testing-putslot"))])
    ((io-json-fallback)
     [(hash (role "print-fallback")
            (symbol "@method :pr")
            (selector "gerbil-poo://io.ss#@method:pr"))
      (hash (role "writeenv-fallback")
            (symbol "@method :wr")
            (selector "gerbil-poo://io.ss#@method:wr-object"))
      (hash (role "json-fallback")
            (symbol "@method :json")
            (selector "gerbil-poo://io.ss#@method:json"))
      (hash (role "json-writer")
            (symbol "@method :write-json")
            (selector "gerbil-poo://io.ss#@method:write-json"))
      (hash (role "typed-value-writer")
            (symbol "TV")
            (selector "gerbil-poo://io.ss#@method:wr-TV"))
      (hash (role "writeenv-runtime-boundary")
            (symbol "writeenv")
            (selector "gerbil-runtime://builtin#writeenv"))
      (hash (role "writeenv-method-dispatch-witness")
            (symbol "method-ref")
            (selector "gerbil-poo-witness://t/unit/poo/runtime-witness.ss#writeenv-method-dispatch"))
      (hash (role "object-value-mapping")
            (symbol "map-object-values")
            (selector "gerbil-poo://mop.ss#map-object-values"))])
    ((lens)
     [(hash (role "lens-class")
            (symbol "Lens")
            (selector "gerbil-poo://mop.ss#Lens"))
      (hash (role "lens-slot")
            (symbol "slot-lens")
            (selector "gerbil-poo://mop.ss#slot-lens"))
      (hash (role "lens-compose")
            (symbol ".compose")
            (selector "gerbil-poo://mop.ss#Lens.compose"))
      (hash (role "real-project-lens-test")
            (symbol "Lenses")
            (selector "gerbil-poo-test://t/mop-test.ss#Lenses"))])
    ((type-validation)
     [(hash (role "class-descriptor")
            (symbol "Class.")
            (selector "gerbil-poo://mop.ss#Class."))
      (hash (role "function-validator")
            (symbol "Function.")
            (selector "gerbil-poo://mop.ss#Function."))
      (hash (role "generic-slot-validator")
            (symbol "slot-checker")
            (selector "gerbil-poo://mop.ss#slot-checker"))
      (hash (role "real-project-validation-test")
            (symbol "mop-test")
            (selector "gerbil-poo-test://t/mop-test.ss#sealed-type-validation"))])
    (else
     [(hash (role "class-definition")
            (symbol "defclass")
            (selector "gerbil-poo://object.ss#defclass"))
      (hash (role "generic-definition")
            (symbol ".defgeneric")
            (selector "gerbil-poo://mop.ss#.defgeneric"))
      (hash (role "method-dispatch")
            (symbol "defmethod")
            (selector "gerbil-poo://mop.ss#defmethod"))
      (hash (role "protocol-composition")
            (symbol "proto")
            (selector "gerbil-poo://mop.ss#proto"))
      (hash (role "prototype-composition")
            (symbol "compose-proto")
            (selector "gerbil-poo://proto.ss#compose-proto"))
      (hash (role "method-resolution-order")
            (symbol "class-precedence-list")
            (selector "gerbil-runtime://c3.ss#class-precedence-list"))
      (hash (role "real-project-semantic-test")
            (symbol "c3-test")
            (selector "gerbil-runtime-test://src/gerbil/test/c3-test.ss#c3-test"))])))
;;; Boundary:
;;; - poo-pattern-minimal-forms coordinates multiple evidence fields.
;;; - Keep packet shape and invariants stable.
;; Integer
(def (poo-pattern-minimal-forms (kind 'object-system))
  (case kind
    ((prototype-composition)
     [(hash (role "prototype-instantiation")
            (symbol "instantiate-proto")
            (template (hash (head "instantiate-proto")
                            (operands ["<proto>" "<base-object>"])
                            (keywords [])))
            (selector "gerbil-poo://proto.ss#instantiate-proto"))
      (hash (role "prototype-composition")
            (symbol "compose-proto")
            (template (hash (head "compose-proto")
                            (operands ["<proto-a>" "<proto-b>"])
                            (keywords [])))
            (selector "gerbil-poo://proto.ss#compose-proto"))
      (hash (role "prototype-composition-list")
            (symbol "compose-proto*")
            (template (hash (head "compose-proto*")
                            (operands ["[<proto-a> <proto-b> ...]"])
                            (keywords [])))
            (selector "gerbil-poo://proto.ss#compose-proto*"))])
    ((trace-debug)
     [(hash (role "trace-function-wrapper")
            (symbol "traced-function")
            (template (hash (head "traced-function")
                            (operands ["`(.@ ,name ,slot-name)" "<procedure>"])
                            (keywords [])))
            (selector "gerbil-poo://debug.ss#traced-function"))
      (hash (role "trace-inherited-slot")
            (symbol "trace-inherited-slot")
            (template (hash (head "trace-inherited-slot")
                            (operands ["<poo-name>" "'<slot-symbol>"])
                            (keywords [])))
            (selector "gerbil-poo://debug.ss#trace-inherited-slot"))
      (hash (role "computed-slot-trace")
            (symbol "$computed-slot-spec")
            (template (hash (head "$computed-slot-spec")
                            (operands ["(lambda (self superfun) ...)"])
                            (keywords ["call-superfun-before-wrapping"])))
            (selector "gerbil-poo://debug.ss#trace-inherited-slot"))
      (hash (role "trace-poo-wrapper")
            (symbol "trace-poo")
            (template (hash (head "trace-poo")
                            (operands ["<poo>" "<name>"])
                            (keywords [])))
            (selector "gerbil-poo://debug.ss#trace-poo"))])
    ((slot-cache)
     [(hash (role "computed-slot")
            (symbol "computed-slot-spec")
            (template (hash (head "computed-slot-spec")
                            (operands ["(lambda (self superfun) ...)"])
                            (keywords [])))
            (selector "gerbil-poo://object.ss#apply-slot-spec"))
      (hash (role "slot-cache-read")
            (symbol ".ref")
            (template (hash (head ".ref")
                            (operands ["<object>" "<slot-symbol>"])
                            (keywords [])))
            (selector "gerbil-poo://object.ss#.ref"))
      (hash (role "slot-cache-read-existing")
            (symbol ".ref/cached")
            (template (hash (head ".ref/cached")
                            (operands ["<object>" "<slot-symbol>" "<default>"])
                            (keywords [])))
            (selector "gerbil-poo://object.ss#.ref/cached"))
      (hash (role "slot-cache-regression-test")
            (symbol "putslot-test")
            (template (hash (head "check")
                            (operands ["(.@ <object> <computed-slot>)"
                                       "'<expected-cached-value>"])
                            (keywords [])))
            (selector "gerbil-poo-test://t/object-test.ss#testing-putslot"))])
    ((io-json-fallback)
     [(hash (role "print-fallback")
            (symbol "@method :pr")
            (template (hash (head "defmethod")
                            (operands ["(@method :pr object)"
                                       "(lambda (self port options) ...)"])
                            (keywords [])))
            (selector "gerbil-poo://io.ss#@method:pr"))
      (hash (role "writeenv-fallback")
            (symbol "@method :wr")
            (template (hash (head "defmethod")
                            (operands ["(@method :wr object)"
                                       "(lambda (self writeenv) ...)"])
                            (keywords [])))
            (selector "gerbil-poo://io.ss#@method:wr-object"))
      (hash (role "json-fallback")
            (symbol "@method :json")
            (template (hash (head "defmethod")
                            (operands ["(@method :json object)"
                                       "(lambda (self) ...)"])
                            (keywords [])))
            (selector "gerbil-poo://io.ss#@method:json"))
      (hash (role "json-writer")
            (symbol "@method :write-json")
            (template (hash (head "defmethod")
                            (operands ["(@method :write-json object)"
                                       "(lambda (self port) ...)"])
                            (keywords [])))
            (selector "gerbil-poo://io.ss#@method:write-json"))
      (hash (role "typed-value-writer")
            (symbol "TV")
            (template (hash (head "defmethod")
                            (operands ["(@method :wr TV)"
                                       "(lambda (self writeenv) ...)"])
                            (keywords ["write-object" ".json<-" ".string<-" ".sexp<-"])))
            (selector "gerbil-poo://io.ss#@method:wr-TV"))
      (hash (role "writeenv-method-dispatch-witness")
            (symbol "method-ref")
            (template (hash (head "method-ref")
                            (operands ["<object-or-TV>" "`:wr"])
                            (keywords [])))
            (selector "gerbil-poo-witness://t/unit/poo/runtime-witness.ss#writeenv-method-dispatch"))])
    ((lens)
     [(hash (role "slot-lens")
            (symbol "slot-lens")
            (template (hash (head "slot-lens")
                            (operands ["'<slot-symbol>"])
                            (keywords [])))
            (selector "gerbil-poo://mop.ss#slot-lens"))
      (hash (role "lens-compose")
            (symbol ".compose")
            (template (hash (head ".call")
                            (operands ["<lens>" ".compose" "<nested-lens>"])
                            (keywords [])))
            (selector "gerbil-poo://mop.ss#Lens.compose"))
      (hash (role "lens-regression-test")
            (symbol "Lenses")
            (template (hash (head "check-equal?")
                            (operands ["(.alist (.call Lens .modify (slot-lens '<slot>) <fn> <object>))"
                                       "'((<slot> . <value>) ...)"])
                            (keywords [])))
            (selector "gerbil-poo-test://t/mop-test.ss#Lenses"))])
    ((type-validation)
     [(hash (role "sealed-class-definition")
            (symbol "define-type")
            (template (hash (head "define-type")
                            (operands ["(<Class> @ <Base>)"
                                       "slots: =>.+ {<slot>: {type: <Type>} ...}"])
                            (keywords ["sealed: #t"])))
            (selector "gerbil-poo://mop.ss#Class."))
      (hash (role "generic-slot-validator")
            (symbol ".defgeneric")
            (template (hash (head ".defgeneric")
                            (operands ["(<accessor> x)"])
                            (keywords ["slot: <slot>" "default: <value>"])))
            (selector "gerbil-poo://mop.ss#slot-checker"))
      (hash (role "validation-regression-test")
            (symbol "validate")
            (template (hash (head "validate")
                            (operands ["<Type>" "<object>"])
                            (keywords [])))
            (selector "gerbil-poo-test://t/mop-test.ss#sealed-type-validation"))])
    (else
     [(hash (role "class-definition")
            (symbol "defclass")
            (template (hash (head "defclass")
                            (operands ["(<Class> <Base>)" "(<slot> ...)"])
                            (keywords ["transparent: #t"])))
            (selector "gerbil-poo://object.ss#defclass"))
      (hash (role "generic-definition")
            (symbol ".defgeneric")
            (template (hash (head ".defgeneric")
                            (operands ["(<generic> <type> <arg>)"])
                            (keywords ["slot: .<slot>"])))
            (selector "gerbil-poo://mop.ss#.defgeneric"))
      (hash (role "method-dispatch")
            (symbol "defmethod")
            (template (hash (head "defmethod")
                            (operands ["(@@method <generic> <type>)"
                                       "(lambda (self) ...)"])
                            (keywords [])))
            (selector "gerbil-poo://mop.ss#defmethod"))
      (hash (role "protocol-composition")
            (symbol "compose-proto")
            (template (hash (head "compose-proto")
                            (operands ["<proto-a>" "<proto-b>"])
                            (keywords [])))
            (selector "gerbil-poo://proto.ss#compose-proto"))
      (hash (role "mro-regression-test")
            (symbol "class-precedence-list")
            (template (hash (head "check")
                            (operands ["(map ##type-name (class-precedence-list <Class>::t))"
                                       "'(<Class> <Base> ... object t)"])
                            (keywords [])))
            (selector "gerbil-runtime-test://src/gerbil/test/c3-test.ss#class-inheritance"))
      (hash (role "slot-order-regression-test")
            (symbol "class-type-slot-vector")
            (template (hash (head "check")
                            (operands ["(class-type-slot-vector <Class>::t)"
                                       "#(__class <base-slots> ... <class-slots> ...)"])
                            (keywords [])))
            (selector "gerbil-runtime-test://src/gerbil/test/c3-test.ss#slot-computation-order"))])))
;;; Boundary:
;;; - poo-pattern-failure-cases coordinates multiple evidence fields.
;;; - Keep packet shape and invariants stable.
;; PooPatternFailureCases
(def (poo-pattern-failure-cases (kind 'object-system))
  (case kind
    ((prototype-composition)
     [(hash (id "proto-order-confusion")
            (riskKind "composition-order")
            (badPattern "compose-proto-with-reversed-base-and-extension-order")
            (correctiveAction "follow-compose-proto-source-order-before-editing")
            (selectors ["gerbil-poo://proto.ss#compose-proto"
                        "gerbil-poo://proto.ss#compose-proto*"]))
      (hash (id "missing-prototype-runtime-witness")
            (riskKind "untested-composition")
            (badPattern "prototype-stack-without-instantiation-witness")
            (correctiveAction "add-instantiate-proto-behavior-snapshot")
            (selectors ["gerbil-poo://proto.ss#instantiate-proto"]))])
    ((trace-debug)
     [(hash (id "trace-without-superfun")
            (riskKind "computed-slot-contract")
            (badPattern "trace-wrapper-that-never-calls-inherited-superfun")
            (correctiveAction "call-superfun-inside-trace-inherited-slot-before-wrapping")
            (selectors ["gerbil-poo://debug.ss#trace-inherited-slot"]))
      (hash (id "eager-trace-wrapper")
            (riskKind "debug-tracing-semantics")
            (badPattern "wraps-slot-value-before-computed-slot-inheritance-runs")
            (correctiveAction "use-$computed-slot-spec-to-delay-inherited-slot-wrapper")
            (selectors ["gerbil-poo://debug.ss#trace-inherited-slot"
                        "gerbil-poo://object.ss#apply-slot-spec"]))
      (hash (id "trace-mutates-source-poo")
            (riskKind "debug-object-isolation")
            (badPattern "mutates-original-poo-while-adding-trace-slots")
            (correctiveAction "create-traced-variant-with-trace-poo-wrapper")
            (selectors ["gerbil-poo://debug.ss#trace-poo"
                        "gerbil-poo://debug.ss#trace-inherited-slot"]))])
    ((slot-cache)
     [(hash (id "uncached-slot-side-effect")
            (riskKind "slot-cache-semantics")
            (badPattern "computed-slot-with-side-effects-assumed-to-run-every-ref")
            (correctiveAction "use-ref-cache-and-ref-cached-selectors")
            (selectors ["gerbil-poo://object.ss#.ref"
                        "gerbil-poo://object.ss#.ref/cached"]))
      (hash (id "missing-superfun-chain")
            (riskKind "computed-slot-contract")
            (badPattern "computed-slot-ignores-superfun")
            (correctiveAction "follow-apply-slot-spec-superfun-form")
            (selectors ["gerbil-poo://object.ss#apply-slot-spec"]))])
    ((io-json-fallback)
     [(hash (id "json-fallback-bypass")
            (riskKind "serialization-contract")
            (badPattern "manual-json-writer-that-skips-type-json<-and-sexp")
            (correctiveAction "follow-json-fallback-order-before-overriding")
            (selectors ["gerbil-poo://io.ss#@method:json"
                        "gerbil-poo://io.ss#@method:write-json"]))
      (hash (id "print-representation-bypass")
            (riskKind "display-contract")
            (badPattern "manual-printer-that-skips-print-representation-and-sexp")
            (correctiveAction "follow-pr-fallback-order-before-overriding")
            (selectors ["gerbil-poo://io.ss#@method:pr"]))
      (hash (id "typed-value-writer-bypass")
            (riskKind "typed-value-serialization-contract")
            (badPattern "manual-TV-printer-that-skips-write-object-json-string-sexp-precedence")
            (correctiveAction "follow-TV-writeenv-fallback-order-before-specializing")
            (selectors ["gerbil-poo://io.ss#@method:wr-TV"
                        "gerbil-poo://io.ss#@method:wr-object"]))
      (hash (id "direct-writeenv-construction")
            (riskKind "runtime-internal-boundary")
            (badPattern "agent-constructs-writeenv-or-calls-:wr-directly")
            (correctiveAction "use-write-json-pr-or-method-ref-dispatch-witness-until-writeenv-roundtrip-is-owned")
            (selectors ["gerbil-runtime://builtin#writeenv"
                        "gerbil-poo-witness://t/unit/poo/runtime-witness.ss#writeenv-method-dispatch"]))
      (hash (id "write-printer-hook-assumption")
            (riskKind "printer-hook-contract")
            (badPattern "agent-assumes-write-output-roundtrips-through-poo-:wr")
            (correctiveAction "treat-writeenv-roundtrip-as-missing-until-a-runtime-owner-exposes-a-stable-writeenv-entrypoint")
            (selectors ["gerbil-poo://io.ss#@method:wr-object"
                        "gerbil-poo://io.ss#@method:wr-TV"
                        "gerbil-runtime://builtin#writeenv"]))])
    ((lens)
     [(hash (id "imperative-slot-update")
            (riskKind "functional-update-contract")
            (badPattern "manual-slot-mutation-instead-of-slot-lens")
            (correctiveAction "use-slot-lens-and-lens-compose")
            (selectors ["gerbil-poo://mop.ss#slot-lens"
                        "gerbil-poo://mop.ss#Lens.compose"]))])
    ((type-validation)
     [(hash (id "missing-required-typed-slot")
            (riskKind "type-validation-gap")
            (badPattern "class-instance-created-without-required-typed-slot")
            (correctiveAction "validate-against-real-mop-test-required-slot-failures")
            (selectors ["gerbil-poo-test://t/mop-test.ss#sealed-type-validation"
                        "gerbil-poo://mop.ss#Class."]))
      (hash (id "sealed-extra-slot-assumption")
            (riskKind "sealed-class-contract")
            (badPattern "sealed-class-accepts-extra-slots")
            (correctiveAction "respect-Class.-sealed-effective-slots-check")
            (selectors ["gerbil-poo://mop.ss#Class."
                        "gerbil-poo-test://t/mop-test.ss#sealed-type-validation"]))
      (hash (id "unchecked-function-arity")
            (riskKind "function-validation-contract")
            (badPattern "function-slot-without-arity-or-type-validation")
            (correctiveAction "use-Function.-validate-row-witness")
            (selectors ["gerbil-poo://mop.ss#Function."]))])
    (else
     [(hash (id "racket-class-syntax")
            (riskKind "dialect-confusion")
            (badPattern "racket-class-or-generic-scheme-object")
            (correctiveAction "use-poo-form-mapping")
            (selectors ["gerbil-poo://object.ss#defclass"
                        "gerbil-poo://mop.ss#.defgeneric"
                        "gerbil-poo://mop.ss#defmethod"]))
      (hash (id "missing-extension-activation")
            (riskKind "inactive-extension")
            (badPattern "poo-forms-without-gerbil.pkg-dependency")
            (correctiveAction "query-extension-before-pattern")
            (selectors ["gerbil.pkg"]))
      (hash (id "method-without-generic")
            (riskKind "incomplete-method-contract")
            (badPattern "defmethod-without-generic-slot-contract")
            (correctiveAction "follow-generic-and-method-mappings-together")
            (selectors ["gerbil-poo://mop.ss#.defgeneric"
                        "gerbil-poo://mop.ss#defmethod"]))
      (hash (id "unchecked-mro-assumption")
            (riskKind "semantic-regression-gap")
            (badPattern "class-hierarchy-without-c3-or-slot-order-test")
            (correctiveAction "add-c3-linearization-and-slot-vector-witnesses")
            (selectors ["gerbil-runtime://c3.ss#class-precedence-list"
                        "gerbil-runtime-test://src/gerbil/test/c3-test.ss#c3-test"
                        "gerbil-runtime-test://src/gerbil/test/c3-test.ss#slot-computation-order"]))])))
;;; Boundary:
;;; - poo-pattern-quality-signals coordinates multiple evidence fields.
;;; - Keep packet shape and invariants stable.
;; PooPatternQualitySignals <- String
(def (poo-pattern-quality-signals kind)
  (case kind
    ((prototype-composition)
     ["dependency-backed-mapping" "proto-source" "composition-order"
      "runtime-prototype-composition-witness"])
    ((trace-debug)
     ["dependency-backed-mapping" "debug-source" "computed-slot-source"
      "superfun-chain-source" "trace-wrapper-source" "runtime-trace-poo-witness"])
    ((slot-cache)
     ["dependency-backed-mapping" "apply-slot-spec-source" "ref-cache-source"
      "real-project-slot-cache-test" "superfun-witness"])
    ((io-json-fallback)
     ["dependency-backed-mapping" "json-fallback-source" "print-fallback-source"
      "writeenv-fallback-source" "typed-value-writer-source" "json-roundtrip-witness"
      "print-fallback-witness" "writeenv-method-dispatch-witness"
      "writeenv-roundtrip-witness-required"])
    ((lens)
     ["dependency-backed-mapping" "lens-source" "slot-lens-source"
      "real-project-lens-test" "functional-update-witness"])
    ((type-validation)
     ["dependency-backed-mapping" "class-descriptor-source" "function-validator-source"
      "real-project-mop-test" "sealed-type-witness" "validation-negative-witness"])
    ((c3-mro)
     ["active-extension-fact" "dependency-backed-mapping" "real-project-c3-test"
      "mro-linearization-witness" "slot-order-witness" "failure-cases"])
    (else
     ["active-extension-fact" "dependency-backed-mapping" "real-project-c3-test"
      "mro-linearization-witness" "slot-order-witness" "minimal-forms"
      "failure-cases"])))
;; PooPatternWitness <- String
(def (poo-pattern-witness kind)
  (case kind
    ((prototype-composition) "runtime-prototype-composition-witness")
    ((trace-debug) "runtime-trace-poo-witness")
    ((slot-cache) "real-project-slot-cache-witness")
    ((io-json-fallback) "runtime-json-print-writeenv-method-source-backed-io-fallback")
    ((lens) "real-project-lens-witness")
    ((type-validation) "real-project-sealed-type-validation-witness")
    ((c3-mro) "real-project-c3-and-slot-order-witness")
    (else "dependency-backed-poo-mapping")))
;; PooPatternMissing <- String
(def (poo-pattern-missing kind)
  (case kind
    ((prototype-composition) [])
    ((trace-debug) [])
    ((slot-cache) [])
    ((io-json-fallback) ["writeenv-roundtrip-witness"])
    ((lens) [])
    ((type-validation) [])
    (else [])))
;; String <- String
(def (poo-pattern-next kind)
  (case kind
    ((prototype-composition) "search pattern poo prototype composition witness")
    ((trace-debug) "search pattern poo trace runtime witness")
    ((slot-cache) "search pattern poo slot cache computed")
    ((io-json-fallback) "search runtime-source writeenv printer hook")
    ((lens) "search pattern poo lens slot-lens")
    ((type-validation) "search pattern poo sealed validate")
    ((c3-mro) "search extension poo pattern c3")
    (else "search extension poo syntax")))
;; Boolean <- Suffix SourceLine
(def (string-suffix? suffix text)
  (let ((suffix-length (string-length suffix))
        (text-length (string-length text)))
    (and (fx<= suffix-length text-length)
         (equal? suffix
                 (substring text (fx- text-length suffix-length) text-length)))))
