;;; -*- Gerbil -*-
(import :gerbil/gambit
        :std/test
        :std/misc/ports
        :commands/check
        :parser/facade
        :policy/facade
        :types/facade
        :unit/policy/poo-scenarios)
(export policy-test)

(def policy-test
  (test-suite "gerbil scheme harness policy"
    (test-case "modularity policy rejects facade implementation"
      (let* ((root ".run/policy-modularity")
             (_ (write-facade-policy-project
                 root "foo"
                 ";;; -*- Gerbil -*-\n;;; Foo facade.\n(export answer)\n(def answer 42)\n"
                 ";;; -*- Gerbil -*-\n;;; Foo core.\n(def core-answer 42)\n"))
             (index (collect-project root))
             (findings (run-modularity-policy index))
             (finding (car findings)))
        (check (length findings) => 1)
        (check (type-finding-rule-id finding)
               => "GERBIL-SCHEME-MOD-R001")
        (check (type-finding-path finding) => "src/foo/facade.ss")))
    (test-case "modularity policy follows package source scope roots"
      (let* ((root ".run/policy-source-scope-modularity")
             (lib (string-append root "/lib"))
             (owner (string-append lib "/foo")))
        (ensure-dir ".run")
        (ensure-dir root)
        (ensure-dir lib)
        (ensure-dir owner)
        (write-text (string-append root "/gerbil.pkg")
                    "(package: sample/scope\n  policy: ((source-scope roots: (\"lib\") runtime-roots: (\"lib\") explanation: \"Runtime modules live under lib for this package.\")))\n")
        (write-text (string-append owner "/facade.ss")
                    ";;; -*- Gerbil -*-\n;;; Foo facade.\n(export answer)\n(def answer 42)\n")
        (write-text (string-append owner "/core.ss")
                    ";;; -*- Gerbil -*-\n;;; Foo core.\n(def core-answer 42)\n")
        (let* ((index (collect-project root))
               (findings (run-modularity-policy index))
               (matching (filter-rule "GERBIL-SCHEME-MOD-R001" findings))
               (finding (car matching)))
          (check (length matching) => 1)
          (check (type-finding-path finding) => "lib/foo/facade.ss"))))
    (test-case "modularity policy follows build script runtime roots"
      (let* ((root ".run/policy-build-scope-modularity")
             (lib (string-append root "/lib"))
             (owner (string-append lib "/foo")))
        (ensure-dir ".run")
        (ensure-dir root)
        (ensure-dir lib)
        (ensure-dir owner)
        (write-text (string-append root "/gerbil.pkg")
                    "(package: sample/build-scope)\n")
        (write-text (string-append root "/build.ss")
                    ";;; -*- Gerbil -*-\n(defbuild-script '(\"lib/foo/core\"))\n")
        (write-text (string-append owner "/facade.ss")
                    ";;; -*- Gerbil -*-\n;;; Foo facade.\n(export answer)\n(def answer 42)\n")
        (write-text (string-append owner "/core.ss")
                    ";;; -*- Gerbil -*-\n;;; Foo core.\n(def core-answer 42)\n")
        (let* ((index (collect-project root))
               (findings (run-modularity-policy index))
               (matching (filter-rule "GERBIL-SCHEME-MOD-R001" findings))
               (finding (car matching)))
          (check (length matching) => 1)
          (check (type-finding-path finding) => "lib/foo/facade.ss"))))
    (test-case "modularity policy rejects sibling file and owner directory"
      (let* ((root ".run/policy-owner-collision")
             (_ (write-policy-project
                 root "foo"
                 ";;; -*- Gerbil -*-\n;;; Foo sibling entry.\n(export answer)\n"
                 ";;; -*- Gerbil -*-\n;;; Foo core.\n(def core-answer 42)\n"))
             (index (collect-project root))
             (findings (run-modularity-policy index))
             (matching (filter-rule "GERBIL-SCHEME-MOD-R003" findings))
             (finding (car matching)))
        (check (length matching) => 1)
        (check (type-finding-rule-id finding)
               => "GERBIL-SCHEME-MOD-R003")
        (check (type-finding-path finding) => "src/foo.ss")))
    (test-case "modularity policy rejects repeated owner entry names"
      (let* ((root ".run/policy-repeated-owner-entry")
             (_ (write-owner-entry-policy-project
                 root "foo"
                 ";;; -*- Gerbil -*-\n;;; Foo repeated entry.\n(export answer)\n"
                 ";;; -*- Gerbil -*-\n;;; Foo core.\n(def core-answer 42)\n"))
             (index (collect-project root))
             (findings (run-modularity-policy index))
             (matching (filter-rule "GERBIL-SCHEME-MOD-R004" findings))
             (finding (car matching)))
        (check (length matching) => 1)
        (check (type-finding-rule-id finding)
               => "GERBIL-SCHEME-MOD-R004")
        (check (type-finding-path finding) => "src/foo/foo.ss")))
    (test-case "modularity policy rejects bin entrypoint implementation"
      (let* ((root ".run/policy-bin-entrypoint")
             (_ (write-bin-entrypoint-project
                 root ";;; -*- Gerbil -*-\n(import :std/cli/getopt)\n(def (main . args) args)\n"))
             (index (collect-project root))
             (findings (run-modularity-policy index))
             (matching (filter-rule "GERBIL-SCHEME-MOD-R005" findings))
             (finding (car matching)))
        (check (length matching) => 1)
        (check (type-finding-rule-id finding)
               => "GERBIL-SCHEME-MOD-R005")
        (check (type-finding-path finding) => "bin/run.ss")))
    (test-case "modularity policy rejects legacy test directory layout"
      (let* ((root ".run/policy-test-directory-layout")
             (_ (write-test-directory-layout-project root))
             (index (collect-project root))
             (findings (run-modularity-policy index))
             (matching (filter-rule "GERBIL-SCHEME-MOD-R006" findings)))
        (check (length matching) => 2)
        (check (map type-finding-path matching)
               => ["test/bad-test.ss" "tests/bad-tests-test.ss"])
        (check (type-finding-message (car matching))
               => "Gerbil unit test owner test/bad-test.ss uses non-t test/ layout; use t/ unless gerbil.pkg policy explicitly allows this directory with a clear explanation (no policy override)")))
    (test-case "modularity policy allows non-t test directories only with clear package policy"
      (let* ((root ".run/policy-test-directory-layout-allowed")
             (_ (write-test-directory-layout-project
                 root
                 ";;; -*- Gerbil -*-\n(package: sample\n  policy: ((test-directory-layout allowed-directories: (\"test\" \"tests\") explanation: \"This downstream conformance fixture mirrors upstream test directories that cannot be moved into t/ during replay.\")))\n"))
             (index (collect-project root))
             (findings (run-modularity-policy index))
             (matching (filter-rule "GERBIL-SCHEME-MOD-R006" findings)))
        (check matching => [])))
    (test-case "modularity policy rejects non-t test directory override without clear explanation"
      (let* ((root ".run/policy-test-directory-layout-short-explanation")
             (_ (write-test-directory-layout-project
                 root
                 ";;; -*- Gerbil -*-\n(package: sample\n  policy: ((test-directory-layout allowed-directories: (\"test\" \"tests\") explanation: \"temporary\")))\n"))
             (index (collect-project root))
             (findings (run-modularity-policy index))
             (matching (filter-rule "GERBIL-SCHEME-MOD-R006" findings)))
        (check (length matching) => 2)
        (check (type-finding-message (car matching))
               => "Gerbil unit test owner test/bad-test.ss uses non-t test/ layout; use t/ unless gerbil.pkg policy explicitly allows this directory with a clear explanation (policy override is missing a clear explanation)")))
    (test-case "agent policy requires facade intent comment"
      (let* ((root ".run/policy-agent")
             (_ (write-facade-policy-project
                 root "bar"
                 ";;; -*- Gerbil -*-\n(export value)\n"
                 ";;; -*- Gerbil -*-\n;;; Bar core.\n(def value 1)\n"))
             (index (collect-project root))
             (findings (run-agent-policy index))
             (finding (car findings)))
        (check (length findings) => 1)
        (check (type-finding-rule-id finding)
               => "GERBIL-SCHEME-AGENT-R001")
        (check (type-finding-path finding) => "src/bar/facade.ss")))
    (test-case "modularity policy rejects oversized source leaves"
      (let* ((root ".run/policy-source-leaf")
             (_ (write-large-policy-source root "large"))
             (index (collect-project root))
             (findings (run-modularity-policy index))
             (matching (filter-rule "GERBIL-SCHEME-MOD-R002" findings))
             (finding (car matching)))
        (check (length matching) => 1)
        (check (type-finding-rule-id finding)
               => "GERBIL-SCHEME-MOD-R002")
        (check (type-finding-path finding) => "src/large/core.ss")))
    (test-case "agent policy rejects generic owner names"
      (let* ((root ".run/policy-generic-owner")
             (_ (write-facade-policy-project
                 root "utils"
                 ";;; -*- Gerbil -*-\n;;; Utilities facade.\n(export value)\n"
                 ";;; -*- Gerbil -*-\n;;; Utilities core.\n(def value 1)\n"))
             (index (collect-project root))
             (findings (run-agent-policy index))
             (matching (filter-rule "GERBIL-SCHEME-AGENT-R002" findings))
             (finding (car matching)))
        (check (length matching) => 2)
        (check (type-finding-rule-id finding)
               => "GERBIL-SCHEME-AGENT-R002")
        (check (not (not (member "src/utils/facade.ss"
                                  (map type-finding-path matching))))
               => #t)))
    (test-case "agent policy rejects vague definition names"
      (let* ((root ".run/policy-vague-definition")
             (_ (write-vague-definition-project root))
             (index (collect-project root))
             (findings (run-agent-policy index))
             (matching (filter-rule "GERBIL-SCHEME-AGENT-R004" findings))
             (finding (car matching)))
        (check (length matching) => 1)
        (check (type-finding-rule-id finding)
               => "GERBIL-SCHEME-AGENT-R004")
        (check (type-finding-path finding) => "src/orders/core.ss")
        (check (type-finding-selector finding) => "src/orders/core.ss:3-3")))
    (test-case "package agent-policy disables selected rules"
      (let* ((root ".run/policy-agent-disabled-rule")
             (src (string-append root "/src"))
             (owner (string-append src "/orders")))
        (ensure-dir ".run")
        (ensure-dir root)
        (ensure-dir src)
        (ensure-dir owner)
        (write-text (string-append root "/gerbil.pkg")
                    "(package: sample/orders\n  policy: ((agent-policy disabled-rules: (\"GERBIL-SCHEME-AGENT-R004\"))))\n")
        (write-text (string-append owner "/core.ss")
                    ";;; -*- Gerbil -*-\n(package: sample/orders)\n(def (process order) order)\n")
        (let* ((index (collect-project root))
               (findings (run-policy-checks index))
               (matching (filter-rule "GERBIL-SCHEME-AGENT-R004" findings)))
          (check matching => []))))
    (test-case "agent policy rejects top-level executable calls in src"
      (let* ((root ".run/policy-top-level-executable")
             (_ (write-top-level-executable-project root))
             (index (collect-project root))
             (findings (run-agent-policy index))
             (matching (filter-rule "GERBIL-SCHEME-AGENT-R005" findings))
             (finding (car matching)))
        (check (length matching) => 1)
        (check (type-finding-rule-id finding)
               => "GERBIL-SCHEME-AGENT-R005")
        (check (type-finding-path finding) => "src/orders/core.ss")
        (check (type-finding-selector finding) => "src/orders/core.ss:3-3")
        (check (type-finding-message finding)
               => "top-level executable call displayln should move behind a named definition or explicit entrypoint")))
    (test-case "agent policy warns on manual loops that should use functional idioms"
      (let* ((root ".run/policy-functional-idiom")
             (_ (write-functional-idiom-project root))
             (index (collect-project root))
             (findings (run-agent-policy index))
             (matching (filter-rule "GERBIL-SCHEME-AGENT-R009" findings))
             (finding (car matching)))
        (check (length matching) => 1)
        (check (type-finding-severity finding) => "warning")
        (check (type-status matching) => "fail")
        (check (type-finding-path finding) => "src/orders/core.ss")
        (check (type-finding-selector finding) => "src/orders/core.ss:5-6")
        (check (not (not (string-contains
                          (type-finding-message finding)
                          "prefer for/fold, map/filter/filter-map/append-map")))
               => #t)
        (check (hash-get (type-finding-details finding) 'kind)
               => "named-let")
        (check (hash-get (type-finding-details finding) 'sequenceIdioms)
               => ["map" "filter" "filter-map" "append-map" "fold/foldl/foldr" "for/fold"])
        (check (hash-get (type-finding-details finding) 'predicateIdioms)
               => ["andmap/ormap" "every/any" "find/list-index"])
        (check (hash-get (type-finding-details finding) 'compositionIdioms)
               => ["cut/cute" "curry/rcurry" "compose/compose1"])
        (check (hash-get (type-finding-details finding) 'builderIdioms)
               => ["with-list-builder"])
        (check (hash-get (type-finding-details finding) 'detectedControlContexts)
               => [])
        (check (hash-get (type-finding-details finding) 'keepNamedLetWhen)
               => "IO/stateful control flow, C3-style fixpoint selection, or generator/continuation driver")))
    (test-case "agent policy check output routes findings to guide code"
      (let* ((root ".run/policy-functional-idiom-check-output")
             (_ (write-functional-idiom-project root))
             (result (check-output [root]))
             (output (cdr result)))
        (check (car result) => 1)
        (check (not (not (string-contains
                          output
                          "guideTopic=functional-data-transform")))
               => #t)
        (check (not (not (string-contains
                          output
                          "guideIntent=repair")))
               => #t)
        (check (not (not (string-contains
                          output
                          "nextCommand=asp gerbil-scheme guide --code --rule GERBIL-SCHEME-AGENT-R009 --intent repair")))
               => #t)))
    (test-case "agent policy reports named-let preservation control contexts"
      (let* ((root ".run/policy-functional-idiom-control-context")
             (_ (write-functional-idiom-control-context-project root))
             (index (collect-project root))
             (findings (run-agent-policy index))
             (matching (filter-rule "GERBIL-SCHEME-AGENT-R009" findings))
             (finding (car matching))
             (contexts (hash-get (type-finding-details finding)
                                 'detectedControlContexts)))
        (check (length matching) => 1)
        (check (type-finding-severity finding) => "warning")
        (check (not (not (member "continuation-control" contexts))) => #t)
        (check (not (not (member "protected-control" contexts))) => #t)
        (check (not (not (member "protected-handler" contexts))) => #t)))
    (test-case "agent policy accepts explicit higher-order idiom"
      (let* ((root ".run/policy-functional-idiom-positive")
             (_ (write-functional-idiom-positive-project root))
             (index (collect-project root))
             (findings (run-agent-policy index))
             (matching (filter-rule "GERBIL-SCHEME-AGENT-R009" findings)))
        (check (length matching) => 0)))
    (test-case "agent policy rejects direct POO writeenv calls"
      (let* ((root ".run/policy-poo-direct-writeenv")
             (_ (write-poo-direct-writeenv-project root))
             (index (collect-project root))
             (findings (run-agent-policy index))
             (matching (filter-rule "GERBIL-SCHEME-AGENT-R006" findings))
             (finding (car matching)))
        (check (length matching) => 1)
        (check (type-finding-rule-id finding)
               => "GERBIL-SCHEME-AGENT-R006")
        (check (type-finding-path finding) => "src/orders/io.ss")
        (check (type-finding-message finding)
               => "direct writeenv calls bypass POO IO runtime-source evidence; query search runtime-source writeenv printer hook first")))
    (test-case "agent policy requires runtime-source witness for POO IO overrides"
      (let* ((root ".run/policy-poo-io-runtime-witness")
             (_ (write-poo-io-override-project root))
             (index (collect-project root))
             (findings (run-agent-policy index))
             (matching (filter-rule "GERBIL-SCHEME-AGENT-R007" findings))
             (finding (car matching)))
        (check (length matching) => 1)
        (check (type-finding-rule-id finding)
               => "GERBIL-SCHEME-AGENT-R007")
        (check (type-finding-path finding) => "src/orders/io.ss")
        (check (type-finding-message finding)
               => "POO IO method overrides in src/ need runtime-source-backed writeenv/printer-hook witness coverage before being treated as verified")))
    (test-case "agent policy requires POO method generic and class facts"
      (let* ((root ".run/policy-poo-method-shape")
             (_ (write-poo-method-shape-project root))
             (index (collect-project root))
             (findings (run-agent-policy index))
             (matching (filter-rule "GERBIL-SCHEME-AGENT-R008" findings))
             (finding (car matching)))
        (check (length matching) => 1)
        (check (type-finding-rule-id finding)
               => "GERBIL-SCHEME-AGENT-R008")
        (check (type-finding-path finding) => "src/orders/methods.ss")
        (check (type-finding-message finding)
               => "POO method order-discount is missing parser-owned defgeneric,defclass-or-defprotocol facts; query POO pattern evidence and add defgeneric/defclass/defprotocol structure before extending methods")))
    (test-case "agent policy requires macro runtime-source witness"
      (let* ((root ".run/policy-macro-runtime-source")
             (_ (write-macro-runtime-source-project root #f))
             (index (collect-project root))
             (findings (run-agent-policy index))
             (matching (filter-rule "GERBIL-SCHEME-AGENT-R011" findings))
             (finding (car matching)))
        (check (length matching) => 1)
        (check (type-finding-path finding) => "src/macros/core.ss")
        (check (hash-get (type-finding-details finding) 'next)
               => "search runtime-source macro sugar module-sugar")))
    (test-case "agent policy accepts macro runtime-source witness policy"
      (let* ((root ".run/policy-macro-runtime-source-allowed")
             (_ (write-macro-runtime-source-project root #t))
             (index (collect-project root))
             (findings (run-agent-policy index))
             (matching (filter-rule "GERBIL-SCHEME-AGENT-R011" findings)))
        (check matching => [])))
    (test-case "agent policy requires declared protocol evidence"
      (let* ((root ".run/policy-protocol-evidence")
             (_ (write-protocol-evidence-project root #f))
             (index (collect-project root))
             (findings (run-agent-policy index))
             (matching (filter-rule "GERBIL-SCHEME-AGENT-R012" findings))
             (finding (car matching)))
        (check (length matching) => 1)
        (check (type-finding-path finding) => "src/orders/protocol.ss")
        (check (hash-get (type-finding-details finding) 'next)
               => "search pattern poo protocol")))
    (test-case "agent policy accepts declared protocol evidence"
      (let* ((root ".run/policy-protocol-evidence-positive")
             (_ (write-protocol-evidence-project root #t))
             (index (collect-project root))
             (findings (run-agent-policy index))
             (matching (filter-rule "GERBIL-SCHEME-AGENT-R012" findings)))
        (check matching => [])))
    (test-case "agent policy catches downstream POO implementation drift"
      (let* ((root ".run/policy-downstream-poo-agent")
             (_ (write-downstream-poo-agent-project root))
             (index (collect-project root))
             (findings (run-agent-policy index))
             (vague (filter-rule "GERBIL-SCHEME-AGENT-R004" findings))
             (direct-writeenv (filter-rule "GERBIL-SCHEME-AGENT-R006" findings))
             (runtime-witness (filter-rule "GERBIL-SCHEME-AGENT-R007" findings))
             (method-shape (filter-rule "GERBIL-SCHEME-AGENT-R008" findings))
             (object-model (filter-rule "GERBIL-SCHEME-AGENT-R010" findings)))
        (check (length vague) => 1)
        (check (length direct-writeenv) => 1)
        (check (length runtime-witness) => 1)
        (check (length method-shape) => 1)
        (check (length object-model) => 1)
        (check (type-finding-path (car vague)) => "src/orders/core.ss")
        (check (type-finding-path (car direct-writeenv)) => "src/orders/io.ss")
        (check (type-finding-path (car runtime-witness)) => "src/orders/io.ss")
        (check (type-finding-path (car method-shape)) => "src/orders/io.ss")
        (check (type-finding-path (car object-model)) => "src/orders/core.ss")
        (check (type-finding-selector (car object-model)) => "src/orders/core.ss:4-4")))
    (test-case "agent policy accepts downstream POO pattern-guided implementation"
      (let* ((root ".run/policy-downstream-poo-agent-positive")
             (_ (write-downstream-poo-agent-positive-project root))
             (index (collect-project root))
             (findings (run-agent-policy index)))
        (check findings => [])))
    (test-case "agent policy rejects duplicate facade exports"
      (let* ((root ".run/policy-export-conflict")
             (_alpha (write-facade-policy-project
                      root "alpha"
                      ";;; -*- Gerbil -*-\n;;; Alpha facade.\n(export value)\n"
                      ";;; -*- Gerbil -*-\n;;; Alpha core.\n(def value 1)\n"))
             (_beta (write-facade-policy-project
                     root "beta"
                     ";;; -*- Gerbil -*-\n;;; Beta facade.\n(export value)\n"
                     ";;; -*- Gerbil -*-\n;;; Beta core.\n(def value 2)\n"))
             (index (collect-project root))
             (findings (run-agent-policy index))
             (matching (filter-rule "GERBIL-SCHEME-AGENT-R003" findings))
             (finding (car matching)))
        (check (length matching) => 1)
        (check (type-finding-rule-id finding)
               => "GERBIL-SCHEME-AGENT-R003")
        (check (type-finding-path finding) => "src/beta/facade.ss")))))

(def (filter-rule rule-id findings)
  (filter (lambda (finding)
            (equal? (type-finding-rule-id finding) rule-id))
          findings))

(def (check-output args)
  (let* ((status #f)
         (output
          (call-with-output-string
            (lambda (out)
              (parameterize ((current-output-port out))
                (set! status (check-main args)))))))
    (cons status output)))

(def (write-policy-project root facade-name facade-source core-source)
  (let* ((src (string-append root "/src"))
         (owner (string-append src "/" facade-name))
         (facade-path (string-append src "/" facade-name ".ss"))
         (owner-entry-path (string-append owner "/" facade-name ".ss"))
         (core-path (string-append owner "/core.ss")))
    (ensure-dir ".run")
    (ensure-dir root)
    (ensure-dir src)
    (ensure-dir owner)
    (delete-file-if-exists owner-entry-path)
    (write-text facade-path facade-source)
    (write-text core-path core-source)))

(def (write-owner-entry-policy-project root owner-name facade-source core-source)
  (let* ((src (string-append root "/src"))
         (owner (string-append src "/" owner-name))
         (sibling-path (string-append src "/" owner-name ".ss"))
         (facade-entry-path (string-append owner "/facade.ss"))
         (facade-path (string-append owner "/" owner-name ".ss"))
         (core-path (string-append owner "/core.ss")))
    (ensure-dir ".run")
    (ensure-dir root)
    (ensure-dir src)
    (ensure-dir owner)
    (delete-file-if-exists sibling-path)
    (delete-file-if-exists facade-entry-path)
    (write-text facade-path facade-source)
    (write-text core-path core-source)))

(def (write-facade-policy-project root owner-name facade-source core-source)
  (let* ((src (string-append root "/src"))
         (owner (string-append src "/" owner-name))
         (sibling-path (string-append src "/" owner-name ".ss"))
         (repeated-entry-path (string-append owner "/" owner-name ".ss"))
         (facade-path (string-append owner "/facade.ss"))
         (core-path (string-append owner "/core.ss")))
    (ensure-dir ".run")
    (ensure-dir root)
    (ensure-dir src)
    (ensure-dir owner)
    (delete-file-if-exists sibling-path)
    (delete-file-if-exists repeated-entry-path)
    (write-text facade-path facade-source)
    (write-text core-path core-source)))

(def (write-bin-entrypoint-project root source)
  (let* ((bin (string-append root "/bin"))
         (entrypoint-path (string-append bin "/run.ss")))
    (ensure-dir ".run")
    (ensure-dir root)
    (ensure-dir bin)
    (write-text entrypoint-path source)))

(def (write-test-directory-layout-project root . maybe-package-source)
  (let ((legacy-test (string-append root "/test"))
        (legacy-tests (string-append root "/tests"))
        (native-test (string-append root "/t"))
        (package-path (string-append root "/gerbil.pkg")))
    (ensure-dir ".run")
    (ensure-dir root)
    (ensure-dir legacy-test)
    (ensure-dir legacy-tests)
    (ensure-dir native-test)
    (if (pair? maybe-package-source)
      (write-text package-path (car maybe-package-source))
      (delete-file-if-exists package-path))
    (write-text (string-append legacy-test "/bad-test.ss")
                ";;; -*- Gerbil -*-\n(import :std/test)\n(def bad-test (test-suite \"bad\"))\n")
    (write-text (string-append legacy-tests "/bad-tests-test.ss")
                ";;; -*- Gerbil -*-\n(import :std/test)\n(def bad-tests-test (test-suite \"bad tests\"))\n")
    (write-text (string-append native-test "/good-test.ss")
                ";;; -*- Gerbil -*-\n(import :std/test)\n(def good-test (test-suite \"good\"))\n")))

(def (write-vague-definition-project root)
  (let* ((src (string-append root "/src"))
         (owner (string-append src "/orders")))
    (ensure-dir ".run")
    (ensure-dir root)
    (ensure-dir src)
    (ensure-dir owner)
    (write-text (string-append owner "/core.ss")
                ";;; -*- Gerbil -*-\n(package: sample/orders)\n(def (process order) order)\n(def (order-total order) order)\n")))

(def (write-top-level-executable-project root)
  (let* ((src (string-append root "/src"))
         (owner (string-append src "/orders")))
    (ensure-dir ".run")
    (ensure-dir root)
    (ensure-dir src)
    (ensure-dir owner)
    (write-text (string-append owner "/core.ss")
                ";;; -*- Gerbil -*-\n(import :std/misc/ports)\n(displayln \"bad\")\n(def (named) #t)\n")))

(def (write-functional-idiom-project root)
  (let* ((src (string-append root "/src"))
         (owner (string-append src "/orders")))
    (ensure-dir ".run")
    (ensure-dir root)
    (ensure-dir src)
    (ensure-dir owner)
    (write-text (string-append owner "/facade.ss")
                ";;; -*- Gerbil -*-\n;;; Orders facade intent.\n(export total)\n")
    (write-text (string-append owner "/core.ss")
                ";;; -*- Gerbil -*-\n(package: sample/orders)\n(export total)\n(def (total xs)\n  (let loop ((rest xs) (acc 0))\n    (if (null? rest) acc (loop (cdr rest) (+ acc (car rest))))))\n")))

(def (write-functional-idiom-positive-project root)
  (let* ((src (string-append root "/src"))
         (owner (string-append src "/orders")))
    (ensure-dir ".run")
    (ensure-dir root)
    (ensure-dir src)
    (ensure-dir owner)
    (write-text (string-append owner "/facade.ss")
                ";;; -*- Gerbil -*-\n;;; Orders facade intent.\n(export total)\n")
    (write-text (string-append owner "/core.ss")
                ";;; -*- Gerbil -*-\n(package: sample/orders)\n(export total)\n(def (total xs)\n  (for/fold ((acc 0)) ((x xs)) (+ acc x)))\n")))

(def (write-functional-idiom-control-context-project root)
  (let* ((src (string-append root "/src"))
         (owner (string-append src "/orders")))
    (ensure-dir ".run")
    (ensure-dir root)
    (ensure-dir src)
    (ensure-dir owner)
    (write-text (string-append owner "/facade.ss")
                ";;; -*- Gerbil -*-\n;;; Orders facade intent.\n(export drain)\n")
    (write-text (string-append owner "/core.ss")
                ";;; -*- Gerbil -*-\n(package: sample/orders)\n(export drain)\n(def (drain xs)\n  (let/cc stop\n    (let loop ((rest xs))\n      (if (null? rest) (stop #f) (loop (cdr rest)))))\n  (try (void) (finally (void))))\n")))

(def (write-macro-runtime-source-project root allowed?)
  (let* ((src (string-append root "/src"))
         (owner (string-append src "/macros")))
    (ensure-dir ".run")
    (ensure-dir root)
    (ensure-dir src)
    (ensure-dir owner)
    (if allowed?
      (write-text (string-append root "/gerbil.pkg")
                  "(package: sample/macros\n  policy: ((macro-governance allow-generated: #t explanation: \"Macro transformer edits are allowed only with runtime-source and expansion evidence.\" witness: \"search runtime-source macro sugar module-sugar\")))\n")
      (delete-file-if-exists (string-append root "/gerbil.pkg")))
    (write-text (string-append owner "/core.ss")
                ";;; -*- Gerbil -*-\n(package: sample/macros)\n(defsyntax (with-order stx)\n  #'(void))\n")))

(def (write-protocol-evidence-project root declared?)
  (let* ((src (string-append root "/src"))
         (owner (string-append src "/orders")))
    (ensure-dir ".run")
    (ensure-dir root)
    (ensure-dir src)
    (ensure-dir owner)
    (write-text (string-append owner "/protocol.ss")
                (string-append
                 ";;; -*- Gerbil -*-\n(package: sample/orders)\n(import :clan/poo/protocol)\n"
                 (if declared? "(defprotocol <Renderable>)\n" "")
                 "(defgeneric :render)\n"
                 "(defmethod (:render (value <Renderable>)) value)\n"))))

(def (ensure-dir path)
  (with-catch
   (lambda (_) #f)
   (lambda () (create-directory path))))

(def (write-text path text)
  (delete-file-if-exists path)
  (call-with-output-file path
    (lambda (port) (display text port))))

(def (delete-file-if-exists path)
  (with-catch
   (lambda (_) #f)
   (lambda () (delete-file path))))

(def (write-large-policy-source root owner-name)
  (let* ((src (string-append root "/src"))
         (owner (string-append src "/" owner-name))
         (source-path (string-append owner "/core.ss")))
    (ensure-dir ".run")
    (ensure-dir root)
    (ensure-dir src)
    (ensure-dir owner)
    (with-catch
     (lambda (_) #f)
     (lambda () (delete-file source-path)))
    (call-with-output-file source-path
      (lambda (port)
        (display ";;; -*- Gerbil -*-\n;;; Large source leaf.\n" port)
        (let lp ((index 0))
          (when (fx< index 45)
            (display "(def value" port)
            (display index port)
            (display " " port)
            (display index port)
            (display ")\n" port)
            (lp (fx1+ index))))
        (let lp ((index 0))
          (when (fx< index 610)
            (display ";; padding\n" port)
            (lp (fx1+ index))))))))
