;;; -*- Gerbil -*-
;;; Boundary:
;;; - test owner records policy expectations.
;;; - Keep typed contracts and fixture intent explicit.
(import :gerbil/gambit
        :std/test
        :std/misc/ports
        :std/misc/process
        (only-in :std/text/json read-json)
        :commands/check
        :parser/facade
        :policy/facade
        :types/facade
        :unit/policy/poo-scenarios)
(export policy-test)
;; PolicyTest
(def policy-test
  (test-suite "gerbil scheme harness policy"
    (test-case "modularity policy rejects facade implementation"
      (let* ((root ".run/policy-modularity")
             (_ (write-facade-policy-project
                 root "foo"
                 ";;; -*- Gerbil -*-\n;;; Foo facade.\n(export answer)\n(def answer 42)\n"
                 ";;; -*- Gerbil -*-\n;;; Foo core.\n(def core-answer 42)\n"))
             (index (collect-project root))
             (findings (run-modularity-policy index))
             (finding (car findings)))
        (check (length findings) => 1)
        (check (type-finding-rule-id finding)
               => "GERBIL-SCHEME-MOD-R001")
        (check (type-finding-path finding) => "src/foo/facade.ss")))
    (test-case "modularity policy follows package source scope roots"
      (let* ((root ".run/policy-source-scope-modularity")
             (lib (string-append root "/lib"))
             (owner (string-append lib "/foo")))
        (ensure-dir ".run")
        (ensure-dir root)
        (ensure-dir lib)
        (ensure-dir owner)
        (write-text (string-append root "/gerbil.pkg")
                    "(package: sample/scope\n  policy: ((source-scope roots: (\"lib\") runtime-roots: (\"lib\") explanation: \"Runtime modules live under lib for this package.\")))\n")
        (write-text (string-append owner "/facade.ss")
                    ";;; -*- Gerbil -*-\n;;; Foo facade.\n(export answer)\n(def answer 42)\n")
        (write-text (string-append owner "/core.ss")
                    ";;; -*- Gerbil -*-\n;;; Foo core.\n(def core-answer 42)\n")
        (let* ((index (collect-project root))
               (findings (run-modularity-policy index))
               (matching (filter-rule "GERBIL-SCHEME-MOD-R001" findings))
               (finding (car matching)))
          (check (length matching) => 1)
          (check (type-finding-path finding) => "lib/foo/facade.ss"))))
    (test-case "modularity policy follows build script runtime roots"
      (let* ((root ".run/policy-build-scope-modularity")
             (lib (string-append root "/lib"))
             (owner (string-append lib "/foo")))
        (ensure-dir ".run")
        (ensure-dir root)
        (ensure-dir lib)
        (ensure-dir owner)
        (write-text (string-append root "/gerbil.pkg")
                    "(package: sample/build-scope)\n")
        (write-text (string-append root "/build.ss")
                    ";;; -*- Gerbil -*-\n(defbuild-script '(\"lib/foo/core\"))\n")
        (write-text (string-append owner "/facade.ss")
                    ";;; -*- Gerbil -*-\n;;; Foo facade.\n(export answer)\n(def answer 42)\n")
        (write-text (string-append owner "/core.ss")
                    ";;; -*- Gerbil -*-\n;;; Foo core.\n(def core-answer 42)\n")
        (let* ((index (collect-project root))
               (findings (run-modularity-policy index))
               (matching (filter-rule "GERBIL-SCHEME-MOD-R001" findings))
               (finding (car matching)))
          (check (length matching) => 1)
          (check (type-finding-path finding) => "lib/foo/facade.ss"))))
    (test-case "modularity policy rejects sibling file and owner directory"
      (let* ((root ".run/policy-owner-collision")
             (_ (write-policy-project
                 root "foo"
                 ";;; -*- Gerbil -*-\n;;; Foo sibling entry.\n(export answer)\n"
                 ";;; -*- Gerbil -*-\n;;; Foo core.\n(def core-answer 42)\n"))
             (index (collect-project root))
             (findings (run-modularity-policy index))
             (matching (filter-rule "GERBIL-SCHEME-MOD-R003" findings))
             (finding (car matching)))
        (check (length matching) => 1)
        (check (type-finding-rule-id finding)
               => "GERBIL-SCHEME-MOD-R003")
        (check (type-finding-path finding) => "src/foo.ss")))
    (test-case "modularity policy rejects repeated owner entry names"
      (let* ((root ".run/policy-repeated-owner-entry")
             (_ (write-owner-entry-policy-project
                 root "foo"
                 ";;; -*- Gerbil -*-\n;;; Foo repeated entry.\n(export answer)\n"
                 ";;; -*- Gerbil -*-\n;;; Foo core.\n(def core-answer 42)\n"))
             (index (collect-project root))
             (findings (run-modularity-policy index))
             (matching (filter-rule "GERBIL-SCHEME-MOD-R004" findings))
             (finding (car matching)))
        (check (length matching) => 1)
        (check (type-finding-rule-id finding)
               => "GERBIL-SCHEME-MOD-R004")
        (check (type-finding-path finding) => "src/foo/foo.ss")))
    (test-case "modularity policy rejects bin entrypoint implementation"
      (let* ((root ".run/policy-bin-entrypoint")
             (_ (write-bin-entrypoint-project
                 root ";;; -*- Gerbil -*-\n(import :std/cli/getopt)\n(def (main . args) args)\n"))
             (index (collect-project root))
             (findings (run-modularity-policy index))
             (matching (filter-rule "GERBIL-SCHEME-MOD-R005" findings))
             (finding (car matching)))
        (check (length matching) => 1)
        (check (type-finding-rule-id finding)
               => "GERBIL-SCHEME-MOD-R005")
        (check (type-finding-path finding) => "bin/run.ss")))
    (test-case "modularity policy rejects legacy test directory layout"
      (let* ((root ".run/policy-test-directory-layout")
             (_ (write-test-directory-layout-project root))
             (index (collect-project root))
             (findings (run-modularity-policy index))
             (matching (filter-rule "GERBIL-SCHEME-MOD-R006" findings)))
        (check (length matching) => 2)
        (check (map type-finding-path matching)
               => ["test/bad-test.ss" "tests/bad-tests-test.ss"])
        (check (type-finding-message (car matching))
               => "Gerbil unit test owner test/bad-test.ss uses non-t test/ layout; use t/ unless gerbil.pkg policy explicitly allows this directory with a clear explanation (no policy override)")))
    (test-case "modularity policy allows non-t test directories only with clear package policy"
      (let* ((root ".run/policy-test-directory-layout-allowed")
             (_ (write-test-directory-layout-project
                 root
                 ";;; -*- Gerbil -*-\n(package: sample\n  policy: ((test-directory-layout allowed-directories: (\"test\" \"tests\") explanation: \"This downstream conformance fixture mirrors upstream test directories that cannot be moved into t/ during replay.\")))\n"))
             (index (collect-project root))
             (findings (run-modularity-policy index))
             (matching (filter-rule "GERBIL-SCHEME-MOD-R006" findings)))
        (check matching => [])))
    (test-case "modularity policy rejects non-t test directory override without clear explanation"
      (let* ((root ".run/policy-test-directory-layout-short-explanation")
             (_ (write-test-directory-layout-project
                 root
                 ";;; -*- Gerbil -*-\n(package: sample\n  policy: ((test-directory-layout allowed-directories: (\"test\" \"tests\") explanation: \"temporary\")))\n"))
             (index (collect-project root))
             (findings (run-modularity-policy index))
             (matching (filter-rule "GERBIL-SCHEME-MOD-R006" findings)))
        (check (length matching) => 2)
        (check (type-finding-message (car matching))
               => "Gerbil unit test owner test/bad-test.ss uses non-t test/ layout; use t/ unless gerbil.pkg policy explicitly allows this directory with a clear explanation (policy override is missing a clear explanation)")))
    (test-case "agent policy requires facade intent comment"
      (let* ((root ".run/policy-agent")
             (_ (write-facade-policy-project
                 root "bar"
                 ";;; -*- Gerbil -*-\n(export value)\n"
                 ";;; -*- Gerbil -*-\n;;; Bar core.\n(def value 1)\n"))
             (index (collect-project root))
             (findings (run-agent-policy index))
             (matching (filter-rule "GERBIL-SCHEME-AGENT-R001" findings))
             (finding (car matching)))
        (check (length matching) => 1)
        (check (type-finding-rule-id finding)
               => "GERBIL-SCHEME-AGENT-R001")
        (check (type-finding-path finding) => "src/bar/facade.ss")))
    (test-case "modularity policy rejects oversized source leaves"
      (let* ((root ".run/policy-source-leaf")
             (_ (write-large-policy-source root "large"))
             (index (collect-project root))
             (findings (run-modularity-policy index))
             (matching (filter-rule "GERBIL-SCHEME-MOD-R002" findings))
             (finding (car matching)))
        (check (length matching) => 1)
        (check (type-finding-rule-id finding)
               => "GERBIL-SCHEME-MOD-R002")
        (check (type-finding-path finding) => "src/large/core.ss")))
    (test-case "agent policy rejects generic owner names"
      (let* ((root ".run/policy-generic-owner")
             (_ (write-facade-policy-project
                 root "utils"
                 ";;; -*- Gerbil -*-\n;;; Utilities facade.\n(export value)\n"
                 ";;; -*- Gerbil -*-\n;;; Utilities core.\n(def value 1)\n"))
             (index (collect-project root))
             (findings (run-agent-policy index))
             (matching (filter-rule "GERBIL-SCHEME-AGENT-R002" findings))
             (finding (car matching)))
        (check (length matching) => 2)
        (check (type-finding-rule-id finding)
               => "GERBIL-SCHEME-AGENT-R002")
        (check (not (not (member "src/utils/facade.ss"
                                  (map type-finding-path matching))))
               => #t)))
    (test-case "agent policy rejects vague definition names"
      (let* ((root ".run/policy-vague-definition")
             (_ (write-vague-definition-project root))
             (index (collect-project root))
             (findings (run-agent-policy index))
             (matching (filter-rule "GERBIL-SCHEME-AGENT-R004" findings))
             (finding (car matching)))
        (check (length matching) => 1)
        (check (type-finding-rule-id finding)
               => "GERBIL-SCHEME-AGENT-R004")
        (check (type-finding-path finding) => "src/orders/core.ss")
        (check (type-finding-selector finding) => "src/orders/core.ss:3-3")))
    (test-case "package agent-policy disables selected rules"
      (let* ((root ".run/policy-agent-disabled-rule")
             (src (string-append root "/src"))
             (owner (string-append src "/orders")))
        (ensure-dir ".run")
        (ensure-dir root)
        (ensure-dir src)
        (ensure-dir owner)
        (write-text (string-append root "/gerbil.pkg")
                    "(package: sample/orders\n  policy: ((agent-policy disabled-rules: (\"GERBIL-SCHEME-AGENT-R004\"))))\n")
        (write-text (string-append owner "/core.ss")
                    ";;; -*- Gerbil -*-\n(package: sample/orders)\n(def (process order) order)\n")
        (let* ((index (collect-project root))
               (findings (run-policy-checks index))
               (matching (filter-rule "GERBIL-SCHEME-AGENT-R004" findings)))
          (check matching => []))))
    (test-case "typed-combinator-style policy is enabled by default"
      (let* ((root ".run/policy-typed-combinator-style-default")
             (src (string-append root "/src"))
             (owner (string-append src "/orders")))
        (ensure-dir ".run")
        (ensure-dir root)
        (ensure-dir src)
        (ensure-dir owner)
        (write-text (string-append root "/gerbil.pkg")
                    "(package: sample/orders)\n")
        (write-text (string-append owner "/core.ss")
                    ";;; -*- Gerbil -*-\n(package: sample/orders)\n(def (order-total order) order)\n")
        (let* ((index (collect-project root))
               (findings (run-policy-checks index))
               (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings))
               (finding (car matching)))
          (check (length matching) => 1)
          (check (type-finding-severity finding) => "warning")
          (check (type-finding-path finding) => "src/orders/core.ss")
          (check (type-finding-selector finding) => "src/orders/core.ss")
          (check (hash-get (type-finding-details finding) 'styleGuide)
                 => "typed-combinator-style")
          (check (hash-get (type-finding-details finding) 'expectedCommentShape)
                 => "adjacent contract block such as ;; (Z <- YY) <- (Z <- XX YY) XX")
          (check (hash-get (type-finding-details finding) 'signatureShape)
                 => "adjacent Haskell-like transform signature block, one or more lines, no inline function name")
          (check (hash-get (type-finding-details finding) 'contractLinePolicy)
                 => "multi-line typed-combinator-style contracts are allowed when needed to preserve precision")
          (check (hash-get (type-finding-details finding) 'compositionShape)
                 => "compact expression-level helper or combinator chain; prefer map/filter/fold/cut/curry/compose when behavior fits")
          (check (hash-get (type-finding-details finding) 'qualityReference)
                 => "gerbil-utils")
          (check (hash-get (type-finding-details finding) 'functionShape)
                 => "single-purpose expression-returning helper; one visible data-flow shape per function")
          (check (hash-get (type-finding-details finding) 'expressionLevelRewrite)
                 => "extract predicate/mapper/reducer helpers, then compose with filter-map/map/fold/andmap/ormap/cut/curry/compose when behavior fits")
          (check (hash-get (type-finding-details finding) 'optimizationBoundary)
                 => "when using case-lambda or a specialized branch, comment why that branch exists and keep the comment about the boundary, not the code mechanics"))))
    (test-case "typed-combinator-style policy rejects partial definition coverage"
      (let* ((root ".run/policy-typed-combinator-style-partial")
             (src (string-append root "/src"))
             (owner (string-append src "/orders")))
        (ensure-dir ".run")
        (ensure-dir root)
        (ensure-dir src)
        (ensure-dir owner)
        (write-text (string-append root "/gerbil.pkg")
                    "(package: sample/orders)\n")
        (write-text (string-append owner "/core.ss")
                    ";;; -*- Gerbil -*-\n(package: sample/orders)\n;; Order <- Order\n(def (order-total order) order)\n(def (order-tax order) order)\n")
        (let* ((index (collect-project root))
               (findings (run-policy-checks index))
               (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings))
               (finding (car matching))
               (details (type-finding-details finding)))
          (check (length matching) => 1)
        (check (hash-get details 'definitionCount) => 2)
        (check (hash-get details 'typedCommentCount) => 1)
        (check (hash-get details 'missingTypedCommentCount) => 1)
        (check (hash-get details 'qualityReference) => "gerbil-utils")
        (check (hash-get details 'agentRepairStandard)
               => "rewrite toward gerbil-utils style: small algebraic helpers, dense but readable composition, minimal let*/mutation scaffolding"))))
    (test-case "typed-combinator-style policy accepts algebraic contracts"
      (let* ((root ".run/policy-typed-combinator-style-contract")
             (src (string-append root "/src"))
             (owner (string-append src "/orders")))
        (ensure-dir ".run")
        (ensure-dir root)
        (ensure-dir src)
        (ensure-dir owner)
        (write-text (string-append root "/gerbil.pkg")
                    "(package: sample/orders)\n")
        (write-text (string-append owner "/core.ss")
                    ";;; -*- Gerbil -*-\n(package: sample/orders)\n;; Money <- Order\n(def (order-total order) order)\n;; (List Money) <- (List Order)\n(def (order-totals orders) (map order-total orders))\n")
        (let* ((index (collect-project root))
               (findings (run-policy-checks index))
               (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings)))
          (check matching => []))))
    (test-case "typed-combinator-style policy rejects sparse implementation coverage"
      (let* ((root ".run/policy-typed-combinator-style-sparse-coverage")
             (src (string-append root "/src"))
             (owner (string-append src "/orders")))
        (ensure-dir ".run")
        (ensure-dir root)
        (ensure-dir src)
        (ensure-dir owner)
        (write-text (string-append root "/gerbil.pkg")
                    "(package: sample/orders)\n")
        (write-text (string-append owner "/core.ss")
                    ";;; -*- Gerbil -*-\n(package: sample/orders)\n;; Money <- Order\n(def (order-total order) order)\n;; Tax <- Order\n(def (order-tax order) order)\n;; (List Money) <- (List Order)\n(def (order-totals orders) (map order-total orders))\n;; Money <- Order\n(def (order-net order) order)\n")
        (let* ((index (collect-project root))
               (findings (run-policy-checks index))
               (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings))
               (finding (car matching))
               (details (type-finding-details finding)))
          (check (length matching) => 1)
          (check (hash-get details 'missingImplementationEvidence) => #f)
          (check (hash-get details 'implementationCoverageInsufficient) => #t)
          (check (hash-get details 'functionDefinitionCount) => 4)
          (check (hash-get details 'coveredDefinitionCount) => 1)
          (check (hash-get details 'minimumCoveredDefinitionCount) => 2)
          (check (hash-get details 'uncoveredDefinitionCount) => 3)
          (check (not (not (member "order-net"
                                   (hash-get details 'uncoveredDefinitions))))
                 => #t)
          (check (not (not (member "expression-level-composition"
                                   (hash-get details 'qualityFacets))))
                 => #t)
          (check (not (not (member "prefer map/filter/filter-map/fold pipelines; extract predicate, mapper, or reducer helpers before rewriting loops"
                                   (hash-get details 'qualityFacetSteering))))
                 => #t))))
    (test-case "typed-combinator-style policy keeps native quality facets as advice"
      (let* ((root ".run/policy-typed-combinator-style-native-facets")
             (src (string-append root "/src"))
             (owner (string-append src "/orders")))
        (ensure-dir ".run")
        (ensure-dir root)
        (ensure-dir src)
        (ensure-dir owner)
        (write-text (string-append root "/gerbil.pkg")
                    "(package: sample/orders)\n")
        (write-text (string-append owner "/core.ss")
                    ";;; -*- Gerbil -*-\n(package: sample/orders)\n;; Integer <- (List Number)\n(def (order-total xs)\n  (let loop ((rest xs) (acc 0))\n    (if (null? rest) acc (loop (cdr rest) (+ acc (car rest))))))\n")
        (let* ((index (collect-project root))
               (findings (run-policy-checks index))
               (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings))
               (fact (car (project-typed-contract-facts index)))
               (quality-facets (typed-contract-fact-quality-facets fact))
               (repair-evidence (typed-contract-fact-repair-evidence fact)))
          (check matching => [])
          (check (not (not (member "manual-loop-drift"
                                   quality-facets)))
                 => #t)
          (check (not (not (member "combinator-candidate"
                                   quality-facets)))
                 => #t)
          (check (hash-get repair-evidence 'factSource) => "native-parser")
          (check (not (not (member "replace-manual-loop-with-higher-order-combinator-when-no-state-witness"
                                   (hash-get repair-evidence 'allowedMoves))))
                 => #t))))
    (test-case "comment-quality policy rejects contract-only engineering comments"
      (let* ((root ".run/policy-comment-quality-contract-only")
             (src (string-append root "/src"))
             (owner (string-append src "/orders")))
        (ensure-dir ".run")
        (ensure-dir root)
        (ensure-dir src)
        (ensure-dir owner)
        (write-text (string-append root "/gerbil.pkg")
                    "(package: sample/orders)\n")
        (write-text (string-append owner "/core.ss")
                    ";;; -*- Gerbil -*-\n;;; Fixture has module intent so only definition comment quality is tested.\n(package: sample/orders)\n;; Money <- Order\n(def (order-total order) order)\n;; (List Money) <- (List Order)\n(def (order-totals orders) (map order-total orders))\n")
        (let* ((index (collect-project root))
               (findings (run-policy-checks index))
               (matching (filter-rule "GERBIL-SCHEME-AGENT-R015" findings))
               (finding (car matching))
               (details (type-finding-details finding))
               (example (car (hash-get details 'weakCommentExamples)))
               (parser-evidence (hash-get example 'parserEvidence))
               (matched-fact (car (hash-get parser-evidence 'matchedFacts)))
               (repair (finding-agent-repair-json finding)))
          (check (length matching) => 1)
          (check (hash-get details 'weakCommentCount) => 1)
          (check (hash-get details 'evidenceSource)
                 => "parser-owned commentQualityFacts.evidence")
          (check (hash-get details 'repairInstruction)
                 => "write adjacent engineering comment lines when parserEvidence needs them; concise prose, bullets, or Boundary/Invariant/Intent labels are all valid")
          (check (hash-get example 'target) => "order-totals")
          (check (hash-get example 'quality) => "weak")
          (check (hash-get example 'commentKind) => "contract-only")
          (check (hash-get parser-evidence 'definition) => "order-totals")
          (check (hash-get parser-evidence 'context) => "higher-order")
          (check (hash-get parser-evidence 'matchedFactCount) => 1)
          (check (hash-get matched-fact 'factKind) => "higher-order")
          (check (hash-get matched-fact 'role) => "sequence-map")
          (check (hash-get details 'typedContractBoundary)
                 => "typed contract comments describe algebraic shape only and may use adjacent multi-line contract blocks when needed")
          (check (hash-get repair 'nextCommand)
                 => "asp gerbil-scheme guide --code --rule GERBIL-SCHEME-AGENT-R015 --intent style"))))
    (test-case "comment-quality policy rejects compressed engineering comments"
      (let* ((root ".run/policy-comment-quality-compressed")
             (src (string-append root "/src"))
             (owner (string-append src "/orders")))
        (ensure-dir ".run")
        (ensure-dir root)
        (ensure-dir src)
        (ensure-dir owner)
        (write-text (string-append root "/gerbil.pkg")
                    "(package: sample/orders)\n")
        (write-text (string-append owner "/core.ss")
                    ";;; -*- Gerbil -*-\n;;; Boundary:\n;;; - Fixture owns the comment-quality compression scenario.\n(package: sample/orders)\n;;; Boundary: order-totals maps order-total across orders; keep higher-order data-flow visible.\n;; (List Money) <- (List Order)\n(def (order-totals orders) (map order-total orders))\n")
        (let* ((index (collect-project root))
               (findings (run-policy-checks index))
               (matching (filter-rule "GERBIL-SCHEME-AGENT-R015" findings))
               (finding (car matching))
               (details (type-finding-details finding))
               (example (car (hash-get details 'weakCommentExamples))))
          (check (length matching) => 1)
          (check (hash-get example 'target) => "order-totals")
          (check (hash-get example 'commentKind) => "compressed-engineering")
          (check (hash-get example 'quality) => "weak")
          (check (hash-get example 'reasons)
                 => ["compressed-engineering-comment-needs-adjacent-lines"])
          (check (hash-get details 'commentLinePolicy)
                 => "split multi-clause engineering rationale across adjacent comment lines when it improves confidence; do not squeeze rationale clauses into one semicolon-separated line"))))
    (test-case "typed-combinator-style policy rejects typed contracts without implementation evidence"
      (let* ((root ".run/policy-typed-combinator-style-no-implementation-evidence")
             (src (string-append root "/src"))
             (owner (string-append src "/orders")))
        (ensure-dir ".run")
        (ensure-dir root)
        (ensure-dir src)
        (ensure-dir owner)
        (write-text (string-append root "/gerbil.pkg")
                    "(package: sample/orders)\n")
        (write-text (string-append owner "/core.ss")
                    ";;; -*- Gerbil -*-\n(package: sample/orders)\n;; Money <- Order\n(def (order-total order) order)\n;; Tax <- Order\n(def (order-tax order) order)\n")
        (let* ((index (collect-project root))
               (findings (run-policy-checks index))
               (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings))
               (finding (car matching))
               (details (type-finding-details finding)))
          (check (length matching) => 1)
          (check (hash-get details 'typedCommentCount) => 2)
          (check (hash-get details 'missingTypedCommentCount) => 0)
          (check (hash-get details 'implementationEvidenceCount) => 0)
          (check (hash-get details 'missingImplementationEvidence) => #t)
          (check (hash-get details 'passiveRepairFlow)
                 => "policy-finding -> agentRepair -> guide-code -> bounded edit")
          (check (hash-get details 'implementationEvidenceSource)
                 => "parser-owned higherOrderFacts plus callFacts; do not use raw text heuristics"))))
    (test-case "typed-combinator-style policy rejects Any contracts"
      (let* ((root ".run/policy-typed-combinator-style-any")
             (src (string-append root "/src"))
             (owner (string-append src "/orders")))
        (ensure-dir ".run")
        (ensure-dir root)
        (ensure-dir src)
        (ensure-dir owner)
        (write-text (string-append root "/gerbil.pkg")
                    "(package: sample/orders)\n")
        (write-text (string-append owner "/core.ss")
                    ";;; -*- Gerbil -*-\n(package: sample/orders)\n;; Any <- Any\n(def (order-total order) order)\n")
        (let* ((index (collect-project root))
               (findings (run-policy-checks index))
               (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings))
               (finding (car matching))
               (details (type-finding-details finding)))
          (check (length matching) => 1)
          (check (hash-get details 'definitionCount) => 1)
          (check (hash-get details 'typedCommentCount) => 0)
          (check (hash-get details 'validTypedContractCount) => 0)
          (check (hash-get details 'invalidTypedContractCount) => 1)
          (check (hash-get details 'missingTypedCommentCount) => 1))))
    (test-case "typed-combinator-style policy rejects placeholder contracts"
      (let* ((root ".run/policy-typed-combinator-style-placeholder")
             (src (string-append root "/src"))
             (owner (string-append src "/orders")))
        (ensure-dir ".run")
        (ensure-dir root)
        (ensure-dir src)
        (ensure-dir owner)
        (write-text (string-append root "/gerbil.pkg")
                    "(package: sample/orders)\n")
        (write-text (string-append owner "/core.ss")
                    ";;; -*- Gerbil -*-\n(package: sample/orders)\n;; (List XX) <- Fact Value\n(def (order-total order) order)\n")
        (let* ((index (collect-project root))
               (findings (run-policy-checks index))
               (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings))
               (finding (car matching))
               (details (type-finding-details finding)))
          (check (length matching) => 1)
          (check (hash-get details 'typedCommentCount) => 0)
          (check (hash-get details 'invalidTypedContractCount) => 1)
          (check (hash-get details 'missingTypedCommentCount) => 1)
          (check (hash-get details 'invalidReason)
                 => "typed-combinator-style comments must be parser-owned adjacent algebraic transform signatures; see invalidTypedContractReasons for exact parser reasons")
          (check (hash-get details 'invalidTypedContractReasons)
                 => ["placeholder-contract-without-domain-or-higher-order-shape"])
          (check (hash-get (car (hash-get details 'invalidTypedContractExamples))
                           'contract)
                 => "(List XX) <- Fact Value")
          (check (hash-get (car (hash-get details 'invalidTypedContractExamples))
                           'quality)
                 => "invalid"))))
    (test-case "typed-combinator-style policy rejects inline function names"
      (let* ((root ".run/policy-typed-combinator-style-inline-name")
             (src (string-append root "/src"))
             (owner (string-append src "/orders")))
        (ensure-dir ".run")
        (ensure-dir root)
        (ensure-dir src)
        (ensure-dir owner)
        (write-text (string-append root "/gerbil.pkg")
                    "(package: sample/orders)\n")
        (write-text (string-append owner "/core.ss")
                    ";;; -*- Gerbil -*-\n(package: sample/orders)\n;; Money <- Order ; order-total\n(def (order-total order) order)\n")
        (let* ((index (collect-project root))
               (findings (run-policy-checks index))
               (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings))
               (finding (car matching))
               (details (type-finding-details finding)))
          (check (length matching) => 1)
          (check (hash-get details 'typedCommentCount) => 0)
          (check (hash-get details 'invalidTypedContractCount) => 1)
          (check (hash-get details 'missingTypedCommentCount) => 1))))
    (test-case "typed-combinator-style policy rejects detached ledger contracts"
      (let* ((root ".run/policy-typed-combinator-style-ledger")
             (src (string-append root "/src"))
             (owner (string-append src "/orders")))
        (ensure-dir ".run")
        (ensure-dir root)
        (ensure-dir src)
        (ensure-dir owner)
        (write-text (string-append root "/gerbil.pkg")
                    "(package: sample/orders)\n")
        (write-text (string-append owner "/core.ss")
                    ";;; -*- Gerbil -*-\n(package: sample/orders)\n(def (order-total order) order)\n\n;;; typed-combinator-style ledger\n;; Money <- Order\n")
        (let* ((index (collect-project root))
               (findings (run-policy-checks index))
               (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings))
               (finding (car matching))
               (details (type-finding-details finding)))
          (check (length matching) => 1)
          (check (hash-get details 'typedCommentCount) => 0)
          (check (hash-get details 'missingTypedCommentCount) => 1)
          (check (hash-get details 'adjacency) => "definition-leading-comment"))))
    (test-case "typed-combinator-style policy covers t scheme owners"
      (let* ((root ".run/policy-typed-combinator-style-test-owner")
             (test-dir (string-append root "/t")))
        (ensure-dir ".run")
        (ensure-dir root)
        (ensure-dir test-dir)
        (write-text (string-append root "/gerbil.pkg")
                    "(package: sample/orders)\n")
        (write-text (string-append test-dir "/orders-test.ss")
                    ";;; -*- Gerbil -*-\n(import :std/test)\n(def (order-fixture order) order)\n")
        (let* ((index (collect-project root))
               (findings (run-policy-checks index))
               (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings))
               (finding (car matching)))
          (check (length matching) => 1)
          (check (type-finding-path finding) => "t/orders-test.ss")
          (check (hash-get (type-finding-details finding) 'scope)
                 => "source-or-test-owner"))))
    (test-case "typed-combinator-style policy can be disabled by package config"
      (let* ((root ".run/policy-typed-combinator-style-disabled")
             (src (string-append root "/src"))
             (owner (string-append src "/orders")))
        (ensure-dir ".run")
        (ensure-dir root)
        (ensure-dir src)
        (ensure-dir owner)
        (write-text (string-append root "/gerbil.pkg")
                    "(package: sample/orders\n  policy: ((agent-policy disabled-rules: (\"GERBIL-SCHEME-AGENT-R013\"))))\n")
        (write-text (string-append owner "/core.ss")
                    ";;; -*- Gerbil -*-\n(package: sample/orders)\n(def (order-total order) order)\n")
        (let* ((index (collect-project root))
               (findings (run-policy-checks index))
               (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings)))
          (check matching => []))))
    (test-case "agent policy rejects top-level executable calls in src"
      (let* ((root ".run/policy-top-level-executable")
             (_ (write-top-level-executable-project root))
             (index (collect-project root))
             (findings (run-agent-policy index))
             (matching (filter-rule "GERBIL-SCHEME-AGENT-R005" findings))
             (finding (car matching)))
        (check (length matching) => 1)
        (check (type-finding-rule-id finding)
               => "GERBIL-SCHEME-AGENT-R005")
        (check (type-finding-path finding) => "src/orders/core.ss")
        (check (type-finding-selector finding) => "src/orders/core.ss:3-3")
        (check (type-finding-message finding)
               => "top-level executable call displayln should move behind a named definition or explicit entrypoint")))
    (test-case "agent policy warns on manual loops that should use functional idioms"
      (let* ((root ".run/policy-functional-idiom")
             (_ (write-functional-idiom-project root))
             (index (collect-project root))
             (findings (run-agent-policy index))
             (matching (filter-rule "GERBIL-SCHEME-AGENT-R009" findings))
             (finding (car matching)))
        (check (length matching) => 1)
        (check (type-finding-severity finding) => "warning")
        (check (type-status matching) => "fail")
        (check (type-finding-path finding) => "src/orders/core.ss")
        (check (type-finding-selector finding) => "src/orders/core.ss:5-6")
        (check (not (not (string-contains
                          (type-finding-message finding)
                          "prefer for/fold, map/filter/filter-map/append-map")))
               => #t)
        (check (hash-get (type-finding-details finding) 'kind)
               => "named-let")
        (check (hash-get (type-finding-details finding) 'sequenceIdioms)
               => ["map" "filter" "filter-map" "append-map" "fold/foldl/foldr" "for/fold"])
        (check (hash-get (type-finding-details finding) 'predicateIdioms)
               => ["andmap/ormap" "every/any" "find/list-index"])
        (check (hash-get (type-finding-details finding) 'compositionIdioms)
               => ["cut/cute" "curry/rcurry" "compose/compose1"])
        (check (hash-get (type-finding-details finding) 'builderIdioms)
               => ["with-list-builder"])
        (check (hash-get (type-finding-details finding) 'styleGuide)
               => "typed-combinator-style")
        (check (hash-get (type-finding-details finding) 'styleCommand)
               => "asp gerbil-scheme guide --code --topic typed-combinator-style --intent style")
        (check (hash-get (type-finding-details finding) 'detectedControlContexts)
               => [])
        (check (hash-get (type-finding-details finding) 'keepNamedLetWhen)
               => "IO/stateful control flow, C3-style fixpoint selection, or generator/continuation driver")))
    (test-case "agent policy check output routes findings to guide code"
      (let* ((root ".run/policy-functional-idiom-check-output")
             (_ (write-functional-idiom-project root))
             (result (check-output [root]))
             (output (cdr result)))
        (check (car result) => 1)
        (check (not (not (string-contains
                          output
                          "|agent-repair-info status=active repairableFindings=3 repairableWarnings=3 repairableErrors=0 trigger=warning")))
               => #t)
        (check (not (not (string-contains
                          output
                          "|agent-repair rule=GERBIL-SCHEME-AGENT-R009 severity=warning repairable=true active=true trigger=warning")))
               => #t)
        (check (not (not (string-contains
                          output
                          "guideTopic=functional-data-transform")))
               => #t)
        (check (not (not (string-contains
                          output
                          "guideIntent=repair")))
               => #t)
        (check (not (not (string-contains
                          output
                          "nextCommand=asp gerbil-scheme guide --code --rule GERBIL-SCHEME-AGENT-R009 --intent repair")))
               => #t)
        (check (not (not (string-contains
                          output
                          "nextCommand=asp gerbil-scheme guide --code --rule GERBIL-SCHEME-AGENT-R015 --intent style")))
               => #t)
        (check (not (not (string-contains
                          output
                          "styleGuide=typed-combinator-style")))
               => #t)
        (check (not (not (string-contains
                          output
                          "styleCommand=asp gerbil-scheme guide --code --topic typed-combinator-style --intent style")))
               => #t)
        (check (not (not (string-contains
                          output
                          "qualityFacets=")))
               => #t)
        (check (not (not (string-contains
                          output
                          "qualityFacetSteering=")))
               => #t)))
    (test-case "agent policy check json exposes agent repair triggers"
      (let* ((root ".run/policy-functional-idiom-check-json")
             (_ (write-functional-idiom-project root))
             (result (check-output ["--json" root]))
             (packet (call-with-input-string (cdr result) read-json))
             (agent-repair (hash-get packet "agentRepair"))
             (finding (json-finding-by-rule
                       (hash-get packet "findings")
                       "GERBIL-SCHEME-AGENT-R009"))
             (comment-finding (json-finding-by-rule
                               (hash-get packet "findings")
                               "GERBIL-SCHEME-AGENT-R015"))
             (finding-repair (hash-get finding "agentRepair")))
        (check (car result) => 1)
        (check (hash-get agent-repair "status") => "active")
        (check (hash-get agent-repair "repairableFindings") => 3)
        (check (hash-get agent-repair "repairableWarnings") => 3)
        (check (hash-get agent-repair "repairableErrors") => 0)
        (check (hash-get agent-repair "trigger") => "warning")
        (check (hash-get finding-repair "repairable") => #t)
        (check (hash-get finding-repair "active") => #t)
        (check (hash-get finding-repair "trigger") => "warning")
        (check (hash-get finding-repair "guideTopic")
               => "functional-data-transform")
        (check (hash-get finding-repair "guideIntent") => "repair")
        (check (hash-get finding-repair "nextCommand")
               => "asp gerbil-scheme guide --code --rule GERBIL-SCHEME-AGENT-R009 --intent repair")
        (check (hash-get (hash-get comment-finding "agentRepair")
                         "nextCommand")
               => "asp gerbil-scheme guide --code --rule GERBIL-SCHEME-AGENT-R015 --intent style")))
    (test-case "check changed scope reports only changed-file policy findings"
      (let* ((root ".run/policy-check-changed-scope")
             (_ (write-check-changed-project root))
             (_ (initialize-git-fixture root))
             (_ (write-text (string-append root "/src/changed/core.ss")
                            ";;; -*- Gerbil -*-\n(package: sample/changed)\n(def (changed-value x) x)\n"))
             (result (check-output ["--changed" root]))
             (output (cdr result)))
        (check (car result) => 1)
        (check (not (not (string-contains output "scope=changed"))) => #t)
        (check (not (not (string-contains output "src/changed/core.ss"))) => #t)
        (check (not (string-contains output "src/stable/core.ss")) => #t)))
    (test-case "agent policy reports named-let preservation control contexts"
      (let* ((root ".run/policy-functional-idiom-control-context")
             (_ (write-functional-idiom-control-context-project root))
             (index (collect-project root))
             (findings (run-agent-policy index))
             (matching (filter-rule "GERBIL-SCHEME-AGENT-R009" findings))
             (finding (car matching))
             (contexts (hash-get (type-finding-details finding)
                                 'detectedControlContexts)))
        (check (length matching) => 1)
        (check (type-finding-severity finding) => "warning")
        (check (not (not (member "continuation-control" contexts))) => #t)
        (check (not (not (member "protected-control" contexts))) => #t)
        (check (not (not (member "protected-handler" contexts))) => #t)))
    (test-case "agent policy accepts explicit higher-order idiom"
      (let* ((root ".run/policy-functional-idiom-positive")
             (_ (write-functional-idiom-positive-project root))
             (index (collect-project root))
             (findings (run-agent-policy index))
             (matching (filter-rule "GERBIL-SCHEME-AGENT-R009" findings)))
        (check (length matching) => 0)))
    (test-case "agent policy keeps functional idiom suppression caller scoped"
      (let* ((root ".run/policy-functional-idiom-caller-scope")
             (_ (write-functional-idiom-caller-scope-project root))
             (index (collect-project root))
             (findings (run-agent-policy index))
             (matching (filter-rule "GERBIL-SCHEME-AGENT-R009" findings))
             (finding (car matching)))
        (check (length matching) => 1)
        (check (type-finding-selector finding) => "src/orders/core.ss:7-8")
        (check (hash-get (type-finding-details finding) 'caller)
               => "manual-total")))
    (test-case "agent policy preserves native reader loops"
      (let* ((root ".run/policy-functional-idiom-reader")
             (_ (write-functional-idiom-reader-project root))
             (index (collect-project root))
             (findings (run-agent-policy index))
             (matching (filter-rule "GERBIL-SCHEME-AGENT-R009" findings)))
        (check (length matching) => 0)))
    (test-case "agent policy reports repeated match branch shape before style repair"
      (let* ((root ".run/policy-controlled-branch-shape")
             (_ (write-controlled-branch-shape-project root))
             (index (collect-project root))
             (findings (run-agent-policy index))
             (matching (filter-rule "GERBIL-SCHEME-AGENT-R014" findings))
             (finding (car matching))
             (result (check-output [root]))
             (output (cdr result)))
        (check (length matching) => 1)
        (check (type-finding-path finding) => "src/orders/core.ss")
        (check (type-finding-selector finding) => "src/orders/core.ss:5-7")
        (check (hash-get (type-finding-details finding) 'styleGuide)
               => "controlled-branch-shape")
        (check (hash-get (type-finding-details finding) 'rewriteScope)
               => "same caller or extracted helper only")
        (check (hash-get (type-finding-details finding) 'qualityReference)
               => "gerbil-utils")
        (check (hash-get (type-finding-details finding) 'functionShape)
               => "small selector/predicate/helper first; keep match branches shallow and expression-returning")
        (check (hash-get (type-finding-details finding) 'expressionLevelRewrite)
               => "turn repeated match plus accumulator shape into a named predicate/mapper/reducer pipeline before changing behavior")
        (check (car result) => 1)
        (check (not (not (string-contains output "guideTopic=controlled-branch-shape"))) => #t)
        (check (not (not (string-contains output "nextCommand=asp gerbil-scheme guide --code --rule GERBIL-SCHEME-AGENT-R014 --intent style"))) => #t)))
    (test-case "agent policy reports match plus named-let selector shape before style repair"
      (let* ((root ".run/policy-controlled-branch-loop-shape")
             (_ (write-controlled-branch-loop-shape-project root))
             (index (collect-project root))
             (findings (run-agent-policy index))
             (matching (filter-rule "GERBIL-SCHEME-AGENT-R014" findings))
             (finding (car matching)))
        (check (length matching) => 1)
        (check (type-finding-path finding) => "src/orders/core.ss")
        (check (type-finding-selector finding) => "src/orders/core.ss:5-12")
        (check (hash-get (type-finding-details finding) 'shape)
               => "pattern-branch-with-manual-loop")
        (check (hash-get (type-finding-details finding) 'matchCount) => 1)
        (check (hash-get (type-finding-details finding) 'manualLoopCount) => 1)
        (check (not (not (string-contains
                          (type-finding-message finding)
                          "combines match state destructuring with a named-let loop")))
               => #t)))
    (test-case "agent policy rejects direct POO writeenv calls"
      (let* ((root ".run/policy-poo-direct-writeenv")
             (_ (write-poo-direct-writeenv-project root))
             (index (collect-project root))
             (findings (run-agent-policy index))
             (matching (filter-rule "GERBIL-SCHEME-AGENT-R006" findings))
             (finding (car matching)))
        (check (length matching) => 1)
        (check (type-finding-rule-id finding)
               => "GERBIL-SCHEME-AGENT-R006")
        (check (type-finding-path finding) => "src/orders/io.ss")
        (check (type-finding-message finding)
               => "direct writeenv calls bypass POO IO runtime-source evidence; query search runtime-source writeenv printer hook first")))
    (test-case "agent policy requires runtime-source witness for POO IO overrides"
      (let* ((root ".run/policy-poo-io-runtime-witness")
             (_ (write-poo-io-override-project root))
             (index (collect-project root))
             (findings (run-agent-policy index))
             (matching (filter-rule "GERBIL-SCHEME-AGENT-R007" findings))
             (finding (car matching)))
        (check (length matching) => 1)
        (check (type-finding-rule-id finding)
               => "GERBIL-SCHEME-AGENT-R007")
        (check (type-finding-path finding) => "src/orders/io.ss")
        (check (type-finding-message finding)
               => "POO IO method overrides in src/ need runtime-source-backed writeenv/printer-hook witness coverage before being treated as verified")))
    (test-case "agent policy requires POO method generic and class facts"
      (let* ((root ".run/policy-poo-method-shape")
             (_ (write-poo-method-shape-project root))
             (index (collect-project root))
             (findings (run-agent-policy index))
             (matching (filter-rule "GERBIL-SCHEME-AGENT-R008" findings))
             (finding (car matching)))
        (check (length matching) => 1)
        (check (type-finding-rule-id finding)
               => "GERBIL-SCHEME-AGENT-R008")
        (check (type-finding-path finding) => "src/orders/methods.ss")
        (check (type-finding-message finding)
               => "POO method order-discount is missing parser-owned defgeneric,defclass-or-defprotocol facts; query POO pattern evidence and add defgeneric/defclass/defprotocol structure before extending methods")))
    (test-case "agent policy requires macro runtime-source witness"
      (let* ((root ".run/policy-macro-runtime-source")
             (_ (write-macro-runtime-source-project root #f))
             (index (collect-project root))
             (findings (run-agent-policy index))
             (matching (filter-rule "GERBIL-SCHEME-AGENT-R011" findings))
             (finding (car matching)))
        (check (length matching) => 1)
        (check (type-finding-path finding) => "src/macros/core.ss")
        (check (hash-get (type-finding-details finding) 'next)
               => "search runtime-source macro sugar module-sugar")))
    (test-case "agent policy accepts macro runtime-source witness policy"
      (let* ((root ".run/policy-macro-runtime-source-allowed")
             (_ (write-macro-runtime-source-project root #t))
             (index (collect-project root))
             (findings (run-agent-policy index))
             (matching (filter-rule "GERBIL-SCHEME-AGENT-R011" findings)))
        (check matching => [])))
    (test-case "agent policy requires declared protocol evidence"
      (let* ((root ".run/policy-protocol-evidence")
             (_ (write-protocol-evidence-project root #f))
             (index (collect-project root))
             (findings (run-agent-policy index))
             (matching (filter-rule "GERBIL-SCHEME-AGENT-R012" findings))
             (finding (car matching)))
        (check (length matching) => 1)
        (check (type-finding-path finding) => "src/orders/protocol.ss")
        (check (hash-get (type-finding-details finding) 'next)
               => "search pattern poo protocol")))
    (test-case "agent policy accepts declared protocol evidence"
      (let* ((root ".run/policy-protocol-evidence-positive")
             (_ (write-protocol-evidence-project root #t))
             (index (collect-project root))
             (findings (run-agent-policy index))
             (matching (filter-rule "GERBIL-SCHEME-AGENT-R012" findings)))
        (check matching => [])))
    (test-case "agent policy catches downstream POO implementation drift"
      (let* ((root ".run/policy-downstream-poo-agent")
             (_ (write-downstream-poo-agent-project root))
             (index (collect-project root))
             (findings (run-agent-policy index))
             (vague (filter-rule "GERBIL-SCHEME-AGENT-R004" findings))
             (direct-writeenv (filter-rule "GERBIL-SCHEME-AGENT-R006" findings))
             (runtime-witness (filter-rule "GERBIL-SCHEME-AGENT-R007" findings))
             (method-shape (filter-rule "GERBIL-SCHEME-AGENT-R008" findings))
             (object-model (filter-rule "GERBIL-SCHEME-AGENT-R010" findings)))
        (check (length vague) => 1)
        (check (length direct-writeenv) => 1)
        (check (length runtime-witness) => 1)
        (check (length method-shape) => 1)
        (check (length object-model) => 1)
        (check (type-finding-path (car vague)) => "src/orders/core.ss")
        (check (type-finding-path (car direct-writeenv)) => "src/orders/io.ss")
        (check (type-finding-path (car runtime-witness)) => "src/orders/io.ss")
        (check (type-finding-path (car method-shape)) => "src/orders/io.ss")
        (check (type-finding-path (car object-model)) => "src/orders/core.ss")
        (check (type-finding-selector (car object-model)) => "src/orders/core.ss:4-4")))
    (test-case "agent policy accepts downstream POO pattern-guided implementation"
      (let* ((root ".run/policy-downstream-poo-agent-positive")
             (_ (write-downstream-poo-agent-positive-project root))
             (index (collect-project root))
             (findings (run-agent-policy index)))
        (check findings => [])))
    (test-case "agent policy rejects duplicate facade exports"
      (let* ((root ".run/policy-export-conflict")
             (_alpha (write-facade-policy-project
                      root "alpha"
                      ";;; -*- Gerbil -*-\n;;; Alpha facade.\n(export value)\n"
                      ";;; -*- Gerbil -*-\n;;; Alpha core.\n(def value 1)\n"))
             (_beta (write-facade-policy-project
                     root "beta"
                     ";;; -*- Gerbil -*-\n;;; Beta facade.\n(export value)\n"
                     ";;; -*- Gerbil -*-\n;;; Beta core.\n(def value 2)\n"))
             (index (collect-project root))
             (findings (run-agent-policy index))
             (matching (filter-rule "GERBIL-SCHEME-AGENT-R003" findings))
             (finding (car matching)))
        (check (length matching) => 1)
        (check (type-finding-rule-id finding)
               => "GERBIL-SCHEME-AGENT-R003")
        (check (type-finding-path finding) => "src/beta/facade.ss")))))
;; FilterRule <- RuleId (List XX)
(def (filter-rule rule-id findings)
  (filter (lambda (finding)
            (equal? (type-finding-rule-id finding) rule-id))
          findings))
;; Json <- (List TypeFinding) RuleId
(def (json-finding-by-rule findings rule-id)
  (cond
   ((null? findings) #f)
   ((equal? (hash-get (car findings) "ruleId") rule-id) (car findings))
   (else (json-finding-by-rule (cdr findings) rule-id))))
;; CheckOutput <- (List TypeFinding)
(def (check-output args)
  (let* ((status #f)
         (output
          (call-with-output-string
            (lambda (out)
              (parameterize ((current-output-port out))
                (set! status (check-main args)))))))
    (cons status output)))
;; Unit <- String FacadeName FacadeSource CoreSource
(def (write-policy-project root facade-name facade-source core-source)
  (let* ((src (string-append root "/src"))
         (owner (string-append src "/" facade-name))
         (facade-path (string-append src "/" facade-name ".ss"))
         (owner-entry-path (string-append owner "/" facade-name ".ss"))
         (core-path (string-append owner "/core.ss")))
    (ensure-dir ".run")
    (ensure-dir root)
    (ensure-dir src)
    (ensure-dir owner)
    (delete-file-if-exists owner-entry-path)
    (write-text facade-path facade-source)
    (write-text core-path core-source)))
;; Unit <- String OwnerName FacadeSource CoreSource
(def (write-owner-entry-policy-project root owner-name facade-source core-source)
  (let* ((src (string-append root "/src"))
         (owner (string-append src "/" owner-name))
         (sibling-path (string-append src "/" owner-name ".ss"))
         (facade-entry-path (string-append owner "/facade.ss"))
         (facade-path (string-append owner "/" owner-name ".ss"))
         (core-path (string-append owner "/core.ss")))
    (ensure-dir ".run")
    (ensure-dir root)
    (ensure-dir src)
    (ensure-dir owner)
    (delete-file-if-exists sibling-path)
    (delete-file-if-exists facade-entry-path)
    (write-text facade-path facade-source)
    (write-text core-path core-source)))
;; Unit <- String OwnerName FacadeSource CoreSource
(def (write-facade-policy-project root owner-name facade-source core-source)
  (let* ((src (string-append root "/src"))
         (owner (string-append src "/" owner-name))
         (sibling-path (string-append src "/" owner-name ".ss"))
         (repeated-entry-path (string-append owner "/" owner-name ".ss"))
         (facade-path (string-append owner "/facade.ss"))
         (core-path (string-append owner "/core.ss")))
    (ensure-dir ".run")
    (ensure-dir root)
    (ensure-dir src)
    (ensure-dir owner)
    (delete-file-if-exists sibling-path)
    (delete-file-if-exists repeated-entry-path)
    (write-text facade-path facade-source)
    (write-text core-path core-source)))
;; Unit <- String Source
(def (write-bin-entrypoint-project root source)
  (let* ((bin (string-append root "/bin"))
         (entrypoint-path (string-append bin "/run.ss")))
    (ensure-dir ".run")
    (ensure-dir root)
    (ensure-dir bin)
    (write-text entrypoint-path source)))
;; Unit <- String MaybePackageSource
(def (write-test-directory-layout-project root . maybe-package-source)
  (let ((legacy-test (string-append root "/test"))
        (legacy-tests (string-append root "/tests"))
        (native-test (string-append root "/t"))
        (package-path (string-append root "/gerbil.pkg")))
    (ensure-dir ".run")
    (ensure-dir root)
    (ensure-dir legacy-test)
    (ensure-dir legacy-tests)
    (ensure-dir native-test)
    (if (pair? maybe-package-source)
      (write-text package-path (car maybe-package-source))
      (delete-file-if-exists package-path))
    (write-text (string-append legacy-test "/bad-test.ss")
                ";;; -*- Gerbil -*-\n(import :std/test)\n(def bad-test (test-suite \"bad\"))\n")
    (write-text (string-append legacy-tests "/bad-tests-test.ss")
                ";;; -*- Gerbil -*-\n(import :std/test)\n(def bad-tests-test (test-suite \"bad tests\"))\n")
    (write-text (string-append native-test "/good-test.ss")
                ";;; -*- Gerbil -*-\n(import :std/test)\n(def good-test (test-suite \"good\"))\n")))
;; Unit <- String
(def (write-vague-definition-project root)
  (let* ((src (string-append root "/src"))
         (owner (string-append src "/orders")))
    (ensure-dir ".run")
    (ensure-dir root)
    (ensure-dir src)
    (ensure-dir owner)
    (write-text (string-append owner "/core.ss")
                ";;; -*- Gerbil -*-\n(package: sample/orders)\n(def (process order) order)\n(def (order-total order) order)\n")))
;; Unit <- String
(def (write-top-level-executable-project root)
  (let* ((src (string-append root "/src"))
         (owner (string-append src "/orders")))
    (ensure-dir ".run")
    (ensure-dir root)
    (ensure-dir src)
    (ensure-dir owner)
    (write-text (string-append owner "/core.ss")
                ";;; -*- Gerbil -*-\n(import :std/misc/ports)\n(displayln \"bad\")\n(def (named) #t)\n")))
;; String <- String
(def (write-functional-idiom-project root)
  (let* ((src (string-append root "/src"))
         (owner (string-append src "/orders")))
    (ensure-dir ".run")
    (ensure-dir root)
    (ensure-dir src)
    (ensure-dir owner)
    (write-text (string-append owner "/facade.ss")
                ";;; -*- Gerbil -*-\n;;; Orders facade intent.\n(export total)\n")
    (write-text (string-append owner "/core.ss")
                ";;; -*- Gerbil -*-\n(package: sample/orders)\n(export total)\n(def (total xs)\n  (let loop ((rest xs) (acc 0))\n    (if (null? rest) acc (loop (cdr rest) (+ acc (car rest))))))\n")))
;; String <- String
(def (write-functional-idiom-positive-project root)
  (let* ((src (string-append root "/src"))
         (owner (string-append src "/orders")))
    (ensure-dir ".run")
    (ensure-dir root)
    (ensure-dir src)
    (ensure-dir owner)
    (write-text (string-append owner "/facade.ss")
                ";;; -*- Gerbil -*-\n;;; Orders facade intent.\n(export total)\n")
    (write-text (string-append owner "/core.ss")
                ";;; -*- Gerbil -*-\n(package: sample/orders)\n(export total)\n(def (total xs)\n  (for/fold ((acc 0)) ((x xs)) (+ acc x)))\n")))
;; String <- String
(def (write-functional-idiom-caller-scope-project root)
  (let* ((src (string-append root "/src"))
         (owner (string-append src "/orders")))
    (ensure-dir ".run")
    (ensure-dir root)
    (ensure-dir src)
    (ensure-dir owner)
    (write-text (string-append owner "/facade.ss")
                ";;; -*- Gerbil -*-\n;;; Orders facade intent.\n(export total manual-total)\n")
    (write-text (string-append owner "/core.ss")
                ";;; -*- Gerbil -*-\n(package: sample/orders)\n(export total manual-total)\n(def (total xs)\n  (for/fold ((acc 0)) ((x xs)) (+ acc x)))\n(def (manual-total xs)\n  (let loop ((rest xs) (acc 0))\n    (if (null? rest) acc (loop (cdr rest) (+ acc (car rest))))))\n")))
;; String <- String
(def (write-functional-idiom-reader-project root)
  (let* ((src (string-append root "/src"))
         (owner (string-append src "/orders")))
    (ensure-dir ".run")
    (ensure-dir root)
    (ensure-dir src)
    (ensure-dir owner)
    (write-text (string-append owner "/facade.ss")
                ";;; -*- Gerbil -*-\n;;; Orders facade intent.\n(export read-values)\n")
    (write-text (string-append owner "/core.ss")
                ";;; -*- Gerbil -*-\n(package: sample/orders)\n(import :std/misc/ports)\n(export read-values)\n(def (read-values port)\n  (let loop ((out '()))\n    (let (line (read-line port))\n      (if (eof-object? line) (reverse out) (loop (cons line out))))))\n")))
;; Unit <- String
(def (write-controlled-branch-shape-project root)
  (let* ((src (string-append root "/src"))
         (owner (string-append src "/orders")))
    (ensure-dir ".run")
    (ensure-dir root)
    (ensure-dir src)
    (ensure-dir owner)
    (write-text (string-append owner "/facade.ss")
                ";;; -*- Gerbil -*-\n;;; Orders facade intent.\n(export decode-order)\n")
    (write-text (string-append owner "/core.ss")
                ";;; -*- Gerbil -*-\n(package: sample/orders)\n(export decode-order)\n(def (decode-order event)\n  (match event\n    (['created id] id)\n    (else #f))\n  (match event\n    (['cancelled id] id)\n    (else #f)))\n")))
;; Unit <- String
(def (write-controlled-branch-loop-shape-project root)
  (let* ((src (string-append root "/src"))
         (owner (string-append src "/orders")))
    (ensure-dir ".run")
    (ensure-dir root)
    (ensure-dir src)
    (ensure-dir owner)
    (write-text (string-append owner "/facade.ss")
                ";;; -*- Gerbil -*-\n;;; Orders facade intent.\n(export select-orders)\n")
    (write-text (string-append owner "/core.ss")
                ";;; -*- Gerbil -*-\n(package: sample/orders)\n(export select-orders)\n(def (select-orders facts state)\n  (match state\n    ([seen out remaining]\n     (let lp ((rest facts) (seen seen) (out out) (remaining remaining))\n       (cond\n        ((or (null? rest) (<= remaining 0))\n         [seen out remaining])\n        (else\n         (lp (cdr rest) seen out remaining)))))))\n")))
;; Unit <- String
(def (write-check-changed-project root)
  (let* ((src (string-append root "/src"))
         (changed (string-append src "/changed"))
         (stable (string-append src "/stable")))
    (reset-fixture-root root)
    (ensure-dir ".run")
    (ensure-dir root)
    (ensure-dir src)
    (ensure-dir changed)
    (ensure-dir stable)
    (write-text (string-append changed "/core.ss")
                ";;; -*- Gerbil -*-\n(package: sample/changed)\n(def changed-value 1)\n")
    (write-text (string-append stable "/core.ss")
                ";;; -*- Gerbil -*-\n(package: sample/stable)\n(def stable-value 1)\n")))
;; InitializeGitFixture <- String
(def (initialize-git-fixture root)
  (run-git root ["init"])
  (run-git root ["config" "user.email" "gerbil-harness@example.invalid"])
  (run-git root ["config" "user.name" "Gerbil Harness Test"])
  (run-git root ["add" "."])
  (run-git root ["commit" "-m" "baseline"]))
;; RunGit <- String (List XX)
(def (run-git root args)
  (void
   (run-process (cons "git" args)
                directory: root
                stderr-redirection: #t)))
;; ResetFixtureRoot <- String
(def (reset-fixture-root root)
  (when (file-exists? root)
    (void
     (run-process ["rm" "-rf" root]
                  stderr-redirection: #t))))
;; String <- String
(def (write-functional-idiom-control-context-project root)
  (let* ((src (string-append root "/src"))
         (owner (string-append src "/orders")))
    (ensure-dir ".run")
    (ensure-dir root)
    (ensure-dir src)
    (ensure-dir owner)
    (write-text (string-append owner "/facade.ss")
                ";;; -*- Gerbil -*-\n;;; Orders facade intent.\n(export drain)\n")
    (write-text (string-append owner "/core.ss")
                ";;; -*- Gerbil -*-\n(package: sample/orders)\n(export drain)\n(def (drain xs)\n  (let/cc stop\n    (let loop ((rest xs))\n      (if (null? rest) (stop #f) (loop (cdr rest)))))\n  (try (void) (finally (void))))\n")))
;; Unit <- String Allowed
(def (write-macro-runtime-source-project root allowed?)
  (let* ((src (string-append root "/src"))
         (owner (string-append src "/macros")))
    (ensure-dir ".run")
    (ensure-dir root)
    (ensure-dir src)
    (ensure-dir owner)
    (if allowed?
      (write-text (string-append root "/gerbil.pkg")
                  "(package: sample/macros\n  policy: ((macro-governance allow-generated: #t explanation: \"Macro transformer edits are allowed only with runtime-source and expansion evidence.\" witness: \"search runtime-source macro sugar module-sugar\")))\n")
      (delete-file-if-exists (string-append root "/gerbil.pkg")))
    (write-text (string-append owner "/core.ss")
                ";;; -*- Gerbil -*-\n(package: sample/macros)\n(defsyntax (with-order stx)\n  #'(void))\n")))
;; String <- String Declared
(def (write-protocol-evidence-project root declared?)
  (let* ((src (string-append root "/src"))
         (owner (string-append src "/orders")))
    (ensure-dir ".run")
    (ensure-dir root)
    (ensure-dir src)
    (ensure-dir owner)
    (write-text (string-append owner "/protocol.ss")
                (string-append
                 ";;; -*- Gerbil -*-\n(package: sample/orders)\n(import :clan/poo/protocol)\n"
                 (if declared? "(defprotocol <Renderable>)\n" "")
                 "(defgeneric :render)\n"
                 "(defmethod (:render (value <Renderable>)) value)\n"))))
;; EnsureDir <- String
(def (ensure-dir path)
  (with-catch
   (lambda (_) #f)
   (lambda () (create-directory path))))
;; Unit <- String SourceLine
(def (write-text path text)
  (delete-file-if-exists path)
  (call-with-output-file path
    (lambda (port) (display text port))))
;; DeleteFileIfExists <- String
(def (delete-file-if-exists path)
  (with-catch
   (lambda (_) #f)
   (lambda () (delete-file path))))
;; Unit <- String OwnerName
(def (write-large-policy-source root owner-name)
  (let* ((src (string-append root "/src"))
         (owner (string-append src "/" owner-name))
         (source-path (string-append owner "/core.ss")))
    (ensure-dir ".run")
    (ensure-dir root)
    (ensure-dir src)
    (ensure-dir owner)
    (with-catch
     (lambda (_) #f)
     (lambda () (delete-file source-path)))
    (call-with-output-file source-path
      (lambda (port)
        (display ";;; -*- Gerbil -*-\n;;; Large source leaf.\n" port)
        (let lp ((index 0))
          (when (fx< index 45)
            (display "(def value" port)
            (display index port)
            (display " " port)
            (display index port)
            (display ")\n" port)
            (lp (fx1+ index))))
        (let lp ((index 0))
          (when (fx< index 610)
            (display ";; padding\n" port)
            (lp (fx1+ index))))))))
