;;; -*- Gerbil -*-
(import :std/test
        :parser/facade
        :types/facade)
(export types-test)

(def types-test
  (test-suite "gerbil scheme harness types"
    (test-case "reader errors become type pipeline findings"
      (let* ((root (path-normalize "."))
             (file (parse-source-file root "t/fixtures/invalid-read.fixture"))
             (findings (source-file-type-findings file))
             (finding (car findings)))
        (check (length findings) => 1)
        (check (type-finding-rule-id finding) => "GERBIL-SCHEME-READ-R001")
        (check (type-finding-severity finding) => "error")
        (check (type-finding-path finding) => "t/fixtures/invalid-read.fixture")))
    (test-case "type env is built from native parser facts"
      (let* ((root (path-normalize "."))
             (index (collect-project root))
             (sample-bindings
              (filter (lambda (binding)
                        (equal? (type-binding-path binding)
                                "t/fixtures/formals.ss"))
                      (build-type-env index))))
        (check (map type-binding-name sample-bindings)
               => ["sum-two" "collect"])
        (check (map type-binding-kind sample-bindings)
               => ["def" "def"])
        (check (map type->string (map type-binding-type sample-bindings))
               => ["unknown" "unknown"])
        (check (map type-binding-formals sample-bindings)
               => [["x" "y"] ["xs"]])
        (check (map type-binding-arity sample-bindings)
               => [2 1])))
    (test-case "signature types merge into native type env"
      (let* ((root (path-normalize "."))
             (index (collect-project root))
             (signatures (load-type-signatures "t/fixtures/type-signatures.scm"))
             (sample-bindings
              (filter (lambda (binding)
                        (equal? (type-binding-path binding)
                                "t/fixtures/formals.ss"))
                      (build-type-env/signatures index signatures))))
        (check (map type-binding-name sample-bindings)
               => ["sum-two" "collect"])
        (check (map type->string (map type-binding-type sample-bindings))
               => ["(function (number number) number)" "(function (any) any)"])))
    (test-case "signature parameter types build native param env"
      (let* ((root (path-normalize "."))
             (index (collect-project root))
             (signatures (load-type-signatures "t/fixtures/type-signatures.scm"))
             (param-bindings
              (filter (lambda (binding)
                        (equal? (type-param-binding-path binding)
                                "t/fixtures/formals.ss"))
                      (build-param-type-env/signatures index signatures))))
        (check (map type-param-binding-function-name param-bindings)
               => ["sum-two" "sum-two"])
        (check (map type-param-binding-name param-bindings)
               => ["x" "y"])
        (check (map type->string (map type-param-binding-type param-bindings))
               => ["number" "number"])))
    (test-case "signature parser supports structured native type forms"
      (let* ((signatures (load-type-signatures "t/fixtures/type-signatures.scm"))
             (pair-type (signature-type-for "pair-value" signatures))
             (numbers-type (signature-type-for "numbers" signatures))
             (names-type (signature-type-for "names" signatures))
             (union-type (signature-type-for "string-or-number" signatures))
             (node-type (signature-type-for "node" signatures))
             (rest-type (signature-type-for "rest-sum" signatures)))
        (check (type->string pair-type) => "(pair string number)")
        (check (type->string (type-pair-car pair-type)) => "string")
        (check (type->string (type-pair-cdr pair-type)) => "number")
        (check (type->string numbers-type) => "(list number)")
        (check (type->string (type-list-elem numbers-type)) => "number")
        (check (type->string names-type) => "(vector string)")
        (check (type->string (type-vector-elem names-type)) => "string")
        (check (type->string union-type) => "(union string number)")
        (check (map type->string (type-union-members union-type))
               => ["string" "number"])
        (check (type->string node-type)
               => "(record ((value number) (next (union null any))) (value))")
        (check (type-record-required node-type) => ["value"])
        (check (type->string (record-field-type node-type "next"))
               => "(union null any)")
        (check (type->string rest-type) => "(function* number number 1)")
        (check (type-kind rest-type) => 'function-variadic)
        (check (type-function-variadic-min-arity rest-type) => 1)))
    (test-case "duplicate definitions become type env facts"
      (let* ((first (make-type-binding "answer" "definition" (make-type-unknown)
                                       '() 0 "same.ss" "same.ss:1-1"))
             (second (make-type-binding "answer" "definition" (make-type-unknown)
                                        '() 0 "same.ss" "same.ss:2-2"))
             (duplicates (duplicate-type-bindings [first second]))
             (duplicate (car duplicates)))
        (check (length duplicates) => 1)
        (check (type-binding-selector (car duplicate)) => "same.ss:2-2")
        (check (type-binding-selector (cadr duplicate)) => "same.ss:1-1")))
    (test-case "same definition names in different owners are distinct"
      (let* ((first (make-type-binding "answer" "definition" (make-type-unknown)
                                       '() 0 "first.ss" "first.ss:1-1"))
             (second (make-type-binding "answer" "definition" (make-type-unknown)
                                        '() 0 "second.ss" "second.ss:2-2")))
        (check (duplicate-type-bindings [first second]) => '())))))
