(guide
 (lines
  ("gerbil-scheme-harness guide"
   "|cmd guide-code=gerbil-scheme-harness guide --code"
   "|cmd guide-code-topic=gerbil-scheme-harness guide --code --topic higher-order-control"
   "|cmd guide-code-more=gerbil-scheme-harness guide --code --topic higher-order-control --more"
   "|cmd guide-code-repair=gerbil-scheme-harness guide --code --rule GERBIL-SCHEME-AGENT-R009 --intent repair"
   "|cmd guide-code-poo-repair=gerbil-scheme-harness guide --code --topic poo-policy --intent repair"
   "|cmd guide-code-macro-witness=gerbil-scheme-harness guide --code --topic macro-runtime-source --intent witness"
   "|cmd guide-code-advanced=gerbil-scheme-harness guide --code --topic higher-order-control --level advanced"
   "|cmd prime=gerbil-scheme-harness search prime --view seeds ."
   "|cmd pipe=gerbil-scheme-harness search pipe '<term>' --view seeds ."
   "|cmd fzf=gerbil-scheme-harness search fzf '<term>' owner tests --view seeds ."
   "|cmd owner=gerbil-scheme-harness search owner <path> --view seeds ."
   "|cmd owner-items=gerbil-scheme-harness search owner <path> items --query <symbol> --names-only ."
   "|cmd query-code=gerbil-scheme-harness query --selector <path:start-end> --workspace . --code"
   "|cmd env=gerbil-scheme-harness search env [term ...] --view seeds ."
   "|cmd runtime-source=gerbil-scheme-harness search runtime-source [term ...] --view seeds ."
   "|cmd lang=gerbil-scheme-harness search lang [term ...] --view seeds ."
   "|cmd std=gerbil-scheme-harness search std [term ...] --view seeds ."
   "|cmd extension=gerbil-scheme-harness search extension <extension> [term ...] --view seeds ."
  "|cmd pattern=gerbil-scheme-harness search pattern <feature-or-extension> [term ...] --view seeds ."
  "|cmd compare=gerbil-scheme-harness search compare <axis> [left right] --view seeds ."
  "|cmd structural=gerbil-scheme-harness search structural --view seeds ."
  "|cmd structural-index-json=gerbil-scheme-harness search structural --json ."
  "|cmd evidence-graph=gerbil-scheme-harness evidence graph --json ."
  "|cmd evidence-analyze=gerbil-scheme-harness evidence analyze --json ."
  "|cmd info=gerbil-scheme-harness info --json ."
  "|cmd check=gerbil-scheme-harness check --changed ."
  "|cmd bench=gerbil-scheme-harness bench --json --iterations 1 --max-total-ms 60000 ."
  "|policy structural-json-boundary=use search structural --view seeds for bounded agent evidence; reserve --json for schema tests and artifact validation"
  "|policy configurable-interface=downstream gerbil.pkg policy may declare source-scope roots/runtime-roots/exclude-directories and agent-policy enabled-rules/disabled-rules; without explicit source-scope, build.ss defbuild-script targets provide runtime-root evidence"
  "|policy package-module-style=Gerbil package modules should preserve package:/namespace:/import/export style instead of flattening into generic Scheme files"
  "|policy gerbil-feature-use=when POO/protocol capability is active, prefer parser-owned defclass/defgeneric/defmethod evidence over raw hash/alist object constructors; cite search pattern poo class when intentionally staying raw"
  "|policy poo-method-shape=GERBIL-SCHEME-AGENT-R008 requires defmethod edits to have matching defgeneric plus defclass or defprotocol receiver evidence"
  "|policy macro-runtime-source-witness=GERBIL-SCHEME-AGENT-R011 requires macro edits to cite search runtime-source macro sugar module-sugar before changing transformers"
  "|policy protocol-evidence=GERBIL-SCHEME-AGENT-R012 requires protocol-oriented methods to cite parser-owned defprotocol/defclass evidence"
  "|policy functional-data-transform=GERBIL-SCHEME-AGENT-R009 steers pure data transforms toward map/filter/fold/for/fold/cut and keeps named let for IO/state/generator/continuation drivers"
  "|policy namespace-receipt=macro/module/type/poo edits should cite search env/lang/std/pattern/runtime-source output before editing"
  "|policy runtime-source-code-comments=runtime-source results should expose selectorResolver/sourceExample/sourceComment lines before selector code reads"
  "|guideExemplar id=gerbil.higher-order-control.filter-map topic=higher-order-control intent=study rule=GERBIL-SCHEME-AGENT-R009 level=normal selector=src/checker/arity.ss:1-19 commentSelector=src/checker/arity.ss:2-2 codeSelector=src/checker/arity.ss:14-19 nextCommand=\"gerbil-scheme-harness guide --code --topic higher-order-control\" moreCommand=\"gerbil-scheme-harness guide --code --topic higher-order-control --more\" advancedCommand=\"gerbil-scheme-harness guide --code --topic higher-order-control --level advanced\""
  "|guideExemplar id=gerbil.functional-data-transform.filter-map topic=functional-data-transform intent=repair rule=GERBIL-SCHEME-AGENT-R009 level=normal selector=src/checker/arity.ss:1-19 commentSelector=src/checker/arity.ss:2-2 codeSelector=src/checker/arity.ss:14-19 nextCommand=\"gerbil-scheme-harness guide --code --rule GERBIL-SCHEME-AGENT-R009 --intent repair\""
  "|guideExemplar id=gerbil.poo-policy.parser-facts topic=poo-policy intent=repair rule=GERBIL-SCHEME-AGENT-R008 level=normal selector=src/parser/poo.ss:1-35 commentSelector=src/parser/poo.ss:2-2 codeSelector=src/parser/poo.ss:15-35 nextCommand=\"gerbil-scheme-harness guide --code --topic poo-policy --intent repair\""
  "|guideExemplar id=gerbil.macro-runtime-source.witness topic=macro-runtime-source intent=witness rule=GERBIL-SCHEME-AGENT-R011 level=advanced selector=src/commands/search.ss:562-577 commentSelector=src/commands/search.ss:2-2 codeSelector=src/commands/search.ss:562-577 nextCommand=\"gerbil-scheme-harness guide --code --topic macro-runtime-source --intent witness\""
  "|policy guide-code-default=guide --code writes only extracted source comment plus source code; guide without --code carries selectors and next commands"
  "|policy guide-code-progressive=guide --code defaults to one source-backed excerpt; --more adds one adjacent exemplar; --level advanced includes the macro runtime-source witness path"
  "|policy guide-code-routing=--rule/--finding route known policy ids to source-backed exemplars before agent repair; --intent witness routes to macro runtime-source evidence"
  "|policy guide-workspace=guide does not require a positional .; use --workspace . only when project-local exemplar selection needs context"
  "|policy poo-io-runtime-source=POO :wr/writeenv changes should cite search runtime-source writeenv printer hook; hook guidance remains soft until real-project noise is reviewed")))
