;;; -*- Gerbil -*-
;;; Gerbil scheme harness agent style policy.

(import :gerbil/gambit
        :std/test
        :std/misc/ports
        :std/misc/process
        :commands/check
        :parser/facade
        :policy/facade
        :policy/gxtest
        :types/facade
        :unit/policy/poo-scenarios
        :policy/fixtures)
(export agent-style-policy-test)

;; PolicyTest
(def agent-style-typed-policy-test
  (test-suite "gerbil scheme harness typed style policy"
    (test-case "typed-combinator-style policy is enabled by default"
          (let* ((root ".run/policy-typed-combinator-style-default")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n(package: sample/orders)\n(def (order-total order) order)\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings))
                   (finding (car matching)))
              (check (length matching) => 1)
              (check (type-finding-severity finding) => "warning")
              (check (type-finding-path finding) => "src/orders/core.ss")
              (check (type-finding-selector finding) => "src/orders/core.ss")
              (check (hash-get (type-finding-details finding) 'styleGuide)
                     => "typed-combinator-style")
              (check (hash-get (type-finding-details finding) 'expectedCommentShape)
                     => "adjacent Scheme-native typed block such as ;; : (forall (a) (-> (-> a a Order) (List a) (List a) Order))")
              (check (hash-get (type-finding-details finding) 'signatureShape)
                     => "adjacent Scheme-native signature block using ;; : (-> Input Output), optional ;; | type aliases, and no inline function name")
              (check (hash-get (type-finding-details finding) 'contractLinePolicy)
                     => "multi-line typed-combinator-style contracts are allowed when needed to preserve precision")
              (check (hash-get (type-finding-details finding) 'compositionShape)
                     => "compact expression-level helper or combinator chain; prefer map/filter/fold/cut/curry/compose when behavior fits")
              (check (hash-get (type-finding-details finding) 'qualityReference)
                     => "gerbil-utils")
              (check (hash-get (type-finding-details finding) 'functionShape)
                     => "single-purpose expression-returning helper; one visible data-flow shape per function")
              (check (hash-get (type-finding-details finding) 'expressionLevelRewrite)
                     => "extract predicate/mapper/reducer helpers, then compose with filter-map/map/fold/andmap/ormap/cut/curry/compose when behavior fits")
              (check (hash-get (type-finding-details finding) 'optimizationBoundary)
                     => "when using case-lambda or a specialized branch, comment why that branch exists and keep the comment about the boundary, not the code mechanics"))))
    (test-case "typed-combinator-style policy rejects partial definition coverage"
          (let* ((root ".run/policy-typed-combinator-style-partial")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n(package: sample/orders)\n;; Order <- Order\n(def (order-total order) order)\n(def (order-tax order) order)\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings))
                   (finding (car matching))
                   (details (type-finding-details finding)))
              (check (length matching) => 1)
            (check (hash-get details 'definitionCount) => 2)
            (check (hash-get details 'typedCommentCount) => 1)
            (check (hash-get details 'missingTypedCommentCount) => 1)
            (check (hash-get details 'qualityReference) => "gerbil-utils")
            (check (hash-get details 'agentRepairStandard)
                   => "rewrite toward gerbil-utils style: small algebraic helpers, dense but readable composition, minimal let*/mutation scaffolding"))))
    (test-case "typed-combinator-style policy accepts algebraic contracts"
          (let* ((root ".run/policy-typed-combinator-style-contract")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n(package: sample/orders)\n;; : (-> Order Money)\n(def (order-total order) order)\n;; : (-> (List Order) (List Money))\n;; | type Money = Number\n(def (order-totals orders) (map order-total orders))\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings)))
              (check matching => []))))
    (test-case "typed-combinator-style policy rejects placeholder type variables"
          (let* ((root ".run/policy-typed-combinator-style-placeholder-token")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n(package: sample/orders)\n;; : (-> (List XX) Dedupe)\n(def (dedupe xs) xs)\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings))
                   (finding (car matching))
                   (details (type-finding-details finding))
                   (examples (hash-get details 'invalidTypedContractExamples))
                   (example (car examples)))
              (check (length matching) => 1)
              (check (hash-get details 'invalidTypedContractCount) => 1)
              (check (not (not (member "placeholder-type-variable-token"
                                       (hash-get details 'invalidTypedContractReasons))))
                     => #t)
              (check (hash-get example 'definition) => "dedupe"))))
    (test-case "typed-combinator-style keeps legacy typed contract migration passive by default"
          (let* ((root ".run/policy-typed-combinator-style-legacy-migration")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n(package: sample/orders)\n;; Money <- Order\n(def (order-total order) order)\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings)))
              (check matching => []))))
    (test-case "typed-combinator-style policy rejects sparse implementation coverage"
          (let* ((root ".run/policy-typed-combinator-style-sparse-coverage")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n(package: sample/orders)\n;; Money <- Order\n(def (order-total order) order)\n;; Tax <- Order\n(def (order-tax order) order)\n;; (List Money) <- (List Order)\n(def (order-totals orders) (map order-total orders))\n;; Money <- Order\n(def (order-net order) order)\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings))
                   (finding (car matching))
                   (details (type-finding-details finding)))
              (check (length matching) => 1)
              (check (hash-get details 'missingImplementationEvidence) => #f)
              (check (hash-get details 'implementationCoverageInsufficient) => #t)
              (check (hash-get details 'functionDefinitionCount) => 4)
              (check (hash-get details 'coveredDefinitionCount) => 1)
              (check (hash-get details 'minimumCoveredDefinitionCount) => 2)
              (check (hash-get details 'uncoveredDefinitionCount) => 3)
              (check (not (not (member "order-net"
                                       (hash-get details 'uncoveredDefinitions))))
                     => #t)
              (check (not (not (member "expression-level-composition"
                                       (hash-get details 'qualityFacets))))
                     => #t)
              (check (not (not (member "prefer map/filter/filter-map/fold pipelines; extract predicate, mapper, or reducer helpers before rewriting loops"
                                       (hash-get details 'qualityFacetSteering))))
                     => #t))))
    (test-case "typed-combinator-style policy triggers on native quality facets"
          (let* ((root ".run/policy-typed-combinator-style-native-facets")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n(package: sample/orders)\n;; Integer <- (List Number)\n(def (order-total xs)\n  (let loop ((rest xs) (acc 0))\n    (if (null? rest) acc (loop (cdr rest) (+ acc (car rest))))))\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings))
                   (finding (car matching))
                   (details (type-finding-details finding))
                   (fact (car (project-typed-contract-facts index)))
                   (quality-facets (typed-contract-fact-quality-facets fact))
                   (repair-evidence (typed-contract-fact-repair-evidence fact)))
              (check (length matching) => 1)
              (check (type-finding-severity finding) => "warning")
              (check (hash-get details 'qualityRepairTriggered) => #t)
              (check (not (not (member "manual-loop-drift"
                                       quality-facets)))
                     => #t)
              (check (not (not (member "combinator-candidate"
                                       quality-facets)))
                     => #t)
              (check (not (not (member "replace manual loops with map/filter/filter-map/fold pipelines when parser facts show no IO/state/generator witness"
                                       (hash-get details 'qualityFacetSteering))))
                     => #t)
              (check (hash-get repair-evidence 'factSource) => "native-parser")
              (check (not (not (member "replace-manual-loop-with-higher-order-combinator-when-no-state-witness"
                                       (hash-get repair-evidence 'allowedMoves))))
                     => #t))))))
;; PolicyTest
(def agent-style-comment-policy-test
  (test-suite "gerbil scheme harness comment style policy"
    (test-case "comment-quality policy rejects contract-only engineering comments"
          (let* ((root ".run/policy-comment-quality-contract-only")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n;;; Fixture has module intent so only definition comment quality is tested.\n(package: sample/orders)\n;; Money <- Order\n(def (order-total order) order)\n;; (List Money) <- (List Order)\n(def (order-totals orders) (map order-total orders))\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R015" findings))
                   (finding (car matching))
                   (details (type-finding-details finding))
                   (example (car (hash-get details 'weakCommentExamples)))
                   (parser-evidence (hash-get example 'parserEvidence))
                   (matched-fact (car (hash-get parser-evidence 'matchedFacts)))
                   (repair (finding-agent-repair-json finding)))
              (check (length matching) => 1)
              (check (hash-get details 'weakCommentCount) => 1)
              (check (hash-get details 'evidenceSource)
                     => "parser-owned commentQualityFacts.evidence")
              (check (hash-get details 'repairInstruction)
                     => "write adjacent engineering comment lines when parserEvidence needs them; concise prose, bullets, or Boundary/Invariant/Intent labels are all valid")
              (check (hash-get example 'target) => "order-totals")
              (check (hash-get example 'quality) => "weak")
              (check (hash-get example 'commentKind) => "contract-only")
              (check (hash-get parser-evidence 'definition) => "order-totals")
              (check (hash-get parser-evidence 'context) => "higher-order")
              (check (hash-get parser-evidence 'matchedFactCount) => 1)
              (check (hash-get matched-fact 'factKind) => "higher-order")
              (check (hash-get matched-fact 'role) => "sequence-map")
              (check (hash-get details 'typedContractBoundary)
                     => "typed contract comments describe algebraic shape only and may use adjacent multi-line contract blocks when needed")
              (check (hash-get repair 'nextCommand)
                     => "asp gerbil-scheme guide --code --rule GERBIL-SCHEME-AGENT-R015 --intent style"))))
    (test-case "comment-quality policy rejects compressed engineering comments"
          (let* ((root ".run/policy-comment-quality-compressed")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n;;; Boundary:\n;;; - Fixture owns the comment-quality compression scenario.\n(package: sample/orders)\n;;; Boundary: order-totals maps order-total across orders; keep higher-order data-flow visible.\n;; (List Money) <- (List Order)\n(def (order-totals orders) (map order-total orders))\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R015" findings))
                   (finding (car matching))
                   (details (type-finding-details finding))
                   (example (car (hash-get details 'weakCommentExamples))))
              (check (length matching) => 1)
              (check (hash-get example 'target) => "order-totals")
              (check (hash-get example 'commentKind) => "compressed-engineering")
              (check (hash-get example 'quality) => "weak")
              (check (hash-get example 'reasons)
                     => ["compressed-engineering-comment-needs-adjacent-lines"])
              (check (hash-get details 'commentLinePolicy)
                     => "split multi-clause engineering rationale across adjacent comment lines when it improves confidence; do not squeeze rationale clauses into one semicolon-separated line"))))
    (test-case "typed-combinator-style policy rejects typed contracts without implementation evidence"
          (let* ((root ".run/policy-typed-combinator-style-no-implementation-evidence")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n(package: sample/orders)\n;; Money <- Order\n(def (order-total order) order)\n;; Tax <- Order\n(def (order-tax order) order)\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings))
                   (finding (car matching))
                   (details (type-finding-details finding)))
              (check (length matching) => 1)
              (check (hash-get details 'typedCommentCount) => 2)
              (check (hash-get details 'missingTypedCommentCount) => 0)
              (check (hash-get details 'implementationEvidenceCount) => 0)
              (check (hash-get details 'missingImplementationEvidence) => #t)
              (check (hash-get details 'passiveRepairFlow)
                     => "policy-finding -> agentRepair -> guide-code -> bounded edit")
              (check (hash-get details 'implementationEvidenceSource)
                     => "parser-owned higherOrderFacts plus callFacts; do not use raw text heuristics"))))
    (test-case "typed-combinator-style policy rejects Any contracts"
          (let* ((root ".run/policy-typed-combinator-style-any")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n(package: sample/orders)\n;; Any <- Any\n(def (order-total order) order)\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings))
                   (finding (car matching))
                   (details (type-finding-details finding)))
              (check (length matching) => 1)
              (check (hash-get details 'definitionCount) => 1)
              (check (hash-get details 'typedCommentCount) => 0)
              (check (hash-get details 'validTypedContractCount) => 0)
              (check (hash-get details 'invalidTypedContractCount) => 1)
              (check (hash-get details 'missingTypedCommentCount) => 1))))
    (test-case "typed-combinator-style policy rejects placeholder contracts"
          (let* ((root ".run/policy-typed-combinator-style-placeholder")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n(package: sample/orders)\n;; (List XX) <- Fact Value\n(def (order-total order) order)\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings))
                   (finding (car matching))
                   (details (type-finding-details finding)))
              (check (length matching) => 1)
              (check (hash-get details 'typedCommentCount) => 0)
              (check (hash-get details 'invalidTypedContractCount) => 1)
              (check (hash-get details 'missingTypedCommentCount) => 1)
              (check (hash-get details 'invalidReason)
                     => "typed-combinator-style comments must be parser-owned adjacent algebraic transform signatures; see invalidTypedContractReasons for exact parser reasons")
              (check (hash-get details 'invalidTypedContractReasons)
                     => ["placeholder-contract-without-domain-or-higher-order-shape"])
              (check (hash-get (car (hash-get details 'invalidTypedContractExamples))
                               'contract)
                     => "(List XX) <- Fact Value")
              (check (hash-get (car (hash-get details 'invalidTypedContractExamples))
                               'quality)
                     => "invalid"))))
    (test-case "typed-combinator-style policy rejects inline function names"
          (let* ((root ".run/policy-typed-combinator-style-inline-name")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n(package: sample/orders)\n;; Money <- Order ; order-total\n(def (order-total order) order)\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings))
                   (finding (car matching))
                   (details (type-finding-details finding)))
              (check (length matching) => 1)
              (check (hash-get details 'typedCommentCount) => 0)
              (check (hash-get details 'invalidTypedContractCount) => 1)
              (check (hash-get details 'missingTypedCommentCount) => 1))))
    (test-case "typed-combinator-style policy rejects detached ledger contracts"
          (let* ((root ".run/policy-typed-combinator-style-ledger")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n(package: sample/orders)\n(def (order-total order) order)\n\n;;; typed-combinator-style ledger\n;; Money <- Order\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings))
                   (finding (car matching))
                   (details (type-finding-details finding)))
              (check (length matching) => 1)
              (check (hash-get details 'typedCommentCount) => 0)
              (check (hash-get details 'missingTypedCommentCount) => 1)
              (check (hash-get details 'adjacency) => "definition-leading-comment"))))
    (test-case "typed-combinator-style policy covers t scheme owners"
          (let* ((root ".run/policy-typed-combinator-style-test-owner")
                 (test-dir (string-append root "/t")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir test-dir)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append test-dir "/orders-test.ss")
                        ";;; -*- Gerbil -*-\n(import :std/test)\n(def (order-fixture order) order)\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings))
                   (finding (car matching)))
              (check (length matching) => 1)
              (check (type-finding-path finding) => "t/orders-test.ss")
              (check (hash-get (type-finding-details finding) 'scope)
                     => "source-or-test-owner"))))
    (test-case "typed-combinator-style policy requires exported helpers to use full typed doc blocks"
          (let* ((root ".run/policy-typed-combinator-style-exported-doc-missing")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n;;; Boundary:\n;;; - Fixture keeps ordinary helper contracts short and exported API docs audited.\n(package: sample/orders)\n(export order-totals)\n;; : (-> Order Money)\n(def (order-total order) order)\n;; : (-> (List Order) (List Money))\n;; | type Money = Number\n(def (order-totals orders) (map order-total orders))\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings))
                   (finding (car matching))
                   (details (type-finding-details finding)))
              (check (length matching) => 1)
              (check (hash-get details 'typedDocMissing) => #t)
              (check (hash-get details 'typedDocMissingCount) => 1)
              (check (hash-get details 'typedDocMissingTargets)
                     => ["order-totals"])
              (check (hash-get details 'expectedDocShape)
                     => "full form for exported helpers, macros, and policy-sensitive helpers: leading name matching the definition, ;;   : signature, optional ;;   | type/contract/requires/warning/rationale fields, and non-empty ;;   | doc m% block")
              (check (hash-get details 'typedDocRequiredWhen)
                     => "exported arity-bearing helper, macro, src/policy helper, or policy-sensitive helper"))))
    (test-case "typed-combinator-style policy accepts exported helpers with full typed doc blocks"
          (let* ((root ".run/policy-typed-combinator-style-exported-doc-present")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n;;; Boundary:\n;;; - Fixture proves exported API helpers can satisfy full-form typed docs.\n(package: sample/orders)\n(export order-totals)\n;; : (-> Order Money)\n(def (order-total order) order)\n;; order-totals\n;;   : (-> (List Order) (List Money))\n;;   | type Money = Number\n;;   | doc m%\n;;       `order-totals orders` returns order totals for `orders`.\n;;     %\n(def (order-totals orders) (map order-total orders))\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings)))
              (check matching => []))))
    (test-case "typed-combinator-style policy rejects full typed doc blocks with mismatched leading names"
          (let* ((root ".run/policy-typed-combinator-style-exported-doc-name-mismatch")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n;;; Boundary:\n;;; - Fixture proves full-form docs must name the attached definition.\n(package: sample/orders)\n(export order-totals)\n;; : (-> Order Money)\n(def (order-total order) order)\n;; wrong-order-totals\n;;   : (-> (List Order) (List Money))\n;;   | type Money = Number\n;;   | doc m%\n;;       `order-totals orders` returns order totals for `orders`.\n;;     %\n(def (order-totals orders) (map order-total orders))\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings))
                   (finding (car matching))
                   (details (type-finding-details finding)))
              (check (length matching) => 1)
              (check (hash-get details 'typedDocMissing) => #t)
              (check (hash-get details 'typedDocMissingTargets)
                     => ["order-totals"]))))
    (test-case "typed-combinator-style policy can be disabled by package config"
          (let* ((root ".run/policy-typed-combinator-style-disabled")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders\n  policy: ((agent-policy disabled-rules: (\"GERBIL-SCHEME-AGENT-R013\"))))\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n(package: sample/orders)\n(def (order-total order) order)\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings)))
              (check matching => []))))))
;; PolicyTest
(def agent-style-functional-policy-test
  (test-suite "gerbil scheme harness functional style policy"
    (test-case "agent policy warns on manual loops that should use functional idioms"
          (let* ((root ".run/policy-functional-idiom")
                 (_ (write-functional-idiom-project root))
                 (index (collect-project root))
                 (findings (run-agent-policy index))
                 (matching (filter-rule "GERBIL-SCHEME-AGENT-R009" findings))
                 (finding (car matching)))
            (check (length matching) => 1)
            (check (type-finding-severity finding) => "warning")
            (check (type-status matching) => "fail")
            (check (type-finding-path finding) => "src/orders/core.ss")
            (check (type-finding-selector finding) => "src/orders/core.ss:5-6")
            (check (not (not (string-contains
                              (type-finding-message finding)
                              "redundant pure transform")))
                   => #t)
            (check (hash-get (type-finding-details finding) 'kind)
                   => "named-let")
            (check (hash-get (type-finding-details finding) 'namedLetPolicy)
                   => "warn-on-redundant-pure-transform-only")
            (check (hash-get (type-finding-details finding) 'detectionSignals)
                   => ["named-let"
                       "manual-loop-role"
                       "multi-binding-loop-state"
                       "no-functional-idiom-witness"
                       "no-reader-boundary"
                       "no-control-preservation-context"])
            (check (hash-get (type-finding-details finding) 'sequenceIdioms)
                   => ["map" "filter" "filter-map" "append-map" "fold/foldl/foldr" "for/fold"])
            (check (hash-get (type-finding-details finding) 'predicateIdioms)
                   => ["andmap/ormap" "every/any" "find/list-index"])
            (check (hash-get (type-finding-details finding) 'compositionIdioms)
                   => ["cut/cute" "curry/rcurry" "compose/compose1"])
            (check (hash-get (type-finding-details finding) 'builderIdioms)
                   => ["with-list-builder"])
            (check (hash-get (type-finding-details finding) 'styleGuide)
                   => "typed-combinator-style")
            (check (hash-get (type-finding-details finding) 'styleCommand)
                   => "asp gerbil-scheme guide --code --topic typed-combinator-style --intent style")
            (check (hash-get (type-finding-details finding) 'detectedControlContexts)
                   => [])
            (check (hash-get (type-finding-details finding) 'callerControlContexts)
                   => [])
            (check (hash-get (type-finding-details finding) 'keepNamedLetWhen)
                   => "IO/stateful control flow, C3-style fixpoint selection, or generator/continuation driver")
            (check (hash-get (type-finding-details finding) 'preserveNamedLetWhen)
                   => ["local recursion without accumulator boilerplate"
                       "reader or port EOF loops"
                       "stateful control flow"
                       "C3-style fixpoint selection"
                       "generator, coroutine, actor, or continuation driver"])))
    (test-case "agent policy preserves focused named-let recursion"
          (let* ((root ".run/policy-functional-idiom-focused-named-let")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append owner "/facade.ss")
                        ";;; -*- Gerbil -*-\n;;; Orders facade intent.\n(export resolve)\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n(package: sample/orders)\n(export resolve)\n;; : (-> Node Node)\n(def (resolve node)\n  (let walk ((current node))\n    (if (node-final? current)\n      current\n      (walk (node-parent current)))))\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R009" findings)))
              (check matching => []))))
    (test-case "agent policy check output routes findings to guide code"
          (let* ((root ".run/policy-functional-idiom-check-output")
                 (_ (write-functional-idiom-project root)))
            (match (policy-check-output [root])
              ([exit-code . output]
               (check exit-code => 1)
            (check (not (not (string-contains
                              output
                              "|agent-repair-info status=active repairableFindings=3 repairableWarnings=3 repairableErrors=0 trigger=warning")))
                   => #t)
            (check (not (not (string-contains
                              output
                              "|agent-repair rule=GERBIL-SCHEME-AGENT-R009 severity=warning repairable=true active=true trigger=warning")))
                   => #t)
            (check (not (not (string-contains
                              output
                              "guideTopic=functional-data-transform")))
                   => #t)
            (check (not (not (string-contains
                              output
                              "guideIntent=repair")))
                   => #t)
            (check (not (not (string-contains
                              output
                              "nextCommand=asp gerbil-scheme guide --code --rule GERBIL-SCHEME-AGENT-R009 --intent repair")))
                   => #t)
            (check (not (not (string-contains
                              output
                              "action=inspect-code-shape")))
                   => #t)
            (check (not (not (string-contains
                              output
                              "guideCodeFlag=--code")))
                   => #t)
            (check (not (not (string-contains
                              output
                              "nextCommand=asp gerbil-scheme guide --code --rule GERBIL-SCHEME-AGENT-R015 --intent style")))
                   => #t)
            (check (not (not (string-contains
                              output
                              "styleGuide=typed-combinator-style")))
                   => #t)
            (check (not (not (string-contains
                              output
                              "styleCommand=asp gerbil-scheme guide --code --topic typed-combinator-style --intent style")))
                   => #t)
            (check (not (not (string-contains
                              output
                              "qualityFacets=")))
                   => #t)
            (check (not (not (string-contains
                              output
                              "qualityFacetSteering=")))
                   => #t)))))
    (test-case "agent policy reports repeated match branch shape before style repair"
          (let* ((root ".run/policy-controlled-branch-shape")
                 (_ (write-controlled-branch-shape-project root))
                 (index (collect-project root))
                 (findings (run-agent-policy index))
                 (matching (filter-rule "GERBIL-SCHEME-AGENT-R014" findings))
                 (finding (car matching)))
            (check (length matching) => 1)
            (check (type-finding-path finding) => "src/orders/core.ss")
            (check (type-finding-selector finding) => "src/orders/core.ss:5-7")
            (check (hash-get (type-finding-details finding) 'styleGuide)
                   => "controlled-branch-shape")
            (check (hash-get (type-finding-details finding) 'rewriteScope)
                   => "same caller or extracted helper only")
            (check (hash-get (type-finding-details finding) 'qualityReference)
                   => "gerbil-utils")
            (check (hash-get (type-finding-details finding) 'functionShape)
                   => "small selector/predicate/helper first; keep match branches shallow and expression-returning")
            (check (hash-get (type-finding-details finding) 'expressionLevelRewrite)
                   => "turn repeated match plus accumulator shape into a named predicate/mapper/reducer pipeline before changing behavior")
            (match (policy-check-output [root])
              ([exit-code . output]
               (check exit-code => 1)
               (check (not (not (string-contains output "guideTopic=controlled-branch-shape"))) => #t)
               (check (not (not (string-contains output "nextCommand=asp gerbil-scheme guide --code --rule GERBIL-SCHEME-AGENT-R014 --intent style"))) => #t)))))
    (test-case "agent policy reports match plus named-let selector shape before style repair"
          (let* ((root ".run/policy-controlled-branch-loop-shape")
                 (_ (write-controlled-branch-loop-shape-project root))
                 (index (collect-project root))
                 (findings (run-agent-policy index))
                 (matching (filter-rule "GERBIL-SCHEME-AGENT-R014" findings))
                 (finding (car matching)))
            (check (length matching) => 1)
            (check (type-finding-path finding) => "src/orders/core.ss")
            (check (type-finding-selector finding) => "src/orders/core.ss:5-12")
            (check (hash-get (type-finding-details finding) 'shape)
                   => "pattern-branch-with-manual-loop")
            (check (hash-get (type-finding-details finding) 'matchCount) => 1)
            (check (hash-get (type-finding-details finding) 'manualLoopCount) => 1)
            (check (not (not (string-contains
                              (type-finding-message finding)
                              "combines match state destructuring with a named-let loop")))
                   => #t)))))
;; PolicyTest
(def agent-style-predicate-policy-test
  (test-suite "gerbil scheme harness predicate style policy"
    (test-case "agent policy reports predicate family combinator repair"
          (let* ((root ".run/policy-predicate-family-combinator")
                 (_ (write-predicate-family-combinator-project root))
                 (index (collect-project root))
                 (findings (run-agent-policy index))
                 (matching (filter-rule "GERBIL-SCHEME-AGENT-R016" findings))
                 (finding (car matching))
                 (details (type-finding-details finding))
                 (repair (finding-agent-repair-json finding)))
            (check (length matching) => 1)
            (check (type-finding-path finding) => "src/orders/core.ss")
            (check (type-finding-severity finding) => "warning")
            (check (hash-get details 'styleGuide) => "predicate-family-combinator")
            (check (hash-get details 'subject) => "fact")
            (check (hash-get details 'predicateCount) => 3)
            (check (hash-get (hash-get details 'gerbilUtilsSource)
                             'sourcePattern)
                   => "gerbil-utils-predicate-combinator")
            (check (not (not (member "gerbil-utils/base.ss#compose"
                                     (hash-get (hash-get details 'gerbilUtilsSource)
                                               'sourceOwners))))
                   => #t)
            (check (not (not (member "role" (hash-get details 'fieldKeys)))) => #t)
            (check (not (not (member "hash-get" (hash-get details 'repeatedCallees)))) => #t)
            (check (hash-get repair 'active) => #t)
            (check (hash-get repair 'guideTopic) => "predicate-family-combinator")
            (check (hash-get repair 'nextCommand)
                   => "asp gerbil-scheme guide --code --rule GERBIL-SCHEME-AGENT-R016 --intent style")))
    (test-case "agent policy keeps single-caller high-count field access advisory only"
          (let* ((root ".run/policy-field-access-single-caller-advisory")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text
             (string-append owner "/core.ss")
             ";;; -*- Gerbil -*-\n(package: sample/orders)\n(def (duration-summary row)\n  (+ (hash-get row 'durationMs)\n     (hash-get row 'durationMs)\n     (hash-get row 'durationMs)\n     (hash-get row 'durationMs)\n     (hash-get row 'durationMs)\n     (hash-get row 'durationMs)\n     (hash-get row 'durationMs)\n     (hash-get row 'durationMs)))\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R016" findings)))
              (check matching => []))))
    (test-case "agent policy reports combined field access selector repair"
          (let* ((root ".run/policy-field-access-selector-helper")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text
             (string-append owner "/core.ss")
             ";;; -*- Gerbil -*-\n(package: sample/orders)\n(def (duration-total row)\n  (+ (hash-get row 'durationMs)\n     (hash-get row 'durationMs)\n     (hash-get row 'durationMs)))\n(def (duration-max row)\n  (if (> (hash-get row 'durationMs) 0)\n    (hash-get row 'durationMs)\n    0))\n(def (duration-label row)\n  (string-append \"duration=\" (hash-get row 'durationMs)))\n(def (duration-warning? row)\n  (or (> (hash-get row 'durationMs) 100)\n      (< (hash-get row 'durationMs) 0)))\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R016" findings))
                   (finding (car matching))
                   (details (type-finding-details finding))
                   (field-evidence (hash-get details 'fieldAccessPattern))
                   (repair (finding-agent-repair-json finding)))
              (check (length matching) => 1)
              (check (type-finding-path finding) => "src/orders/core.ss")
              (check (type-finding-severity finding) => "warning")
              (check (hash-get details 'evidenceSource)
                     => "parser-owned fieldAccessPatternFacts")
              (check (hash-get details 'policySignals)
                     => ["high-field-access-count"
                         "cross-caller-field-access"])
              (check (hash-get details 'detectionCombiner)
                     => "field-access-helper-all-of")
              (check [(hash-get details 'detectionPrototype)
                      (hash-get details 'detectionCombinerKind)]
                     => ["field-access-helper-all-of" "all-of"])
              (check (hash-get details 'detectionDescription)
                     => "field access helper repair requires high access count and cross-caller spread")
              (check (hash-get details 'detectionSourcePattern)
                     => "gerbil-utils-predicate-combinator")
              (check (not (not (member "gerbil-utils/base.ss#compose"
                                       (hash-get details 'detectionSourceOwners))))
                     => #t)
              (check (not (not (member "predicate-combinator"
                                       (hash-get details 'detectionQualitySignals))))
                     => #t)
              (check (hash-get details 'detectionWitness)
                     => "gerbil-utils study: compose/cut/curry helpers and generator map/fold are style witnesses for bounded predicate or selector helper repair")
              (check (hash-get details 'requiredGroups)
                     => ["high-field-access-count"
                         "cross-caller-field-access"])
              (check (hash-get details 'evidenceGroups)
                     => ["high-field-access-count"
                         "cross-caller-field-access"])
              (check (hash-get details 'evidenceCounts) => [8 4])
              (check (hash-get field-evidence 'fieldKey) => "durationMs")
              (check (hash-get field-evidence 'accessCount) => 8)
              (check (length (hash-get field-evidence 'callers)) => 4)
              (check (hash-get details 'accessCountGate) => 8)
              (check (hash-get details 'callerCountGate) => 3)
              (check (hash-get repair 'active) => #t)
              (check (hash-get repair 'guideTopic) => "predicate-family-combinator")
              (check (hash-get repair 'nextCommand)
                     => "asp gerbil-scheme guide --code --rule GERBIL-SCHEME-AGENT-R016 --intent style")))
    (test-case "agent policy reports emitter projection burst through multiple signals"
          (let* ((root ".run/policy-emitter-projection-burst")
                 (_ (write-projection-burst-project root))
                 (index (collect-project root))
                 (findings (run-agent-policy index))
                 (matching (filter-rule "GERBIL-SCHEME-AGENT-R016" findings))
                 (finding (car matching))
                 (details (type-finding-details finding))
                 (burst-evidence (hash-get details 'projectionBurst))
                 (repair (finding-agent-repair-json finding)))
            (check (length matching) => 1)
            (check (type-finding-path finding) => "src/orders/core.ss")
            (check (type-finding-severity finding) => "warning")
            (check (hash-get details 'evidenceSource)
                   => "parser-owned projectionBurstFacts")
            (check (hash-get details 'policySignals)
                   => ["high-projection-access-count"
                       "multi-field-projection"
                       "emitter-output-boundary"])
            (check (hash-get details 'detectionCombiner)
                   => "emitter-projection-burst-all-of")
            (check [(hash-get details 'detectionPrototype)
                    (hash-get details 'detectionCombinerKind)]
                   => ["emitter-projection-burst-all-of" "all-of"])
            (check (hash-get details 'detectionDescription)
                   => "emitter projection repair requires access density, field spread, and output boundary evidence")
            (check (hash-get details 'detectionSourcePattern)
                   => "gerbil-utils-projection-builder")
            (check (not (not (member "gerbil-utils/base.ss#compose"
                                     (hash-get details 'detectionSourceOwners))))
                   => #t)
            (check (not (not (member "list-builder-output-shape"
                                     (hash-get details 'detectionQualitySignals))))
                   => #t)
            (check (not (not (member "projection-builder"
                                     (hash-get details 'detectionProfilePrecedence))))
                   => #t)
            (check (hash-get details 'requiredGroups)
                   => ["high-projection-access-count"
                       "multi-field-projection"
                       "emitter-output-boundary"])
            (check (hash-get details 'evidenceGroups)
                   => ["high-projection-access-count"
                       "multi-field-projection"
                       "emitter-output-boundary"])
            (check (hash-get details 'evidenceCounts) => [12 4 2])
            (check (hash-get burst-evidence 'caller) => "emit-order-line")
            (check (hash-get burst-evidence 'accessCount) => 12)
            (check (hash-get burst-evidence 'accessorCount) => 4)
            (check (hash-get burst-evidence 'emitterCount) => 2)
            (check (not (not (member "id"
                                     (hash-get burst-evidence 'fieldKeys))))
                   => #t)
            (check (hash-get repair 'active) => #t)
            (check (hash-get repair 'guideTopic) => "predicate-family-combinator")
            (check (hash-get repair 'nextCommand)
                   => "asp gerbil-scheme guide --code --rule GERBIL-SCHEME-AGENT-R016 --intent style"))))))
;; PolicyTest
(def agent-style-policy-test
  (test-suite "gerbil scheme harness agent style policy"
    agent-style-typed-policy-test
    agent-style-comment-policy-test
    agent-style-functional-policy-test
    agent-style-predicate-policy-test))
