;;; -*- Gerbil -*-
;;; gerbil scheme harness agent style comment core policy.

(import :gerbil/gambit
        :std/test
        :std/misc/ports
        :std/misc/process
        :std/sort
        :gslph/src/parser/facade
        :gslph/src/policy/agent-style
        :gslph/src/policy/facade
        :gslph/src/policy/gxtest
        :gslph/src/scenario/policy
        :gslph/src/types/facade
        :unit/policy/poo-scenarios
        :policy/fixtures)
(import :policy/agent-style-support)
(export agent-style-comment-core-policy-test)

;; PolicyTest
(def agent-style-comment-core-policy-test
  (test-suite "gerbil scheme harness agent style comment core policy"
(test-case "comment-quality policy keeps plain higher-order comments advisory"
          (let* ((root ".run/policy-comment-quality-contract-only")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n;;; Fixture has module intent so only definition comment quality is tested.\n(package: sample/orders)\n;; : (-> Order Money)\n(def (order-total order) order)\n;; : (-> (List Order) (List Money))\n(def (order-totals orders) (map order-total orders))\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-POLICY-015" findings)))
              (check matching => []))))
(test-case "comment-quality policy rejects compressed engineering comments"
          (let* ((root ".run/policy-comment-quality-compressed")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n;;; Boundary:\n;;; - Fixture owns the comment-quality compression scenario.\n(package: sample/orders)\n;;; Boundary: order-totals maps order-total across orders; keep higher-order data-flow visible.\n;; : (-> (List Order) (List Money))\n(def (order-totals orders)\n  (let* ((v01 orders)\n         (v02 v01)\n         (v03 v02)\n         (v04 v03)\n         (v05 v04)\n         (v06 v05)\n         (v07 v06)\n         (v08 v07)\n         (v09 v08)\n         (v10 v09)\n         (v11 v10)\n         (v12 v11)\n         (v13 v12)\n         (v14 v13)\n         (v15 v14)\n         (v16 v15)\n         (v17 v16)\n         (v18 v17)\n         (v19 v18)\n         (v20 v19)\n         (v21 v20)\n         (v22 v21)\n         (v23 v22)\n         (v24 v23)\n         (v25 v24)\n         (v26 v25)\n         (v27 v26)\n         (v28 v27)\n         (v29 v28)\n         (v30 v29)\n         (v31 v30)\n         (v32 v31)\n         (v33 v32)\n         (v34 v33)\n         (v35 v34)\n         (v36 v35)\n         (v37 v36)\n         (v38 v37)\n         (v39 v38)\n         (v40 v39)\n         (v41 v40)\n         (v42 v41)\n         (v43 v42)\n         (v44 v43)\n         (v45 v44)\n         (v46 v45)\n         (v47 v46)\n         (v48 v47)\n         (v49 v48)\n         (v50 v49)\n         (v51 v50)\n         (v52 v51)\n         (v53 v52)\n         (v54 v53)\n         (v55 v54)\n         (v56 v55)\n         (v57 v56)\n         (v58 v57)\n         (v59 v58)\n         (v60 v59))\n    (map order-total v60)))\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-POLICY-015" findings))
                   (finding (car matching))
                   (details (type-finding-details finding))
                   (example (car (hash-get details 'weakCommentExamples))))
              (check (length matching) => 1)
              (check (hash-get example 'target) => "order-totals")
              (check (hash-get example 'commentKind) => "compressed-engineering")
              (check (hash-get example 'quality) => "weak")
              (check (hash-get example 'reasons)
                     => ["compressed-engineering-comment-needs-adjacent-lines"])
              (check (hash-get details 'commentLinePolicy)
                     => "split multi-clause engineering rationale across adjacent comment lines when it improves confidence; do not squeeze rationale clauses into one semicolon-separated line"))))
(test-case "typed-combinator-style policy rejects typed contracts without implementation evidence"
          (let* ((root ".run/policy-typed-combinator-style-no-implementation-evidence")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n(package: sample/orders)\n;; : (-> Order Money)\n(def (order-total order) order)\n;; : (-> Order Tax)\n(def (order-tax order) order)\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-POLICY-013" findings))
                   (finding (car matching))
                   (details (type-finding-details finding)))
              (check (length matching) => 1)
              (check (hash-get details 'typedCommentCount) => 2)
              (check (hash-get details 'missingTypedCommentCount) => 0)
              (check (hash-get details 'implementationEvidenceCount) => 0)
              (check (hash-get details 'missingImplementationEvidence) => #t)
              (check (hash-get details 'passiveRepairFlow)
                     => "policy-finding -> agentRepair -> guide-code -> bounded edit")
              (check (hash-get details 'implementationEvidenceSource)
                     => "parser-owned higherOrderFacts plus callFacts; do not use raw text heuristics"))))
(test-case "typed-combinator-style policy rejects Any contracts"
          (let* ((root ".run/policy-typed-combinator-style-any")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n(package: sample/orders)\n;; : (-> Any Any)\n(def (order-total order) order)\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-POLICY-013" findings))
                   (finding (car matching))
                   (details (type-finding-details finding)))
              (check (length matching) => 1)
              (check (hash-get details 'definitionCount) => 1)
              (check (hash-get details 'typedCommentCount) => 0)
              (check (hash-get details 'validTypedContractCount) => 0)
              (check (hash-get details 'invalidTypedContractCount) => 1)
              (check (hash-get details 'missingTypedCommentCount) => 1))))
(test-case "typed-combinator-style policy rejects placeholder contracts"
          (let* ((root ".run/policy-typed-combinator-style-placeholder")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n(package: sample/orders)\n;; : (-> Fact Value (List XX))\n(def (order-total order) order)\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-POLICY-013" findings))
                   (finding (car matching))
                   (details (type-finding-details finding)))
              (check (length matching) => 1)
              (check (hash-get details 'typedCommentCount) => 0)
              (check (hash-get details 'invalidTypedContractCount) => 1)
              (check (hash-get details 'missingTypedCommentCount) => 1)
              (check (hash-get details 'invalidReason)
                     => "typed-combinator-style comments must be parser-owned adjacent algebraic transform signatures; see invalidTypedContractReasons for exact parser reasons")
              (check (hash-get details 'invalidTypedContractReasons)
                     => ["placeholder-type-variable-token"
                         "placeholder-contract-without-domain-or-higher-order-shape"])
              (check (hash-get (car (hash-get details 'invalidTypedContractExamples))
                               'contract)
                     => "(-> Fact Value (List XX))")
              (check (hash-get (car (hash-get details 'invalidTypedContractExamples))
                               'quality)
                     => "invalid"))))
  ))
