;;; -*- Gerbil -*-
;;; gerbil scheme harness agent poo policy.

(import :gerbil/gambit
        :std/test
        :std/misc/ports
        :std/misc/process
        (only-in :std/text/json read-json)
        :commands/check
        :parser/facade
        :policy/facade
        :policy/gxtest
        :types/facade
        :unit/policy/poo-scenarios
        :policy/fixtures)
(export agent-poo-policy-test)
;; PolicyTest
(def agent-poo-policy-test
  (test-suite "gerbil scheme harness agent poo policy"
    (test-case "agent policy reports weak dependency protocol adapters"
          (let* ((root ".run/policy-dependency-protocol-adapter")
                 (_ (write-dependency-protocol-adapter-project root #f #f))
                 (index (collect-project root))
                 (findings (run-policy-checks index))
                 (matching (filter-rule "GERBIL-SCHEME-AGENT-R017" findings))
                 (finding (car matching))
                 (details (type-finding-details finding))
                 (repair (finding-agent-repair-json finding)))
            (check (length matching) => 1)
            (check (type-finding-path finding) => "src/orders/dict.ss")
            (check (hash-get details 'styleGuide) => "dependency-protocol-adapter")
            (check (hash-get details 'dependency) => ":clan/pure/dict/orderdict")
            (check (hash-get details 'quality) => "weak")
            (check (not (not (member "typed-validation-boundary"
                                      (hash-get details 'missingEvidence))))
                   => #t)
            (check (not (not (member "generic-contract-test-witness"
                                      (hash-get details 'missingEvidence))))
                   => #t)
            (check (hash-get details 'manualObjectEncodingRisk) => "none")
            (check (hash-get details 'genericContractWitnessKind)
                   => "table-protocol-contract-witness")
            (check (hash-get details 'contractWitnessKind) => "missing")
            (check (not (not (member "table"
                                      (hash-get details 'derivedCapabilities))))
                   => #t)
            (check (hash-get details 'agentRepairStandard)
                   => "current dependency already provides the bottom data structure; do not hand-write loose hash/alist objects. Build a typed protocol adapter: precise only-in imports for primitives, define-type Key/Value/validate/serialization/equality slots, behavior on protocol slots, derived table/set/list/sexp/json/marshal capabilities when slots exist, and generic contract tests")
            (check (hash-get details 'repairAction)
                   => "search-forwarded-example-then-guide-code")
            (check (hash-get details 'guideCodeFlag) => "--code")
            (check (hash-get details 'searchExampleCommand)
                   => "asp gerbil-scheme search pattern poo rationaldict adapter --view seeds .")
            (check (hash-get details 'repairCodeCommand)
                   => "asp gerbil-scheme guide --code --rule GERBIL-SCHEME-AGENT-R017 --intent repair")
            (check (hash-get details 'codeShapeExemplar)
                   => "gerbil-poo rationaldict-style typed protocol adapter")
            (check (hash-get details 'sourcePatternLineage)
                   => "gerbil-poo build/cli/rationaldict/table/brace/object/mop/io patterns")
            (check (hash-get details 'protocolSurface)
                   => "minimal protocol slots first; derive table/set/list/sexp/json/marshal-facing capabilities from the slot surface")
            (check (hash-get details 'protocolSurfaceReference)
                   => "gerbil-poo table.ss methods.table")
            (check (hash-get details 'reusableContractTestPattern)
                   => "small t/ owner calls generic table-contract-tests or protocol-contract-tests against the adapter type descriptor")
            (check (hash-get details 'macroBridgeBoundary)
                   => "syntax forms should stay thin bridges like gerbil-poo brace.ss @method; runtime semantics belong in object/mop/protocol slots")
            (check (hash-get details 'slotResolutionModel)
                   => "POO objects resolve slots through C3 precedence plus lazy slot function cache; do not replace this with raw hash/alist guesses")
            (check (hash-get details 'ioSerializationMethodFamily)
                   => "json<-/<-json, marshal/unmarshal, bytes<-/<-bytes, and string<-/<-string are method/type slots")
            (check (hash-get details 'buildPattern)
                   => "use :std/make + :clan/base + :clan/building discovery, while filtering non-module policy/config files for this harness")
            (check (hash-get details 'cliOptionPattern)
                   => "keep src/cli.ss as a thin dispatcher; compose option objects when command option surfaces grow")
            (check (not (not (string-contains
                              (hash-get details 'adapterRepairShape)
                              "query the search-forwarded rationaldict adapter example first")))
                   => #t)
            (check (not (not (member "run asp gerbil-scheme search pattern poo rationaldict adapter --view seeds . to inspect the dependency example before editing"
                                      (hash-get details 'allowedMoves))))
                   => #t)
            (check (not (not (member "run asp gerbil-scheme guide --code --rule GERBIL-SCHEME-AGENT-R017 --intent repair to inspect local R017 parser/policy repair code"
                                      (hash-get details 'allowedMoves))))
                   => #t)
            (check (not (not (member "derive table/set/list/sexp/json/marshal-facing capability from protocol slots"
                                      (hash-get details 'allowedMoves))))
                   => #t)
            (check (not (not (member "do not replace dependency primitives with hand-written hash/alist storage"
                                      (hash-get details 'disallowedMoves))))
                   => #t)
            (check (hash-get repair 'guideTopic) => "dependency-protocol-adapter")
            (check (hash-get repair 'nextCommand)
                   => "asp gerbil-scheme search pattern poo rationaldict adapter --view seeds .")))
    (test-case "agent policy rejects manual object encoding inside dependency adapters"
          (let* ((root ".run/policy-dependency-manual-object-adapter")
                 (_ (write-dependency-manual-object-adapter-project root))
                 (index (collect-project root))
                 (findings (run-policy-checks index))
                 (matching (filter-rule "GERBIL-SCHEME-AGENT-R017" findings))
                 (finding (car matching))
                 (details (type-finding-details finding)))
            (check (length matching) => 1)
            (check (type-finding-path finding) => "src/orders/dict.ss")
            (check (hash-get details 'manualObjectEncodingRisk)
                   => "manual-object-encoding-risk")
            (check (not (not (member "manual-object-encoding-risk"
                                      (hash-get details 'missingEvidence))))
                   => #t)
            (check (not (not (member "no-manual-object-encoding"
                                      (hash-get details 'qualityFacets))))
                   => #f)))
    (test-case "agent policy accepts complete dependency protocol adapters with contract witnesses"
          (let* ((root ".run/policy-dependency-protocol-adapter-positive")
                 (_ (write-dependency-protocol-adapter-project root #t #t))
                 (index (collect-project root))
                 (facts (project-dependency-adapter-quality-facts index))
                 (fact (car facts))
                 (findings (run-policy-checks index))
                 (matching (filter-rule "GERBIL-SCHEME-AGENT-R017" findings)))
            (check (length facts) => 1)
            (check (dependency-adapter-quality-fact-quality fact) => "complete")
            (check (not (not (member "precise-only-in-import"
                                      (dependency-adapter-quality-fact-quality-facets fact))))
                   => #t)
            (check (not (not (member "table"
                                      (dependency-adapter-quality-fact-derived-capabilities fact))))
                   => #t)
            (check (dependency-adapter-quality-fact-manual-object-encoding-risk fact)
                   => "none")
            (check (dependency-adapter-quality-fact-generic-contract-witness-kind fact)
                   => "table-protocol-contract-witness")
            (check matching => [])))
    (test-case "agent policy rejects direct POO writeenv calls"
          (let* ((root ".run/policy-poo-direct-writeenv")
                 (_ (write-poo-direct-writeenv-project root))
                 (index (collect-project root))
                 (findings (run-agent-policy index))
                 (matching (filter-rule "GERBIL-SCHEME-AGENT-R006" findings))
                 (finding (car matching)))
            (check (length matching) => 1)
            (check (type-finding-rule-id finding)
                   => "GERBIL-SCHEME-AGENT-R006")
            (check (type-finding-path finding) => "src/orders/io.ss")
            (check (type-finding-message finding)
                   => "direct writeenv calls bypass POO IO runtime-source evidence; query search runtime-source writeenv printer hook first")))
    (test-case "agent policy requires runtime-source witness for POO IO overrides"
          (let* ((root ".run/policy-poo-io-runtime-witness")
                 (_ (write-poo-io-override-project root))
                 (index (collect-project root))
                 (findings (run-agent-policy index))
                 (matching (filter-rule "GERBIL-SCHEME-AGENT-R007" findings))
                 (finding (car matching)))
            (check (length matching) => 1)
            (check (type-finding-rule-id finding)
                   => "GERBIL-SCHEME-AGENT-R007")
            (check (type-finding-path finding) => "src/orders/io.ss")
            (check (type-finding-message finding)
                   => "POO IO method overrides in src/ need runtime-source-backed writeenv/printer-hook witness coverage before being treated as verified")))
    (test-case "agent policy requires POO method generic and class facts"
          (let* ((root ".run/policy-poo-method-shape")
                 (_ (write-poo-method-shape-project root))
                 (index (collect-project root))
                 (findings (run-agent-policy index))
                 (matching (filter-rule "GERBIL-SCHEME-AGENT-R008" findings))
                 (finding (car matching)))
            (check (length matching) => 1)
            (check (type-finding-rule-id finding)
                   => "GERBIL-SCHEME-AGENT-R008")
            (check (type-finding-path finding) => "src/orders/methods.ss")
            (check (type-finding-message finding)
                   => "POO method order-discount is missing parser-owned defgeneric,defclass-or-defprotocol facts; query POO pattern evidence and add defgeneric/defclass/defprotocol structure before extending methods")))
    (test-case "agent policy requires macro runtime-source witness"
          (let* ((root ".run/policy-macro-runtime-source")
                 (_ (write-macro-runtime-source-project root #f))
                 (index (collect-project root))
                 (findings (run-agent-policy index))
                 (matching (filter-rule "GERBIL-SCHEME-AGENT-R011" findings))
                 (finding (car matching)))
            (check (length matching) => 1)
            (check (type-finding-path finding) => "src/macros/core.ss")
            (check (hash-get (type-finding-details finding) 'next)
                   => "search runtime-source macro sugar module-sugar")))
    (test-case "agent policy accepts macro runtime-source witness policy"
          (let* ((root ".run/policy-macro-runtime-source-allowed")
                 (_ (write-macro-runtime-source-project root #t))
                 (index (collect-project root))
                 (findings (run-agent-policy index))
                 (matching (filter-rule "GERBIL-SCHEME-AGENT-R011" findings)))
            (check matching => [])))
    (test-case "agent policy requires declared protocol evidence"
          (let* ((root ".run/policy-protocol-evidence")
                 (_ (write-protocol-evidence-project root #f))
                 (index (collect-project root))
                 (findings (run-agent-policy index))
                 (matching (filter-rule "GERBIL-SCHEME-AGENT-R012" findings))
                 (finding (car matching)))
            (check (length matching) => 1)
            (check (type-finding-path finding) => "src/orders/protocol.ss")
            (check (hash-get (type-finding-details finding) 'next)
                   => "search pattern poo protocol")))
    (test-case "agent policy accepts declared protocol evidence"
          (let* ((root ".run/policy-protocol-evidence-positive")
                 (_ (write-protocol-evidence-project root #t))
                 (index (collect-project root))
                 (findings (run-agent-policy index))
                 (matching (filter-rule "GERBIL-SCHEME-AGENT-R012" findings)))
            (check matching => [])))
    (test-case "agent policy catches downstream POO implementation drift"
          (let* ((root ".run/policy-downstream-poo-agent")
                 (_ (write-downstream-poo-agent-project root))
                 (index (collect-project root))
                 (findings (run-agent-policy index))
                 (vague (filter-rule "GERBIL-SCHEME-AGENT-R004" findings))
                 (direct-writeenv (filter-rule "GERBIL-SCHEME-AGENT-R006" findings))
                 (runtime-witness (filter-rule "GERBIL-SCHEME-AGENT-R007" findings))
                 (method-shape (filter-rule "GERBIL-SCHEME-AGENT-R008" findings))
                 (object-model (filter-rule "GERBIL-SCHEME-AGENT-R010" findings)))
            (check (length vague) => 1)
            (check (length direct-writeenv) => 1)
            (check (length runtime-witness) => 1)
            (check (length method-shape) => 1)
            (check (length object-model) => 1)
            (check (type-finding-path (car vague)) => "src/orders/core.ss")
            (check (type-finding-path (car direct-writeenv)) => "src/orders/io.ss")
            (check (type-finding-path (car runtime-witness)) => "src/orders/io.ss")
            (check (type-finding-path (car method-shape)) => "src/orders/io.ss")
            (check (type-finding-path (car object-model)) => "src/orders/core.ss")
            (check (type-finding-selector (car object-model)) => "src/orders/core.ss:4-4")))
    (test-case "agent policy accepts downstream POO pattern-guided implementation"
          (let* ((root ".run/policy-downstream-poo-agent-positive")
                 (_ (write-downstream-poo-agent-positive-project root))
                 (index (collect-project root))
                 (findings (run-agent-policy index)))
            (check findings => [])))
    (test-case "agent policy warns on broad runtime imports"
          (let* ((root ".run/policy-explicit-precise-import")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (reset-fixture-root root)
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/broad.ss")
                        ";;; -*- Gerbil -*-\n(package: sample/orders)\n(import :std/srfi/13)\n(def (starts? value) (string-prefix? \"a\" value))\n")
            (write-text (string-append owner "/precise.ss")
                        ";;; -*- Gerbil -*-\n(package: sample/orders)\n(import (only-in :std/srfi/13 string-prefix?))\n(def (starts? value) (string-prefix? \"a\" value))\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R018" findings))
                   (finding (car matching)))
              (check (length matching) => 1)
              (check (type-finding-path finding) => "src/orders/broad.ss")
              (check (type-finding-selector finding) => "src/orders/broad.ss:3-3"))))
    (test-case "agent policy rejects duplicate facade exports"
          (let* ((root ".run/policy-export-conflict")
                 (_alpha (write-facade-policy-project
                          root "alpha"
                          ";;; -*- Gerbil -*-\n;;; Alpha facade.\n(export value)\n"
                          ";;; -*- Gerbil -*-\n;;; Alpha core.\n(def value 1)\n"))
                 (_beta (write-facade-policy-project
                         root "beta"
                         ";;; -*- Gerbil -*-\n;;; Beta facade.\n(export value)\n"
                         ";;; -*- Gerbil -*-\n;;; Beta core.\n(def value 2)\n"))
                 (index (collect-project root))
                 (findings (run-agent-policy index))
                 (matching (filter-rule "GERBIL-SCHEME-AGENT-R003" findings))
                 (finding (car matching)))
            (check (length matching) => 1)
            (check (type-finding-rule-id finding)
                   => "GERBIL-SCHEME-AGENT-R003")
            (check (type-finding-path finding) => "src/beta/facade.ss")))))
