;;; -*- Gerbil -*-
;;; gerbil scheme harness agent style comment doc policy.

(import :gerbil/gambit
        :std/test
        :std/misc/ports
        :std/misc/process
        :std/sort
        :commands/check
        :parser/facade
        :policy/agent-style
        :policy/facade
        :policy/gxtest
        :scenario/policy
        :types/facade
        :unit/policy/poo-scenarios
        :policy/fixtures)
(import :policy/agent-style-support)
(export agent-style-comment-doc-policy-test)

;; PolicyTest
(def agent-style-comment-doc-policy-test
  (test-suite "gerbil scheme harness agent style comment doc policy"
(test-case "typed-combinator-style policy rejects inline function names"
          (let* ((root ".run/policy-typed-combinator-style-inline-name")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n(package: sample/orders)\n;; : (-> Order Money) ; order-total\n(def (order-total order) order)\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings))
                   (finding (car matching))
                   (details (type-finding-details finding)))
              (check (length matching) => 1)
              (check (hash-get details 'typedCommentCount) => 0)
              (check (hash-get details 'invalidTypedContractCount) => 1)
              (check (hash-get details 'missingTypedCommentCount) => 1))))
(test-case "typed-combinator-style policy rejects detached ledger contracts"
          (let* ((root ".run/policy-typed-combinator-style-ledger")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n(package: sample/orders)\n(def (order-total order) order)\n\n;;; typed-combinator-style ledger\n;; : (-> Order Money)\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings))
                   (finding (car matching))
                   (details (type-finding-details finding)))
              (check (length matching) => 1)
              (check (hash-get details 'typedCommentCount) => 0)
              (check (hash-get details 'missingTypedCommentCount) => 1)
              (check (hash-get details 'adjacency) => "definition-leading-comment"))))
(test-case "typed-combinator-style policy covers t scheme owners"
          (let* ((root ".run/policy-typed-combinator-style-test-owner")
                 (test-dir (string-append root "/t")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir test-dir)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append test-dir "/orders-test.ss")
                        ";;; -*- Gerbil -*-\n(import :std/test)\n(def (order-fixture order) order)\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings))
                   (finding (car matching)))
              (check (length matching) => 1)
              (check (type-finding-path finding) => "t/orders-test.ss")
              (check (hash-get (type-finding-details finding) 'scope)
                     => "source-or-test-owner"))))
(test-case "typed-combinator-style policy requires macro helpers to use full typed doc blocks"
          (let* ((root ".run/policy-typed-combinator-style-exported-doc-missing")
                 (src (string-append root "/src"))
                 (owner (string-append src "/macros")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/macros)\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n;;; Boundary:\n;;; - Fixture keeps macro expansion boundaries on full-form typed docs.\n(package: sample/macros)\n;; : (-> Syntax Syntax)\n(defsyntax (with-order-field stx)\n  #'(void))\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings))
                   (finding (car matching))
                   (details (type-finding-details finding)))
              (check (length matching) => 1)
              (check (hash-get details 'typedDocMissing) => #t)
              (check (hash-get details 'typedDocMissingCount) => 1)
              (check (hash-get details 'typedDocMissingTargets)
                     => ["with-order-field"])
              (check (hash-get details 'expectedDocShape)
                     => "full form for role/facet risk boundaries: leading name matching the definition, ;;   : signature, optional ;;   | type/contract/requires/warning/rationale fields, and ;;   | doc m% with # Examples fenced Scheme input/result")
              (check (hash-get details 'typedDocRequiredWhen)
                     => "arity-bearing macro/protocol/driver roles, or exported helpers that also carry parser-owned risk facets such as macro-runtime-source-witness, poo-protocol-evidence, or loop-driver-classified"))))
(test-case "typed-combinator-style policy accepts macro helpers with full typed doc blocks"
          (let* ((root ".run/policy-typed-combinator-style-exported-doc-present")
                 (src (string-append root "/src"))
                 (owner (string-append src "/macros")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/macros)\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n;;; Boundary:\n;;; - Fixture proves macro helpers can satisfy full-form typed docs.\n(package: sample/macros)\n;; with-order-field\n;;   : (-> Syntax Syntax)\n;;   | doc m%\n;;       `with-order-field stx` expands the order field syntax.\n;;\n;;       # Examples\n;;\n;;       ```scheme\n;;       (with-order-field #'field)\n;;       ;; => syntax\n;;       ```\n;;     %\n(defsyntax (with-order-field stx)\n  #'(void))\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings)))
              (check matching => []))))
(test-case "typed-combinator-style policy rejects full typed macro doc blocks with mismatched leading names"
          (let* ((root ".run/policy-typed-combinator-style-exported-doc-name-mismatch")
                 (src (string-append root "/src"))
                 (owner (string-append src "/macros")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/macros)\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n;;; Boundary:\n;;; - Fixture proves full-form docs must name the attached macro.\n(package: sample/macros)\n;; wrong-order-field\n;;   : (-> Syntax Syntax)\n;;   | doc m%\n;;       `with-order-field stx` expands the order field syntax.\n;;\n;;       # Examples\n;;\n;;       ```scheme\n;;       (with-order-field #'field)\n;;       ;; => syntax\n;;       ```\n;;     %\n(defsyntax (with-order-field stx)\n  #'(void))\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings))
                   (finding (car matching))
                   (details (type-finding-details finding)))
              (check (length matching) => 1)
              (check (hash-get details 'typedDocMissing) => #t)
              (check (hash-get details 'typedDocMissingTargets)
                     => ["with-order-field"]))))
(test-case "typed-combinator-style policy can be disabled by package config"
          (let* ((root ".run/policy-typed-combinator-style-disabled")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders\n  policy: ((agent-policy disabled-rules: (\"GERBIL-SCHEME-AGENT-R013\") explanation: \"Fixture owns R013 suppression regression separately.\")))\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n(package: sample/orders)\n(def (order-total order) order)\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings)))
              (check matching => []))))
  ))
