;;; -*- Gerbil -*-
;;; gerbil scheme harness agent basic policy.

(import :gerbil/gambit
        :std/test
        :std/misc/ports
        :std/misc/process
        (only-in :std/text/json read-json)
        :commands/check
        :parser/facade
        :policy/facade
        :policy/gxtest
        :types/facade
        :unit/policy/poo-scenarios
        :policy/fixtures)
(export agent-basic-policy-test)
;; PolicyTest
(def agent-basic-policy-test
  (test-suite "gerbil scheme harness agent basic policy"
    (test-case "agent policy requires facade intent comment"
          (let* ((root ".run/policy-agent")
                 (_ (write-facade-policy-project
                     root "bar"
                     ";;; -*- Gerbil -*-\n(export value)\n"
                     ";;; -*- Gerbil -*-\n;;; Bar core.\n(def value 1)\n"))
                 (index (collect-project root))
                 (findings (run-agent-policy index))
                 (matching (filter-rule "GERBIL-SCHEME-AGENT-R001" findings))
                 (finding (car matching)))
            (check (length matching) => 1)
            (check (type-finding-rule-id finding)
                   => "GERBIL-SCHEME-AGENT-R001")
            (check (type-finding-path finding) => "src/bar/facade.ss")))
    (test-case "agent policy rejects generic owner names"
          (let* ((root ".run/policy-generic-owner")
                 (_ (write-facade-policy-project
                     root "utils"
                     ";;; -*- Gerbil -*-\n;;; Utilities facade.\n(export value)\n"
                     ";;; -*- Gerbil -*-\n;;; Utilities core.\n(def value 1)\n"))
                 (index (collect-project root))
                 (findings (run-agent-policy index))
                 (matching (filter-rule "GERBIL-SCHEME-AGENT-R002" findings))
                 (finding (car matching)))
            (check (length matching) => 2)
            (check (type-finding-rule-id finding)
                   => "GERBIL-SCHEME-AGENT-R002")
            (check (not (not (member "src/utils/facade.ss"
                                      (map type-finding-path matching))))
                   => #t)))
    (test-case "agent policy rejects vague definition names"
          (let* ((root ".run/policy-vague-definition")
                 (_ (write-vague-definition-project root))
                 (index (collect-project root))
                 (findings (run-agent-policy index))
                 (matching (filter-rule "GERBIL-SCHEME-AGENT-R004" findings))
                 (finding (car matching)))
            (check (length matching) => 1)
            (check (type-finding-rule-id finding)
                   => "GERBIL-SCHEME-AGENT-R004")
            (check (type-finding-path finding) => "src/orders/core.ss")
            (check (type-finding-selector finding) => "src/orders/core.ss:3-3")))
    (test-case "package agent-policy disables selected rules"
          (let* ((root ".run/policy-agent-disabled-rule")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (reset-fixture-root root)
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders\n  policy: ((agent-policy disabled-rules: (\"GERBIL-SCHEME-AGENT-R004\") explanation: \"Fixture owns the vague-definition regression separately.\")))\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n(package: sample/orders)\n(def (process order) order)\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R004" findings)))
              (check matching => []))))
    (test-case "agent policy rejects top-level executable calls in src"
          (let* ((root ".run/policy-top-level-executable")
                 (_ (write-top-level-executable-project root))
                 (index (collect-project root))
                 (findings (run-agent-policy index))
                 (matching (filter-rule "GERBIL-SCHEME-AGENT-R005" findings))
                 (finding (car matching)))
            (check (length matching) => 1)
            (check (type-finding-rule-id finding)
                   => "GERBIL-SCHEME-AGENT-R005")
            (check (type-finding-path finding) => "src/orders/core.ss")
            (check (type-finding-selector finding) => "src/orders/core.ss:3-3")
            (check (type-finding-message finding)
                   => "top-level executable call displayln should move behind a named definition or explicit entrypoint")))
    (test-case "agent policy accepts explicit search-fast entrypoints"
          (let* ((root ".run/policy-search-fast-entrypoint")
                 (_ (write-search-fast-entrypoint-project root))
                 (index (collect-project root))
                 (findings (run-agent-policy index))
                 (matching (filter-rule "GERBIL-SCHEME-AGENT-R005" findings)))
            (check matching => [])))
    (test-case "agent policy accepts exported main script entrypoints"
      (let* ((root ".run/policy-exported-main-entrypoint")
             (src (string-append root "/src"))
             (owner (string-append src "/tools")))
        (reset-fixture-root root)
        (ensure-dir ".run")
        (ensure-dir root)
        (ensure-dir src)
            (ensure-dir owner)
            (write-text
             (string-append owner "/run.ss")
             ";;; -*- Gerbil -*-\n(export main)\n(def (main . args) 0)\n(exit (apply main (cdr (command-line))))\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R005" findings)))
              (check matching => []))))
    (test-case "agent policy accepts explicit test harness entrypoints"
      (let* ((root ".run/policy-test-harness-entrypoint")
             (test-root (string-append root "/t")))
        (reset-fixture-root root)
        (ensure-dir ".run")
        (ensure-dir root)
        (ensure-dir test-root)
        (write-text
         (string-append root "/gerbil.pkg")
         "(package: sample/test-harness-entrypoint)\n")
        (write-text
         (string-append test-root "/sample-test.ss")
         ";;; -*- Gerbil -*-\n(import :std/test)\n(def (subject) 1)\n(run-tests!\n (test-suite \"sample\"\n   (test-case \"works\"\n     (check (subject) => 1))))\n")
        (let* ((index (collect-project root))
               (findings (run-agent-policy index))
               (matching (filter-rule "GERBIL-SCHEME-AGENT-R005" findings)))
          (check matching => []))))
    (test-case "agent policy treats FFI declare body as declarative range"
          (let* ((root ".run/policy-ffi-declare-declarative")
                 (_ (write-ffi-declare-project root))
                 (index (collect-project root))
                 (findings (run-agent-policy index))
                 (matching (filter-rule "GERBIL-SCHEME-AGENT-R005" findings)))
            (check matching => [])))
    (test-case "agent policy treats POO declarative bodies as declarative ranges"
          (let* ((root ".run/policy-poo-declarative-range")
                 (_ (write-poo-declarative-project root))
                 (index (collect-project root))
                 (findings (run-agent-policy index))
                 (matching (filter-rule "GERBIL-SCHEME-AGENT-R005" findings)))
            (check matching => [])))
    (test-case "agent policy treats user config and module object fragments as declarative"
      (let* ((root ".run/policy-agent-declarative-config")
             (src (string-append root "/src"))
             (owner (string-append src "/custom")))
        (reset-fixture-root root)
        (ensure-dir ".run")
        (ensure-dir root)
        (ensure-dir src)
        (ensure-dir owner)
        (write-text
         (string-append root "/gerbil.pkg")
         "(package: sample/agent-declarative-config)\n")
        (write-text
         (string-append owner "/config.ss")
         ";;; -*- Gerbil -*-\n(load! \"profiles/session\")\n(use-module nono-sandbox)\n")
        (write-text
         (string-append owner "/object1.ss")
         ";;; -*- Gerbil -*-\n(list\n (poo-flow-module-object\n  'demo\n  (list (poo-flow-module-field-contract 'name 'symbol))))\n")
        (let* ((index (collect-project root))
               (findings (run-agent-policy index))
               (matching (filter-rule "GERBIL-SCHEME-AGENT-R005" findings)))
          (check matching => []))))
    (test-case "agent policy treats single alist metadata files as declarative"
      (let* ((root ".run/policy-agent-declarative-alist-metadata")
             (src (string-append root "/src"))
             (owner (string-append src "/metadata")))
        (reset-fixture-root root)
        (ensure-dir ".run")
        (ensure-dir root)
        (ensure-dir src)
        (ensure-dir owner)
        (write-text
         (string-append root "/gerbil.pkg")
         "(package: sample/agent-declarative-alist-metadata)\n")
        (write-text
         (string-append owner "/benchmark.ss")
         ";;; -*- Gerbil -*-\n((maxTotalMs . 120)\n (maxCollectMs . 1000)\n (feature . flow-strand-registry-merge)\n (measurementPhases prepare-fixture measure-best assert-time-gate))\n")
        (let* ((index (collect-project root))
               (findings (run-agent-policy index))
               (matching (filter-rule "GERBIL-SCHEME-AGENT-R005" findings)))
          (check matching => []))))
    (test-case "agent policy treats begin-syntax as declarative expansion boundary"
      (let* ((root ".run/policy-agent-declarative-begin-syntax")
             (src (string-append root "/src"))
             (owner (string-append src "/macros")))
        (reset-fixture-root root)
        (ensure-dir ".run")
        (ensure-dir root)
        (ensure-dir src)
        (ensure-dir owner)
        (write-text
         (string-append root "/gerbil.pkg")
         "(package: sample/agent-declarative-begin-syntax)\n")
        (write-text
         (string-append owner "/syntax.ss")
         ";;; -*- Gerbil -*-\n(begin-syntax\n  (def (syntax-helper stx) stx))\n(defsyntax (identity-syntax stx) (syntax-case stx () ((_ value) (syntax value))))\n")
        (let* ((index (collect-project root))
               (findings (run-agent-policy index))
               (matching (filter-rule "GERBIL-SCHEME-AGENT-R005" findings)))
          (check matching => []))))
    (test-case "agent policy preserves stateful named-let mutation loops"
      (let* ((root ".run/policy-agent-stateful-loop-driver")
             (src (string-append root "/src"))
             (owner (string-append src "/stateful")))
        (reset-fixture-root root)
        (ensure-dir ".run")
        (ensure-dir root)
        (ensure-dir src)
        (ensure-dir owner)
        (write-text
         (string-append root "/gerbil.pkg")
         "(package: sample/agent-stateful-loop-driver)\n")
        (write-text
         (string-append owner "/core.ss")
         ";;; -*- Gerbil -*-\n(def (dedupe values)\n  (let (seen (make-hash-table))\n    (let loop ((rest values) (out '()))\n      (cond\n       ((null? rest) (reverse out))\n       ((hash-get seen (car rest)) (loop (cdr rest) out))\n       (else\n        (hash-put! seen (car rest) #t)\n        (loop (cdr rest) (cons (car rest) out)))))))\n")
        (let* ((index (collect-project root))
               (findings (run-policy-checks index))
               (matching (filter-rule "GERBIL-SCHEME-AGENT-R009" findings)))
          (check matching => []))))
    (test-case "agent policy preserves stateful conditional hot paths"
      (let* ((root ".run/policy-agent-stateful-branch-driver")
             (src (string-append root "/src"))
             (owner (string-append src "/stateful")))
        (reset-fixture-root root)
        (ensure-dir ".run")
        (ensure-dir root)
        (ensure-dir src)
        (ensure-dir owner)
        (write-text
         (string-append root "/gerbil.pkg")
         "(package: sample/agent-stateful-branch-driver)\n")
        (write-text
         (string-append owner "/core.ss")
         ";;; -*- Gerbil -*-\n;;; Boundary: this owner keeps hash mutation explicit for a hot merge path.\n;; : (-> List List)\n(def (merge-values values)\n  (let (seen (make-hash-table))\n    (map (lambda (value)\n           (cond\n            ((not value) #f)\n            ((hash-get seen value) value)\n            ((symbol? value) (begin (hash-put! seen value #t) value))\n            ((pair? value) (begin (hash-put! seen value #t) value))\n            (else value)))\n         values)))\n")
        (let* ((index (collect-project root))
               (findings (run-policy-checks index))
               (matching (filter-rule "GERBIL-SCHEME-AGENT-R014" findings)))
          (check matching => []))))
    (test-case "agent policy keeps positive combinator owners out of broad style warnings"
      (let* ((root ".run/policy-agent-positive-combinator-style")
             (src (string-append root "/src"))
             (owner (string-append src "/style")))
        (reset-fixture-root root)
        (ensure-dir ".run")
        (ensure-dir root)
        (ensure-dir src)
        (ensure-dir owner)
        (write-text
         (string-append root "/gerbil.pkg")
         "(package: sample/agent-positive-combinator-style)\n")
        (write-text
         (string-append owner "/core.ss")
         ";;; -*- Gerbil -*-\n;;; Boundary: sequence helpers stay expression-level and data-only.\n;; : (-> List List)\n(def (positive-symbols values)\n  (filter symbol? values))\n")
        (let* ((index (collect-project root))
               (findings (run-policy-checks index))
               (r013 (filter-rule "GERBIL-SCHEME-AGENT-R013" findings))
               (r015 (filter-rule "GERBIL-SCHEME-AGENT-R015" findings)))
          (check r013 => [])
          (check r015 => []))))
    (test-case "agent policy ignores begin-syntax named-let loop drivers"
      (let* ((root ".run/policy-agent-begin-syntax-loop-driver")
             (src (string-append root "/src"))
             (owner (string-append src "/macros")))
        (reset-fixture-root root)
        (ensure-dir ".run")
        (ensure-dir root)
        (ensure-dir src)
        (ensure-dir owner)
        (write-text
         (string-append root "/gerbil.pkg")
         "(package: sample/agent-begin-syntax-loop-driver)\n")
        (write-text
         (string-append owner "/syntax.ss")
         ";;; -*- Gerbil -*-\n(begin-syntax\n  (def (syntax-list->list stx)\n    (let loop ((rest stx) (out '()))\n      (syntax-case rest ()\n        (() (reverse out))\n        ((head . tail)\n         (loop (syntax tail) (cons (syntax head) out)))\n        (_ #f)))))\n")
        (let* ((index (collect-project root))
               (findings (run-policy-checks index))
               (matching (filter-rule "GERBIL-SCHEME-AGENT-R009" findings)))
          (check matching => []))))
    (test-case "agent policy allows direct imports when they are public re-exports"
      (let* ((root ".run/policy-agent-import-reexport")
             (src (string-append root "/src"))
             (direct (string-append src "/direct"))
             (reexport (string-append src "/reexport")))
        (reset-fixture-root root)
        (ensure-dir ".run")
        (ensure-dir root)
        (ensure-dir src)
        (ensure-dir direct)
        (ensure-dir reexport)
        (write-text
         (string-append root "/gerbil.pkg")
         "(package: sample/agent-import-reexport)\n")
        (write-text
         (string-append direct "/core.ss")
         ";;; -*- Gerbil -*-\n(import :clan/poo/object)\n(def value (.o name: 'direct))\n")
        (write-text
         (string-append reexport "/interface.ss")
         ";;; -*- Gerbil -*-\n(import :clan/poo/object)\n(export #t (import: :clan/poo/object))\n(def value (.o name: 'reexport))\n")
        (let* ((index (collect-project root))
               (findings (run-agent-policy index))
               (matching (filter-rule "GERBIL-SCHEME-AGENT-R018" findings)))
          (check (length matching) => 1)
          (check (type-finding-path (car matching)) => "src/direct/core.ss"))))
    (test-case "package build policy accepts named std make build-spec helpers"
      (let* ((root ".run/policy-package-build-named-std-make-spec")
             (src (string-append root "/src")))
        (reset-fixture-root root)
        (ensure-dir ".run")
        (ensure-dir root)
        (ensure-dir src)
        (write-text
         (string-append root "/gerbil.pkg")
         "(package: sample/package-build-named-std-make-spec)\n")
        (write-text
         (string-append src "/core.ss")
         ";;; -*- Gerbil -*-\n(export value)\n(def value 1)\n")
        (write-text
         (string-append root "/build.ss")
         "#!/usr/bin/env gxi\n;;; -*- Gerbil -*-\n(import (only-in :std/make make))\n(def sample-build-spec '((gxc: \"src/core\")))\n(def (main . args) (apply make sample-build-spec srcdir: \".\" []))\n(apply main (cdr (command-line)))\n")
        (let* ((index (collect-project root))
               (findings (run-policy-checks index))
               (r020 (filter-rule "GERBIL-SCHEME-AGENT-R020" findings))
               (r025 (filter-rule "GERBIL-SCHEME-AGENT-R025" findings)))
          (check r020 => [])
          (check r025 => []))))
    (test-case "check changed scope reports only changed-file policy findings"
          (let* ((root ".run/policy-check-changed-scope")
                 (_ (write-check-changed-project root))
                 (_ (initialize-git-fixture root))
                 (_ (write-text (string-append root "/src/changed/core.ss")
                                ";;; -*- Gerbil -*-\n(package: sample/changed)\n(def (process x) x)\n"))
             (result (policy-check-output ["--changed" root]))
                 (output (cdr result)))
            (check (car result) => 1)
            (check (not (not (string-contains output "scope=changed"))) => #t)
            (check (not (not (string-contains output "src/changed/core.ss"))) => #t)
            (check (not (string-contains output "src/stable/core.ss")) => #t)))
    (test-case "agent policy preserves named-let control contexts"
          (let* ((root ".run/policy-functional-idiom-control-context")
                 (_ (write-functional-idiom-control-context-project root))
                 (index (collect-project root))
                 (findings (run-agent-policy index))
                 (matching (filter-rule "GERBIL-SCHEME-AGENT-R009" findings)))
            (check matching => [])))
    (test-case "agent policy accepts explicit higher-order idiom"
          (let* ((root ".run/policy-functional-idiom-positive")
                 (_ (write-functional-idiom-positive-project root))
                 (index (collect-project root))
                 (findings (run-agent-policy index))
                 (matching (filter-rule "GERBIL-SCHEME-AGENT-R009" findings)))
            (check (length matching) => 0)))
    (test-case "agent policy keeps functional idiom suppression caller scoped"
          (let* ((root ".run/policy-functional-idiom-caller-scope")
                 (_ (write-functional-idiom-caller-scope-project root))
                 (index (collect-project root))
                 (findings (run-agent-policy index))
                 (matching (filter-rule "GERBIL-SCHEME-AGENT-R009" findings))
                 (finding (car matching)))
            (check (length matching) => 1)
            (check (type-finding-selector finding) => "src/orders/core.ss:7-8")
            (check (hash-get (type-finding-details finding) 'caller)
                   => "manual-total")))
    (test-case "agent policy preserves native reader loops"
          (let* ((root ".run/policy-functional-idiom-reader")
                 (_ (write-functional-idiom-reader-project root))
                 (index (collect-project root))
                 (findings (run-agent-policy index))
                 (matching (filter-rule "GERBIL-SCHEME-AGENT-R009" findings)))
            (check (length matching) => 0)))))
