;;; -*- Gerbil -*-
;;; gerbil scheme harness agent style typed core policy.

(import :gerbil/gambit
        :std/test
        :std/misc/ports
        :std/misc/process
        :std/sort
        :gslph/src/parser/facade
        :gslph/src/policy/agent-style
        :gslph/src/policy/facade
        :gslph/src/policy/gxtest
        :gslph/src/scenario/policy
        :gslph/src/types/facade
        :unit/policy/poo-scenarios
        :policy/fixtures)
(import :policy/agent-style-support)
(export agent-style-typed-core-policy-test)

;; PolicyTest
(def agent-style-typed-core-policy-test
  (test-suite "gerbil scheme harness agent style typed core policy"
(test-case "typed-combinator-style policy is enabled by default"
          (let* ((root ".run/policy-typed-combinator-style-default")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n(package: sample/orders)\n(def (order-total order) order)\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-POLICY-013" findings))
                   (finding (car matching)))
              (check (length matching) => 1)
              (check (type-finding-severity finding) => "warning")
              (check (type-finding-path finding) => "src/orders/core.ss")
              (check (type-finding-selector finding) => "src/orders/core.ss")
              (check (hash-get (type-finding-details finding) 'styleGuide)
                     => "typed-combinator-style")
              (check (hash-get (type-finding-details finding) 'expectedCommentShape)
                     => "adjacent Gerbil contract projection block such as ;; : (forall (a) (-> (-> a a Order) (List a) (List a) Order))")
              (check (hash-get (type-finding-details finding) 'signatureShape)
                     => "adjacent Gerbil contract/signature projection using ;; : (forall (a) (-> Input Output)), optional ;; | type aliases, U unions, Values, and Refine predicates")
              (check (hash-get (type-finding-details finding) 'contractLinePolicy)
                     => "multi-line typed-combinator-style contracts are allowed when needed to preserve precision")
              (check (hash-get (type-finding-details finding) 'compositionShape)
                     => "Gerbil-native expression shape; prefer lambda-match/match for shape dispatch, cut/curry/rcurry for specialization, case-lambda for real arity boundaries, values/call-with-values for tuple projection, and map/filter/filter-map/fold/andmap/ormap for sequence transforms")
              (check (hash-get (type-finding-details finding) 'qualityReferenceCorpus)
                     => "gerbil-reference-corpus")
              (check (hash-get (type-finding-details finding) 'functionShape)
                     => "single-purpose expression-returning helper; one visible data-flow shape per function")
              (check (hash-get (type-finding-details finding) 'expressionLevelRewrite)
                     => "extract predicate/mapper/reducer helpers, then compose with lambda-match/match/cut/curry/case-lambda/values/filter-map/map/fold/andmap/ormap when behavior fits")
              (check (hash-get (type-finding-details finding) 'optimizationBoundary)
                     => "when using case-lambda or a specialized branch, comment why that branch exists and keep the comment about the boundary, not the code mechanics")
              (check (agent-style-member?
                      "Scheme-native ;; : contract blocks preserve arrow structure without comment-arrow fallback"
                      (hash-get (type-finding-details finding)
                                'gerbilContractProjectionSignals))
                     => #t))))
(test-case "typed-combinator-style policy rejects partial definition coverage"
          (let* ((root ".run/policy-typed-combinator-style-partial")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n(package: sample/orders)\n;; : (-> Order Order)\n(def (order-total order) order)\n(def (order-tax order) order)\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-POLICY-013" findings))
                   (finding (car matching))
                   (details (type-finding-details finding)))
              (check (length matching) => 1)
            (check (hash-get details 'definitionCount) => 2)
            (check (hash-get details 'typedCommentCount) => 1)
            (check (hash-get details 'missingTypedCommentCount) => 1)
            (check (hash-get details 'qualityReferenceCorpus) => "gerbil-reference-corpus")
            (check (hash-get details 'agentRepairStandard)
                   => "rewrite toward learned Gerbil/Gambit style: small algebraic helpers, lambda-match/match where shape is the boundary, cut/curry/case-lambda for specialization, values for tuple protocols, and minimal let*/mutation scaffolding"))))
(test-case "typed-combinator-style policy accepts algebraic contracts"
          (let* ((root ".run/policy-typed-combinator-style-contract")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n(package: sample/orders)\n;; : (-> Order Money)\n(def (order-total order) order)\n;; : (-> (List Order) (List Money))\n;; | type Money = Number\n(def (order-totals orders) (map order-total orders))\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-POLICY-013" findings)))
              (check matching => []))))
(test-case "typed-combinator-style policy reports boolean normalization scaffold"
          (let* ((root ".run/policy-typed-combinator-style-boolean-normalization")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text
             (string-append owner "/core.ss")
             ";;; -*- Gerbil -*-\n(package: sample/orders)\n;; : (-> (List Symbol) Boolean)\n(def (selected? choices)\n  (not (not (member 'ready choices))))\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-POLICY-013" findings))
                   (finding (car matching))
                   (details (type-finding-details finding))
                   (facets (hash-get details 'qualityFacets))
                   (steering (hash-get details 'qualityFacetSteering)))
              (check (length matching) => 1)
              (check (type-finding-path finding) => "src/orders/core.ss")
              (check (hash-get details 'qualityRepairTriggered) => #t)
              (check (agent-style-member? "boolean-normalization-drift" facets)
                     => #t)
              (check (agent-style-member? "generated-scaffold-shape" facets)
                     => #t)
              (check (agent-style-member?
                      "replace double-negation scaffolding with the underlying boolean expression, or name the predicate boundary when truthiness normalization is intentional"
                      steering)
                     => #t))))
(test-case "typed-combinator-style policy reports method-table lambda drift"
          (let* ((root ".run/policy-typed-combinator-style-method-table")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text
             (string-append owner "/core.ss")
             ";;; -*- Gerbil -*-\n(package: sample/orders)\n\
(define-type (Box @ [Wrapper.] T .wrap .unwrap)\n\
  .map: (lambda (f x) (.wrap (f (.unwrap x))))\n\
  .unwrap*: (cut .unwrap <>))\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-POLICY-013" findings))
                   (finding (car matching))
                   (details (type-finding-details finding))
                   (facets (hash-get details 'qualityFacets))
                   (steering (hash-get details 'qualityFacetSteering)))
              (check (length matching) => 1)
              (check (type-finding-path finding) => "src/orders/core.ss")
              (check (hash-get details 'qualityRepairTriggered) => #t)
              (check (agent-style-member? "method-table-lambda-drift" facets)
                     => #t)
              (check (agent-style-member? "method-table-combinator-body" facets)
                     => #t)
              (check (agent-style-member?
                      "repair method-table lambdas by extracting slot-shaped helpers, compiler-style AST pass handlers, or cut/curry/compose adapters while preserving the receiver/protocol boundary"
                      steering)
                     => #t))))
(test-case "typed-combinator-style policy rejects placeholder type variables"
          (let* ((root ".run/policy-typed-combinator-style-placeholder-token")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n(package: sample/orders)\n;; : (-> (List XX) NormalizeItems)\n(def (normalize-items xs) xs)\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-POLICY-013" findings))
                   (finding (car matching))
                   (details (type-finding-details finding))
                   (examples (hash-get details 'invalidTypedContractExamples))
                   (example (car examples)))
              (check (length matching) => 1)
              (check (hash-get details 'invalidTypedContractCount) => 1)
              (check (agent-style-member?
                      "placeholder-type-variable-token"
                      (hash-get details 'invalidTypedContractReasons))
                     => #t)
              (check (hash-get example 'definition) => "normalize-items"))))
(test-case "typed-combinator-style policy rejects structural pseudo types"
          (let* ((root ".run/policy-typed-combinator-style-structural-pseudo-type")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n(package: sample/orders)\n;; : (-> (List) Boolean)\n(def (ready? orders) #t)\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-POLICY-013" findings))
                   (finding (car matching))
                   (details (type-finding-details finding))
                   (examples (hash-get details 'invalidTypedContractExamples))
                   (example (car examples)))
              (check (length matching) => 1)
              (check (hash-get details 'invalidTypedContractCount) => 1)
              (check (agent-style-member?
                      "type-signature:List-requires-one-parameter"
                      (hash-get details 'invalidTypedContractReasons))
                     => #t)
              (check (hash-get example 'definition) => "ready?"))))
(test-case "typed-combinator-style policy accepts keyword-aware contracts"
          (let* ((root ".run/policy-typed-combinator-style-keyword-contract")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text
             (string-append owner "/core.ss")
             ";;; -*- Gerbil -*-\n(package: sample/orders)\n;; : (-> String SlotPrototype supers: (List SlotProfile) SlotProfile)\n(def (slot-profile name slots supers: (supers '())) slots)\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-POLICY-013" findings)))
              (check matching => []))))
(test-case "typed-combinator-style policy rejects malformed runtime contract arrows"
          (let* ((root ".run/policy-typed-combinator-style-runtime-contract-arrow")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text
             (string-append owner "/core.ss")
             ";;; -*- Gerbil -*-\n(package: sample/orders)\n;; : (-> Order Order)\n;; | contract Dyn -> (List) -> Dyn\n(def (normalize-order order) order)\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-POLICY-013" findings))
                   (finding (car matching))
                   (details (type-finding-details finding)))
              (check (length matching) => 1)
              (check (agent-style-member?
                      "runtime-contract[0]:function-parameter[1]:list-element:unknown-type"
                      (hash-get details 'invalidTypedContractReasons))
                     => #t))))
  ))
