;;; -*- Gerbil -*-
;;; Policy tests for gerbil-utils/base.ss-style higher-order abstraction.

(import :std/test
        :std/srfi/13
        :gslph/src/parser/facade
        :gslph/src/policy/facade
        :gslph/src/types/facade
        :policy/fixtures)

(export agent-style-higher-order-policy-test)

;; PolicyTest
(def agent-style-higher-order-policy-test
  (test-suite "gerbil scheme harness higher-order style policy"
    (test-case "agent policy warns on repeated wrapper lambdas without a combinator boundary"
          (let* ((root ".run/policy-wrapper-lambda-drift")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/facade.ss")
                        ";;; -*- Gerbil -*-\n;;; Orders facade intent.\n(export decorate)\n")
            (write-text
             (string-append owner "/core.ss")
             ";;; -*- Gerbil -*-\n(package: sample/orders)\n(export decorate)\n;; : (-> String String (-> String String))\n(def (decorate prefix suffix)\n  (let ((left (lambda (text) (string-append prefix text)))\n        (right (lambda (text) (string-append text suffix))))\n    (lambda (text) (right (left text)))))\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-POLICY-013" findings))
                   (finding (car matching))
                   (details (type-finding-details finding)))
              (check (length matching) => 1)
              (check (type-finding-path finding) => "src/orders/core.ss")
              (check (type-finding-severity finding) => "warning")
              (check (hash-get details 'qualityRepairTriggered) => #t)
              (check (not (not (member "wrapper-lambda-drift"
                                       (hash-get details 'qualityFacets))))
                     => #t)
              (check (not (not (member "function-specialization-opportunity"
                                       (hash-get details 'qualityFacets))))
                     => #t)
              (check (not (not (member "extract repeated wrapper lambdas into a named factory, case-lambda function factory, curry/rcurry specializer, or compose/rcompose pipeline"
                                       (hash-get details 'qualityFacetSteering))))
                     => #t)
              (check (not (not (string-contains
                                (type-finding-message finding)
                                "quality facets require repair")))
                     => #t))))
    (test-case "agent policy keeps case-lambda function factory as gerbil-utils style evidence"
          (let* ((root ".run/policy-case-lambda-factory")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/facade.ss")
                        ";;; -*- Gerbil -*-\n;;; Orders facade intent.\n(export decorate)\n")
            (write-text
             (string-append owner "/core.ss")
             ";;; -*- Gerbil -*-\n(package: sample/orders)\n(export decorate)\n;; : (-> String String (-> String String))\n(def decorate\n  (case-lambda\n    ((prefix) (lambda (text) (string-append prefix text)))\n    ((prefix suffix) (lambda (text) (string-append prefix text suffix)))))\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-POLICY-013" findings)))
              (check matching => []))))
    (test-case "agent policy requires forall for generic functional helper contracts"
          (let* ((root ".run/policy-functional-forall-contract")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/facade.ss")
                        ";;; -*- Gerbil -*-\n;;; Orders facade intent.\n(export pair-any?)\n")
            (write-text
             (string-append owner "/core.ss")
             ";;; -*- Gerbil -*-\n(package: sample/orders)\n(export pair-any?)\n;; : (-> (-> (Pair k v) Boolean) [(Pair k v)] Boolean)\n(def (pair-any? predicate values)\n  (ormap predicate values))\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-POLICY-013" findings))
                   (finding (car matching))
                   (details (type-finding-details finding)))
              (check (length matching) => 1)
              (check (hash-get details 'typedForallMissing) => #t)
              (check (not (not (member "pair-any?"
                                       (hash-get details 'typedForallMissingTargets))))
                     => #t)
              (check (not (not (string-contains
                                 (type-finding-message finding)
                                 "polymorphic generic line")))
                     => #t)
              (check (not (not (string-contains
                                 (type-finding-message finding)
                                 "domain summary line")))
                      => #t))))
    (test-case "agent policy requires polymorphic line when only domain summary is present"
          (let* ((root ".run/policy-functional-polymorphic-contract-missing")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/facade.ss")
                        ";;; -*- Gerbil -*-\n;;; Orders facade intent.\n(export pair-any?)\n")
            (write-text
             (string-append owner "/core.ss")
             ";;; -*- Gerbil -*-\n(package: sample/orders)\n(export pair-any?)\n;; : (-> Predicate Alist Boolean)\n(def (pair-any? predicate values)\n  (ormap predicate values))\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-POLICY-013" findings))
                   (finding (car matching))
                   (details (type-finding-details finding)))
              (check (length matching) => 1)
              (check (hash-get details 'typedForallMissing) => #t)
              (check (not (not (member "pair-any?"
                                       (hash-get details 'typedForallMissingTargets))))
                     => #t)
              (check (not (not (string-contains
                                 (type-finding-message finding)
                                 "polymorphic generic line")))
                     => #t))))
    (test-case "agent policy requires readable domain line when only polymorphic signature is present"
          (let* ((root ".run/policy-functional-domain-summary-missing")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/facade.ss")
                        ";;; -*- Gerbil -*-\n;;; Orders facade intent.\n(export pair-any?)\n")
            (write-text
             (string-append owner "/core.ss")
             ";;; -*- Gerbil -*-\n(package: sample/orders)\n(export pair-any?)\n;; : (forall (k v) (-> (-> (Pair k v) Boolean) [(Pair k v)] Boolean))\n(def (pair-any? predicate values)\n  (ormap predicate values))\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-POLICY-013" findings))
                   (finding (car matching))
                   (details (type-finding-details finding)))
              (check (length matching) => 1)
              (check (hash-get details 'typedForallMissing) => #t)
              (check (not (not (member "pair-any?"
                                       (hash-get details 'typedForallMissingTargets))))
                     => #t)
              (check (not (not (string-contains
                                 (type-finding-message finding)
                                 "readable/domain summary line")))
                     => #t))))
    (test-case "agent policy accepts forall on generic functional helper contracts"
          (let* ((root ".run/policy-functional-forall-contract-pass")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/facade.ss")
                        ";;; -*- Gerbil -*-\n;;; Orders facade intent.\n(export pair-any?)\n")
            (write-text
             (string-append owner "/core.ss")
              ";;; -*- Gerbil -*-\n(package: sample/orders)\n(export pair-any?)\n;; : (forall (k v) (-> (-> (Pair k v) Boolean) [(Pair k v)] Boolean))\n;; : (-> Predicate Alist Boolean)\n(def (pair-any? predicate values)\n  (ormap predicate values))\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-POLICY-013" findings)))
              (check matching => []))))
    (test-case "agent policy validates every layered signature line"
          (let* ((root ".run/policy-functional-layered-contract-invalid")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/facade.ss")
                        ";;; -*- Gerbil -*-\n;;; Orders facade intent.\n(export pair-values)\n")
            (write-text
             (string-append owner "/core.ss")
             ";;; -*- Gerbil -*-\n(package: sample/orders)\n(export pair-values)\n;; : (forall (k) (-> [(Pair k v)] [(Pair k v)]))\n;; : (-> Alist Alist)\n(def (pair-values values)\n  (filter-map (lambda (value) value) values))\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-POLICY-013" findings))
                   (finding (car matching))
                   (details (type-finding-details finding))
                   (reasons (hash-get details 'invalidTypedContractReasons)))
              (check (length matching) => 1)
              (check (hash-get details 'invalidTypedContractCount) => 1)
              (check (not (not (member
                                "type-signature[0]:unbound-type-variable:v"
                                reasons)))
                     => #t))))
    (test-case "agent policy accepts concrete Maybe Type contracts without forall"
          (let* ((root ".run/policy-functional-concrete-maybe-contract-pass")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/facade.ss")
                        ";;; -*- Gerbil -*-\n;;; Orders facade intent.\n(export maybe-type-any?)\n")
            (write-text
             (string-append owner "/core.ss")
             ";;; -*- Gerbil -*-\n(package: sample/orders)\n(export maybe-type-any?)\n;; : (-> (Maybe Type) (Maybe Type) Boolean )\n(def (maybe-type-any? left right)\n  (ormap (lambda (value) value) [left right]))\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-POLICY-013" findings)))
              (check matching => []))))
    (test-case "agent policy warns on multi-arity nested boolean predicates"
          (let* ((root ".run/policy-boolean-predicate-combinator")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/facade.ss")
                        ";;; -*- Gerbil -*-\n;;; Orders facade intent.\n(export path-matches-token?)\n")
            (write-text
             (string-append owner "/core.ss")
             ";;; -*- Gerbil -*-\n(package: sample/orders)\n(export path-matches-token?)\n;; : (-> Path String Boolean)\n(def (path-matches-token? relpath token)\n  (or (string-prefix? (string-append token \"/\") relpath)\n      (string-contains relpath (string-append \"/\" token \"/\"))\n      (string-suffix? (string-append \"/\" token) relpath)\n      (and (not (string-contains token \"/\"))\n           (string-contains relpath token))))\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-POLICY-016" findings))
                   (finding (car matching))
                   (details (type-finding-details finding)))
              (check (length matching) => 1)
              (check (type-finding-path finding) => "src/orders/core.ss")
              (check (type-finding-selector finding) => "src/orders/core.ss:5-10")
              (check (hash-get details 'styleGuide)
                     => "predicate-family-combinator")
              (check (hash-get details 'evidenceSource)
                     => "parser-owned booleanConditionFacts")
              (check (hash-get details 'conditionCount) => 6)
              (check (if (member "string-prefix?"
                                 (hash-get details 'conditionCallees))
                       #t
                       #f)
                     => #t)
              (check (if (member "string-suffix?"
                                 (hash-get details 'conditionCallees))
                       #t
                       #f)
                     => #t))))))
