;;; -*- Gerbil -*-
;;; gerbil scheme harness agent style comment doc policy.

(import :gerbil/gambit
        :std/test
        :std/misc/ports
        :std/misc/process
        :std/sort
        :commands/check
        :parser/facade
        :policy/agent-style
        :policy/facade
        :policy/gxtest
        :scenario/policy
        :types/facade
        :unit/policy/poo-scenarios
        :policy/fixtures)
(import :policy/agent-style-support)
(export agent-style-comment-doc-policy-test)

;; PolicyTest
(def agent-style-comment-doc-policy-test
  (test-suite "gerbil scheme harness agent style comment doc policy"
(test-case "typed-combinator-style policy rejects inline function names"
          (let* ((root ".run/policy-typed-combinator-style-inline-name")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n(package: sample/orders)\n;; Money <- Order ; order-total\n(def (order-total order) order)\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings))
                   (finding (car matching))
                   (details (type-finding-details finding)))
              (check (length matching) => 1)
              (check (hash-get details 'typedCommentCount) => 0)
              (check (hash-get details 'invalidTypedContractCount) => 1)
              (check (hash-get details 'missingTypedCommentCount) => 1))))
(test-case "typed-combinator-style policy rejects detached ledger contracts"
          (let* ((root ".run/policy-typed-combinator-style-ledger")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n(package: sample/orders)\n(def (order-total order) order)\n\n;;; typed-combinator-style ledger\n;; Money <- Order\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings))
                   (finding (car matching))
                   (details (type-finding-details finding)))
              (check (length matching) => 1)
              (check (hash-get details 'typedCommentCount) => 0)
              (check (hash-get details 'missingTypedCommentCount) => 1)
              (check (hash-get details 'adjacency) => "definition-leading-comment"))))
(test-case "typed-combinator-style policy covers t scheme owners"
          (let* ((root ".run/policy-typed-combinator-style-test-owner")
                 (test-dir (string-append root "/t")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir test-dir)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append test-dir "/orders-test.ss")
                        ";;; -*- Gerbil -*-\n(import :std/test)\n(def (order-fixture order) order)\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings))
                   (finding (car matching)))
              (check (length matching) => 1)
              (check (type-finding-path finding) => "t/orders-test.ss")
              (check (hash-get (type-finding-details finding) 'scope)
                     => "source-or-test-owner"))))
(test-case "typed-combinator-style policy requires exported helpers to use full typed doc blocks"
          (let* ((root ".run/policy-typed-combinator-style-exported-doc-missing")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n;;; Boundary:\n;;; - Fixture keeps ordinary helper contracts short and exported API docs audited.\n(package: sample/orders)\n(export order-totals)\n;; : (-> Order Money)\n(def (order-total order) order)\n;; : (-> (List Order) (List Money))\n;; | type Money = Number\n(def (order-totals orders) (map order-total orders))\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings))
                   (finding (car matching))
                   (details (type-finding-details finding)))
              (check (length matching) => 1)
              (check (hash-get details 'typedDocMissing) => #t)
              (check (hash-get details 'typedDocMissingCount) => 1)
              (check (hash-get details 'typedDocMissingTargets)
                     => ["order-totals"])
              (check (hash-get details 'expectedDocShape)
                     => "full form for exported helpers, macros, and policy-sensitive helpers: leading name matching the definition, ;;   : signature, optional ;;   | type/contract/requires/warning/rationale fields, and non-empty ;;   | doc m% block")
              (check (hash-get details 'typedDocRequiredWhen)
                     => "exported arity-bearing helper, macro, src/policy helper, or policy-sensitive helper"))))
(test-case "typed-combinator-style policy accepts exported helpers with full typed doc blocks"
          (let* ((root ".run/policy-typed-combinator-style-exported-doc-present")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n;;; Boundary:\n;;; - Fixture proves exported API helpers can satisfy full-form typed docs.\n(package: sample/orders)\n(export order-totals)\n;; : (-> Order Money)\n(def (order-total order) order)\n;; order-totals\n;;   : (-> (List Order) (List Money))\n;;   | type Money = Number\n;;   | doc m%\n;;       `order-totals orders` returns order totals for `orders`.\n;;     %\n(def (order-totals orders) (map order-total orders))\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings)))
              (check matching => []))))
(test-case "typed-combinator-style policy rejects full typed doc blocks with mismatched leading names"
          (let* ((root ".run/policy-typed-combinator-style-exported-doc-name-mismatch")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n;;; Boundary:\n;;; - Fixture proves full-form docs must name the attached definition.\n(package: sample/orders)\n(export order-totals)\n;; : (-> Order Money)\n(def (order-total order) order)\n;; wrong-order-totals\n;;   : (-> (List Order) (List Money))\n;;   | type Money = Number\n;;   | doc m%\n;;       `order-totals orders` returns order totals for `orders`.\n;;     %\n(def (order-totals orders) (map order-total orders))\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings))
                   (finding (car matching))
                   (details (type-finding-details finding)))
              (check (length matching) => 1)
              (check (hash-get details 'typedDocMissing) => #t)
              (check (hash-get details 'typedDocMissingTargets)
                     => ["order-totals"]))))
(test-case "typed-combinator-style policy can be disabled by package config"
          (let* ((root ".run/policy-typed-combinator-style-disabled")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders\n  policy: ((agent-policy disabled-rules: (\"GERBIL-SCHEME-AGENT-R013\"))))\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n(package: sample/orders)\n(def (order-total order) order)\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings)))
              (check matching => []))))
  ))
