;;; -*- Gerbil -*-
;;; gerbil scheme harness agent basic policy.

(import :gerbil/gambit
        :std/test
        :std/misc/ports
        :std/misc/process
        (only-in :std/text/json read-json)
        :commands/check
        :parser/facade
        :policy/facade
        :policy/gxtest
        :types/facade
        :unit/policy/poo-scenarios
        :policy/fixtures)
(export agent-basic-policy-test)
;; PolicyTest
(def agent-basic-policy-test
  (test-suite "gerbil scheme harness agent basic policy"
    (test-case "agent policy requires facade intent comment"
          (let* ((root ".run/policy-agent")
                 (_ (write-facade-policy-project
                     root "bar"
                     ";;; -*- Gerbil -*-\n(export value)\n"
                     ";;; -*- Gerbil -*-\n;;; Bar core.\n(def value 1)\n"))
                 (index (collect-project root))
                 (findings (run-agent-policy index))
                 (matching (filter-rule "GERBIL-SCHEME-AGENT-R001" findings))
                 (finding (car matching)))
            (check (length matching) => 1)
            (check (type-finding-rule-id finding)
                   => "GERBIL-SCHEME-AGENT-R001")
            (check (type-finding-path finding) => "src/bar/facade.ss")))
    (test-case "agent policy rejects generic owner names"
          (let* ((root ".run/policy-generic-owner")
                 (_ (write-facade-policy-project
                     root "utils"
                     ";;; -*- Gerbil -*-\n;;; Utilities facade.\n(export value)\n"
                     ";;; -*- Gerbil -*-\n;;; Utilities core.\n(def value 1)\n"))
                 (index (collect-project root))
                 (findings (run-agent-policy index))
                 (matching (filter-rule "GERBIL-SCHEME-AGENT-R002" findings))
                 (finding (car matching)))
            (check (length matching) => 2)
            (check (type-finding-rule-id finding)
                   => "GERBIL-SCHEME-AGENT-R002")
            (check (not (not (member "src/utils/facade.ss"
                                      (map type-finding-path matching))))
                   => #t)))
    (test-case "agent policy rejects vague definition names"
          (let* ((root ".run/policy-vague-definition")
                 (_ (write-vague-definition-project root))
                 (index (collect-project root))
                 (findings (run-agent-policy index))
                 (matching (filter-rule "GERBIL-SCHEME-AGENT-R004" findings))
                 (finding (car matching)))
            (check (length matching) => 1)
            (check (type-finding-rule-id finding)
                   => "GERBIL-SCHEME-AGENT-R004")
            (check (type-finding-path finding) => "src/orders/core.ss")
            (check (type-finding-selector finding) => "src/orders/core.ss:3-3")))
    (test-case "package agent-policy disables selected rules"
          (let* ((root ".run/policy-agent-disabled-rule")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders\n  policy: ((agent-policy disabled-rules: (\"GERBIL-SCHEME-AGENT-R004\"))))\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n(package: sample/orders)\n(def (process order) order)\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R004" findings)))
              (check matching => []))))
    (test-case "agent policy rejects top-level executable calls in src"
          (let* ((root ".run/policy-top-level-executable")
                 (_ (write-top-level-executable-project root))
                 (index (collect-project root))
                 (findings (run-agent-policy index))
                 (matching (filter-rule "GERBIL-SCHEME-AGENT-R005" findings))
                 (finding (car matching)))
            (check (length matching) => 1)
            (check (type-finding-rule-id finding)
                   => "GERBIL-SCHEME-AGENT-R005")
            (check (type-finding-path finding) => "src/orders/core.ss")
            (check (type-finding-selector finding) => "src/orders/core.ss:3-3")
            (check (type-finding-message finding)
                   => "top-level executable call displayln should move behind a named definition or explicit entrypoint")))
    (test-case "agent policy accepts explicit search-fast entrypoints"
          (let* ((root ".run/policy-search-fast-entrypoint")
                 (_ (write-search-fast-entrypoint-project root))
                 (index (collect-project root))
                 (findings (run-agent-policy index))
                 (matching (filter-rule "GERBIL-SCHEME-AGENT-R005" findings)))
            (check matching => [])))
    (test-case "agent policy treats FFI declare body as declarative range"
          (let* ((root ".run/policy-ffi-declare-declarative")
                 (_ (write-ffi-declare-project root))
                 (index (collect-project root))
                 (findings (run-agent-policy index))
                 (matching (filter-rule "GERBIL-SCHEME-AGENT-R005" findings)))
            (check matching => [])))
    (test-case "agent policy treats POO declarative bodies as declarative ranges"
          (let* ((root ".run/policy-poo-declarative-range")
                 (_ (write-poo-declarative-project root))
                 (index (collect-project root))
                 (findings (run-agent-policy index))
                 (matching (filter-rule "GERBIL-SCHEME-AGENT-R005" findings)))
            (check matching => [])))
    (test-case "agent policy rejects package build CLI routing"
          (let ((root ".run/policy-package-build-routing"))
            (ensure-dir ".run")
            (ensure-dir root)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/build-routing)\n")
            (write-text
             (string-append root "/build.ss")
             ";;; -*- Gerbil -*-\n(import :clan/base)\n(def (write-wrapper out)\n  (display \"if [ \\\"${1:-}\\\" = search ] && [ \\\"${2:-}\\\" = pattern ]; then\\n\" out))\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R019" findings))
                   (finding (car matching)))
              (check (length matching) => 1)
              (check (type-finding-path finding) => "build.ss")
              (check (type-finding-selector finding) => "build.ss:4-4")
              (check (hash-get (type-finding-details finding) 'kind)
                     => "package-build-responsibility"))))
    (test-case "agent policy rejects package build wrapper definitions"
          (let ((root ".run/policy-package-build-wrapper-definition"))
            (ensure-dir ".run")
            (ensure-dir root)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/build-wrapper)\n")
            (write-text
             (string-append root "/build.ss")
             ";;; -*- Gerbil -*-\n(import :clan/base)\n(def (write-native-link-wrapper build-prefix)\n  build-prefix)\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R019" findings))
                   (finding (car matching)))
              (check (length matching) => 1)
              (check (type-finding-path finding) => "build.ss")
              (check (type-finding-selector finding) => "build.ss:3-4")
              (check (hash-get (type-finding-details finding) 'kind)
                     => "package-build-wrapper-definition"))))
    (test-case "agent policy rejects build-support shell template regression"
          (let* ((root ".run/policy-build-support-shell-template")
                 (support (string-append root "/build-support")))
            (reset-fixture-root root)
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir support)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/build-support-quality)\n")
            (write-text
             (string-append support "/provider-cli.ss")
             ";;; -*- Gerbil -*-\n(def (shell-if condition body)\n  (string-append \"if [ \" condition \" ]; then\\n\" body \"\\nfi\\n\"))\n(def (shell-exec command)\n  (string-append \"exec \" command \" \\\"$@\\\"\\n\"))\n(def (write-wrapper out)\n  (display \"#!/bin/sh\\nset -eu\\n\" out)\n  (display \"find src -name '*.ss' -print | xargs gxc\\n\" out))\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R020" findings))
                   (finding (car matching))
                   (groups (hash-get (type-finding-details finding)
                                     'evidenceGroups)))
              (check (length matching) => 1)
              (check (type-finding-path finding)
                     => "build-support/provider-cli.ss")
              (check (not (not (member "shell-helper-definitions" groups)))
                     => #t)
              (check (not (not (member "shell-control-literals" groups)))
                     => #t))))
    (test-case "agent policy rejects package build shell pipelines"
          (let ((root ".run/policy-package-build-shell-pipeline"))
            (reset-fixture-root root)
            (ensure-dir ".run")
            (ensure-dir root)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/build-shell-pipeline)\n")
            (write-text
             (string-append root "/build.ss")
             ";;; -*- Gerbil -*-\n(def (refresh!)\n  (invoke \"sh\" [\"-c\" \"find src -name '*.ss' -print | xargs gxc -static\"])\n  #t)\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R020" findings))
                   (finding (car matching))
                   (groups (hash-get (type-finding-details finding)
                                     'evidenceGroups)))
              (check (length matching) => 1)
              (check (type-finding-path finding) => "build.ss")
              (check (not (not (member "shell-dispatch-call" groups)))
                     => #t)
              (check (not (not (member "shell-pipeline-literal" groups)))
                     => #t))))
    (test-case "agent policy accepts Gerbil runtime build-support wrappers"
          (let* ((root ".run/policy-build-support-gerbil-runtime")
                 (support (string-append root "/build-support")))
            (reset-fixture-root root)
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir support)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/build-support-runtime)\n")
            (write-text
             (string-append support "/provider-cli-runtime.ss")
             ";;; -*- Gerbil -*-\n(import :gerbil/gambit :std/misc/process)\n(def (run-command! command)\n  (let (status (run-process command check-status: #f))\n    (exit status)))\n(def (provider-cli-main args)\n  (run-command! (append [\"gxi\" \"bin/runner.ss\"] args)))\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R020" findings)))
              (check matching => []))))
    (test-case "check changed scope reports only changed-file policy findings"
          (let* ((root ".run/policy-check-changed-scope")
                 (_ (write-check-changed-project root))
                 (_ (initialize-git-fixture root))
                 (_ (write-text (string-append root "/src/changed/core.ss")
                                ";;; -*- Gerbil -*-\n(package: sample/changed)\n(def (changed-value x) x)\n"))
             (result (policy-check-output ["--changed" root]))
                 (output (cdr result)))
            (check (car result) => 1)
            (check (not (not (string-contains output "scope=changed"))) => #t)
            (check (not (not (string-contains output "src/changed/core.ss"))) => #t)
            (check (not (string-contains output "src/stable/core.ss")) => #t)))
    (test-case "agent policy reports named-let preservation control contexts"
          (let* ((root ".run/policy-functional-idiom-control-context")
                 (_ (write-functional-idiom-control-context-project root))
                 (index (collect-project root))
                 (findings (run-agent-policy index))
                 (matching (filter-rule "GERBIL-SCHEME-AGENT-R009" findings))
                 (finding (car matching))
                 (contexts (hash-get (type-finding-details finding)
                                     'detectedControlContexts)))
            (check (length matching) => 1)
            (check (type-finding-severity finding) => "warning")
            (check (not (not (member "continuation-control" contexts))) => #t)
            (check (not (not (member "protected-control" contexts))) => #t)
            (check (not (not (member "protected-handler" contexts))) => #t)))
    (test-case "agent policy accepts explicit higher-order idiom"
          (let* ((root ".run/policy-functional-idiom-positive")
                 (_ (write-functional-idiom-positive-project root))
                 (index (collect-project root))
                 (findings (run-agent-policy index))
                 (matching (filter-rule "GERBIL-SCHEME-AGENT-R009" findings)))
            (check (length matching) => 0)))
    (test-case "agent policy keeps functional idiom suppression caller scoped"
          (let* ((root ".run/policy-functional-idiom-caller-scope")
                 (_ (write-functional-idiom-caller-scope-project root))
                 (index (collect-project root))
                 (findings (run-agent-policy index))
                 (matching (filter-rule "GERBIL-SCHEME-AGENT-R009" findings))
                 (finding (car matching)))
            (check (length matching) => 1)
            (check (type-finding-selector finding) => "src/orders/core.ss:7-8")
            (check (hash-get (type-finding-details finding) 'caller)
                   => "manual-total")))
    (test-case "agent policy preserves native reader loops"
          (let* ((root ".run/policy-functional-idiom-reader")
                 (_ (write-functional-idiom-reader-project root))
                 (index (collect-project root))
                 (findings (run-agent-policy index))
                 (matching (filter-rule "GERBIL-SCHEME-AGENT-R009" findings)))
            (check (length matching) => 0)))))
