;;; -*- Gerbil -*-
;;; gerbil scheme harness agent style comment core policy.

(import :gerbil/gambit
        :std/test
        :std/misc/ports
        :std/misc/process
        :std/sort
        :commands/check
        :parser/facade
        :policy/agent-style
        :policy/facade
        :policy/gxtest
        :scenario/policy
        :types/facade
        :unit/policy/poo-scenarios
        :policy/fixtures)
(import :policy/agent-style-support)
(export agent-style-comment-core-policy-test)

;; PolicyTest
(def agent-style-comment-core-policy-test
  (test-suite "gerbil scheme harness agent style comment core policy"
(test-case "comment-quality policy rejects contract-only engineering comments"
          (let* ((root ".run/policy-comment-quality-contract-only")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n;;; Fixture has module intent so only definition comment quality is tested.\n(package: sample/orders)\n;; : (-> Order Money)\n(def (order-total order) order)\n;; : (-> (List Order) (List Money))\n(def (order-totals orders) (map order-total orders))\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R015" findings))
                   (finding (car matching))
                   (details (type-finding-details finding))
                   (example (car (hash-get details 'weakCommentExamples)))
                   (parser-evidence (hash-get example 'parserEvidence))
                   (matched-fact (car (hash-get parser-evidence 'matchedFacts)))
                   (repair (finding-agent-repair-json finding)))
              (check (length matching) => 1)
              (check (hash-get details 'weakCommentCount) => 1)
              (check (hash-get details 'evidenceSource)
                     => "parser-owned commentQualityFacts.evidence")
              (check (hash-get details 'repairInstruction)
                     => "write adjacent engineering comment lines when parserEvidence needs them; concise prose, bullets, or Boundary/Invariant/Intent labels are all valid")
              (check (hash-get example 'target) => "order-totals")
              (check (hash-get example 'quality) => "weak")
              (check (hash-get example 'commentKind) => "contract-only")
              (check (hash-get parser-evidence 'definition) => "order-totals")
              (check (hash-get parser-evidence 'context) => "higher-order")
              (check (hash-get parser-evidence 'matchedFactCount) => 1)
              (check (hash-get matched-fact 'factKind) => "higher-order")
              (check (hash-get matched-fact 'role) => "sequence-map")
              (check (hash-get details 'typedContractBoundary)
                     => "Scheme-native typed blocks describe algebraic shape only and may use adjacent multi-line contract blocks when needed")
              (check (hash-get repair 'guideCommand)
                     => "asp gerbil-scheme guide --code --rule GERBIL-SCHEME-AGENT-R015 --intent style"))))
(test-case "comment-quality policy rejects compressed engineering comments"
          (let* ((root ".run/policy-comment-quality-compressed")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n;;; Boundary:\n;;; - Fixture owns the comment-quality compression scenario.\n(package: sample/orders)\n;;; Boundary: order-totals maps order-total across orders; keep higher-order data-flow visible.\n;; : (-> (List Order) (List Money))\n(def (order-totals orders) (map order-total orders))\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R015" findings))
                   (finding (car matching))
                   (details (type-finding-details finding))
                   (example (car (hash-get details 'weakCommentExamples))))
              (check (length matching) => 1)
              (check (hash-get example 'target) => "order-totals")
              (check (hash-get example 'commentKind) => "compressed-engineering")
              (check (hash-get example 'quality) => "weak")
              (check (hash-get example 'reasons)
                     => ["compressed-engineering-comment-needs-adjacent-lines"])
              (check (hash-get details 'commentLinePolicy)
                     => "split multi-clause engineering rationale across adjacent comment lines when it improves confidence; do not squeeze rationale clauses into one semicolon-separated line"))))
(test-case "typed-combinator-style policy rejects typed contracts without implementation evidence"
          (let* ((root ".run/policy-typed-combinator-style-no-implementation-evidence")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n(package: sample/orders)\n;; : (-> Order Money)\n(def (order-total order) order)\n;; : (-> Order Tax)\n(def (order-tax order) order)\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings))
                   (finding (car matching))
                   (details (type-finding-details finding)))
              (check (length matching) => 1)
              (check (hash-get details 'typedCommentCount) => 2)
              (check (hash-get details 'missingTypedCommentCount) => 0)
              (check (hash-get details 'implementationEvidenceCount) => 0)
              (check (hash-get details 'missingImplementationEvidence) => #t)
              (check (hash-get details 'passiveRepairFlow)
                     => "policy-finding -> agentRepair -> guide-code -> bounded edit")
              (check (hash-get details 'implementationEvidenceSource)
                     => "parser-owned higherOrderFacts plus callFacts; do not use raw text heuristics"))))
(test-case "typed-combinator-style policy rejects Any contracts"
          (let* ((root ".run/policy-typed-combinator-style-any")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n(package: sample/orders)\n;; : (-> Any Any)\n(def (order-total order) order)\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings))
                   (finding (car matching))
                   (details (type-finding-details finding)))
              (check (length matching) => 1)
              (check (hash-get details 'definitionCount) => 1)
              (check (hash-get details 'typedCommentCount) => 0)
              (check (hash-get details 'validTypedContractCount) => 0)
              (check (hash-get details 'invalidTypedContractCount) => 1)
              (check (hash-get details 'missingTypedCommentCount) => 1))))
(test-case "typed-combinator-style policy rejects placeholder contracts"
          (let* ((root ".run/policy-typed-combinator-style-placeholder")
                 (src (string-append root "/src"))
                 (owner (string-append src "/orders")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/orders)\n")
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n(package: sample/orders)\n;; : (-> Fact Value (List XX))\n(def (order-total order) order)\n")
            (let* ((index (collect-project root))
                   (findings (run-policy-checks index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-R013" findings))
                   (finding (car matching))
                   (details (type-finding-details finding)))
              (check (length matching) => 1)
              (check (hash-get details 'typedCommentCount) => 0)
              (check (hash-get details 'invalidTypedContractCount) => 1)
              (check (hash-get details 'missingTypedCommentCount) => 1)
              (check (hash-get details 'invalidReason)
                     => "typed-combinator-style comments must be parser-owned adjacent algebraic transform signatures; see invalidTypedContractReasons for exact parser reasons")
              (check (hash-get details 'invalidTypedContractReasons)
                     => ["placeholder-type-variable-token"
                         "placeholder-contract-without-domain-or-higher-order-shape"])
              (check (hash-get (car (hash-get details 'invalidTypedContractExamples))
                               'contract)
                     => "(-> Fact Value (List XX))")
              (check (hash-get (car (hash-get details 'invalidTypedContractExamples))
                               'quality)
                     => "invalid"))))
  ))
